### ISSUE TITLE
Peak Watcher which leaves traces in projects

### ISSUE THREAD

**Issue by reaperaccessible** [jcsteh/osara#1065]
Sorry for the title of this issue but I couldn't find any other words.
I shared a Reaper project with a person who is not blind and who uses Reaper 7.15. When he opens the project, he gets a warning telling him that this project was saved with an extension that is not installed. The name of the extension is Peak Watcher. However, in my project, the Peak Watcher is not activated on any track nor the master. It's not the end of the world but I just wanted to alert you to this. Maybe this is normal.

**Comment by jcsteh** [comment]
This is a side effect of the work to make the Peak Watcher settings project specific. The Peak Watcher settings are saved within the project itself. We can't just avoid saving these if the Peak Watcher is disabled because that would cause any changes the user has made to notify level, hold time, etc. to be lost. I guess it might be possible to avoid saving the data if neither watcher differs from the default settings.

**Comment by reaperaccessible** [comment]
It's great to be able to save the Peak Watcher settings in the project.
I just wanted to know if this was normal. We just need to mention to the person with whom we share projects that they should ignore this notification.
I guess it's impossible to add conditions like, if OSARA is not installed, ignore the Peak Watcher information when loading the project.

**Comment by jcsteh** [comment]
> I guess it's impossible to add conditions like, if OSARA is not installed, ignore the Peak Watcher information when loading the project.

Unfortunately, this isn't possible. If OSARA isn't installed, it can't add any conditions at all, and it's not possible to add such conditions into the project data.
