### ISSUE TITLE
Missing string possibility for OSARA translation

### ISSUE THREAD

**Issue by reaperaccessible** [jcsteh/osara#1087]
I can't find the following action for translation, is this normal?
OSARA: Report tempo and time signature at play cursor; press twice to add/edit tempo markers
Thanks.

**Comment by ScottChesworth** [comment]
Hmm that's strange, it's definitely in the latest translation template, right after "OSARA: Open online documentation". Are you sure you have the latest template there?
https://ci.appveyor.com/api/buildjobs/6yws1a1132emrn10/artifacts/locale/osara_2024.5.20.1434,e91a354b.pot

**Comment by jcsteh** [comment]
@reaperaccessible, where are you downloading the fr_CA.po file from? Are you getting it from Crowdin or GitHub?

**Comment by jcsteh** [comment]
I just looked at fr_CA.po on Crowdin and I see this:

```
msgid "OSARA: Report tempo and time signature at play cursor; press twice to add/edit tempo markers"
msgstr "Marqueurs de tempo"
```

So the string is definitely there. I know you've had trouble accessing the file on Crowdin in the past, so here's the direct link again:
https://crowdin.com/editor/osara/4/en-frca?view=comfortable&filter=basic&value=2
Just open that link and press control+s to download the file.

**Comment by reaperaccessible** [comment]
Ok, I understand, did you change this sentence because it was already translated but before it was only "Tempo marker".
That's why I couldn't find it.
I will now use the download/upload method of the .po file.
To locate the most relevant strings that have been added, are they always added to the beginning of the file?

**Comment by ScottChesworth** [comment]
No those are different, "tempo marker" has been a separate string for a long time. Not sure how those got confused, but it seems like you're back on track so I'm closing this. Reopen if there are any problems I've missed.

**Comment by jcsteh** [comment]
Yeah, I'm not sure how that translation got there. Is it at all possible that you accepted a suggestion Crowdin offered by mistake?

As far as Crowdin is concerned, we can't change strings, only add and remove them. So even if we were to change a string, it would show up as a new string in Crowdin. I think Crowdin might be able to make suggestions though.

How have you previously downloaded and uploaded your translations to Crowdin in the past?

You can upload a .po file to Crowdin by pressing control+insert. If you're using NVDA, that'll need to be control+insert twice, since NVDA will swallow the first press of insert as the NVDA key.
