### ISSUE TITLE
Reaper suddenly not giving any speech output at all.

### ISSUE THREAD

**Issue by TheChiMaster** [jcsteh/osara#1158]
I just opened my computer today with the intention of working on a project. I opened reaper, and when I got to the window it didn't report "trackview" for some reason. I switched focus a few times hoping the issue would resolve, and it didn't. The title wasn't even announced when switching to it from the task switcher. I terminated the processes and restarted, but the same thing happened. But when I did switch focus to reaper and pressed space, the metronome started playing. No reporting of play / pause, not reporting of cursor moving, no reading of ribbon menus, not a single thing. I am confused and have no idea what is going on. I reinstalled everything, nothing has worked. I tried this on another computer and it worked, I am not sure where the issue lies.

**Comment by ScottChesworth** [comment]
Which OS and screen reader are you using? If it's Windows and NVDA, this is likely being caused by LBL add-on. Here's a link to update that, please be sure to read the term of use before downloading:
https://reaperaccessible.fr/index.php?option=com_content&view=article&id=421&Itemid=283&lang=en-us

Hope that gets you back up and running. Please let us know either way.

**Comment by TheChiMaster** [comment]
The issue has been resolved thank you so much. It turns out that the LBL
add-on was playing up.

Thank you so much you’re a legend

**Comment by ScottChesworth** [comment]
Glad to hear you're back in business! :)
