### ISSUE TITLE
request to create some kind of keymap updater

### ISSUE THREAD

**Issue by Binary-solo1** [jcsteh/osara#1169]
For me, it is very disruptive to my workflow when new versions of the Osara keymap throw out everything that has been added, be it custom actions or stuff added by extensions like Reapack. I know the way around this is not to replace the keymap with the Osara distributed version. I usually choose to do that though since there is a lot of thought that's gone into the Osara keymap and I like to stick to that as much as I can only mapping stuff occasionally when I need something. Anyway, just wanted to draw attention to this. If there was a way for Osara to update rather than replace the existing keymap I think that would be a huge quality of life improvement for us.

**Comment by ScottChesworth** [comment]
Some groundwork has already been done on this in preparation for OSARA to ship a layered map. However, it's a difficult undocumented format, requires contributors with plenty of experience of stress testing and debugging. I'm closing this for now only because it's already covered in other open issues, but rest assured we're trying.
