### ISSUE TITLE
Urgent: re Peakwatcher

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#119]
Hi, 

Over the past few months I have become increasingly convinced that the peakwatcher is inconsistent. At first, when I discussed this with other users, they hadn't noticed it, so I attributed the problem to random elements in the effects I was using. 

However, running Reaper 5.4 64 bit on a Windows 8.1 system on a freshly insert media item with no effects, with the peakwatcher set to follow current track, the peak level measured will vary by up to a DB or more when reset. 

I play the item, I reset the peakwatcher, rehighlight the track, play the item again and the values are different. 

Obviously this makes doing anything precise very difficult, meaning that one has to relie on a limiter to avoid clipping and this is far from ideal, meaning that using Reaper for professional applications is less of a safe bet. 

I don't remember the peakwatcher exhibiting this behaviour when it was first revised, so wonder if it's a setting I need to change or if something in one of the Reaper/Osara updates has broken things. At least one other user has been able to replicate this behaviour. 

I would be very grateful for anything that could be doneor, if it's a settings issue, any advice you can give. 

Thanks very much in advance, 

Regards, 

Justin

**Comment by jcsteh** [comment]
This is probably to do with the way the Peak Watcher works, although I
didn't originally foresee it affecting us in this way. The only way we can
watch peaks is to repeatedly fetch the peak info for the track. However, we
can't just do this over and over; we havve to allow REAPER time to do other
things like handle commands from the user, display the UI, etc. So, we do
it on a timer. Currently, that timer is about 30 ms. I'm guessing that this
is causing us to read peaks differently depending on how our peak watcher
timer and REAPER's display of peaks line up.

REAPER has a Meter decay preference (in Appearance -> Track Control Panels)
which determines how fast the meters drop after a peak. By default, that is
set to 120dB/second. If my math is correct, that'd mean it decays 3.6dB per
30 ms, which means that the worst we can lose is... quite a bit.
Interestingly, the default meter update frequency is 30 Hz, which I think
means one update every 33 ms or so. Wouldnt this mean sighted users would
also miss information?


Control surfaces update meters in a similar way, so I would have thought
they'd be similarly affected.

I can try increasing the timer frequency to see if this helps, but I don't
think it will fix this completely, even if it improves it.

Are you able to provide any details on/find out how sighted users deal with
precise metering? I wouldn't have thought they were able to see exact
peaks; it would be too fast. I guess maybe they adjust the meter decay.
This would also help OSARA, though it's not ideal for us to have to
instruct users to mess with preferences.

**Comment by jcsteh** [comment]
Can anyone answer my last question here regarding how sighted users deal with metering if 30 ms updates aren't sufficient? @ScottChesworth, any possibility of you getting some helpful eyes on this?

**Comment by ScottChesworth** [comment]
I have a working set of watchers available today yep. They're not familiar with metering, but should be able to describe what they're seeing well enough to shed at least some light. My thought was to grab the peak value from some sources with different dynamics using peak watcher, then compare that to what they say the peak would be by watching the meters when I play the same sources with the meter at default settings. That's far from scientific, so if you can think of a better way, let me know.

**Comment by ScottChesworth** [comment]
While I wait for feedback on how you want this tested, I've snipped a
couple of sample clips out from the song that's on the chopping block
today, have run a few tests of SWS item analysis vs peak watcher and
logged the results in case that's useful for anything. SWS is
consistent (presumably because it's an offline analysis), but Peak
Watcher seems to be giving me ranges of up to 6DB across multiple
tests. Uh oh! Happy to upload the results and the audio I've used to
test once I have results from a sightling incorporated.

**Comment by ScottChesworth** [comment]
Jamie, here are the results of what I tried yesterday, a description of what level of accuracy a sighted user experiences, and the files I used for reference.

I tested each scenario below 5 times.

Click.flac (whole file):
SWS reports peak is -0.89 consistently
Sighted user reports -0.9 consistently
Peak watcher reports -0.9 consistently

Click.flac (just the first click):
SWS reports -3.27 consistently
Sighted user reports -3.3 consistently
Peak watcher reports a range from -3.3 to -8.5

Drums.flac (whole file):
SWS reports -0.6 on both channels consistently
Sighted user reports -0.6 consistently for hard kicks and snares, with ghosts hovering around -18.
Peak watcher reports -0.6 consistently

Drums.flac (just the second to last snare (the one with the open hats)):
SWS reports -0.6 consistently both channels
Peak watcher reports range of -06 to -5.3 on channel 1 and -0.6 to -6.2 on channel 2 (only 2 of the 5 tests yielded the same result)
Sighted user reports -0.6 consistently

Here's a short description of what a sighted user is able to get from the meter when playing the 3 files I've attached:
Reaper's default setup seems to respond almost instantly to each transient, and also decays fast enough that a decent level of accuracy is visible. For example, I isolated 3 ghost notes in Drums.flac, and without playing the audio out loud, the sighted user confirmed 3 bounces of the meter around -18. When playing the whole file without any audio, the visuals were illustrative enough that she was able to beatbox what she thought the drum pattern would sound like with reasonable accuracy, just from watching the meter. Investigating a little further, I used the first of those muted triplet thunk thingies from the file bass.flac, which is (I think) a 16 note triplet at 130BPM. Looking at the meter without hearing the audio this time, she predicted there'd be two hits rather than 3, which were confirmed to be the first and third once I played the audio out loud along with the visual reference.

Conclusion, Peak Watcher seems to be struggling with the shorter examples. Beyond that, I know diddly squat about what to draw from this or how to firm up the findings. Let me know if you need any additional info to be gathered.
[Scotts peak watcher test files.zip](https://github.com/jcsteh/osara/files/1547170/Scotts.peak.watcher.test.files.zip)

**Comment by jcsteh** [comment]
Thanks for the detailed data, @ScottChesworth. I spent a while on this today. I tried decreasing the timer interval to 1 ms. I even tried faking a control surface to fetch meters the same way a surface does. The results were still far too variable. I guess surface metering isn't as accurate as the on screen meters? That probably makes sense, since they mostly just display clipping, rather than values.

There's one more thing I can try when I have some time. I'm not convinced this timer is actually running at 1 ms; Windows timers aren't necessarily that accurate. If REAPER will allow me to check meters from a background thread, I can try doing this in another thread, where I can be more accurate with timing. I'm not sure if REAPER will allow that, though.

**Comment by jcsteh** [comment]
Well, turns out all of this thread and timer frequency stuff is unnecessary and REAPER already provides a way to do this kind of thing that I missed. (In my defence, documentation is... negligible.) I'm pretty sure I've fixed this properly now, though I haven't tested extensively with different scenarios. Please test and let me know if you see any issues.

**Comment by ScottChesworth** [comment]
Awesome sauce! Looking forward to taking this for a spin.
