### ISSUE TITLE
Exporting outputMsg to reaper scripts

### ISSUE THREAD

**Issue by brhbrh** [jcsteh/osara#122]
In order to create accessible scripts in LUA, python, EEL, it would be great to have access to OSARA functions like outputMsg, 

For example, I've attached a LUA script I'm working on to speak the current track volume.
I currently use messageBox but speaking via OSARA's outputMsg would be better.

In addition, by exporting this function (and possibly others?), the community could contribute to reaper access with accessible scripts without the full complexity of being an OSARA/c++/reaper/extension developer.

[SayVolume.txt](https://github.com/nvaccess/osara/files/1236562/SayVolume.txt)

**Comment by jcsteh** [comment]
I can certainly export this, but note that because of the way this is implemented, it will work in custom REAPER views like the track view, but it won't work in controls that already provide their own accessibility; e.g. list views such as the MIDI Event List. That distinction might be a bit tricky to explain to developers without experience in Windows accessibility. That said, I guess it's still better than nothing.

**Comment by leonardder** [comment]
Would it makes sense to switch to UIAutomation notifications for Windows 10 1709 and higher? It might be a bit too much overkill, but I think other cases may benefit from this. For example, while JAWS and Narrator work with OSARA, JAWS tends to be pretty slow with announcing name changes, whereas Narrator insists on reporting the role after the name change.

**Comment by jcsteh** [comment]
I absolutely think we should do this, yes. There are other advantages too;
e.g. we can use notifications with higher importance to silence earlier
notifications, which is necessary when making a lot of changes from a
surface (since otherwise speech won't be interrupted). (NVDA doesn't
interrupt speech for any UIA notifications yet, but I think it'd be
reasonable to consider changing that.) However, this should be handled in a
separate issue; it's not really related to this one.

**Comment by yplassiard** [comment]
Subscribing to this thread to be aware of subsequent changes

**Comment by Timtam** [comment]
This seems to be a rather old issue, is there any progress on this, or are there still any decisions to make?

**Comment by jcsteh** [comment]
I'm a little reluctant to implement this  because of the gotchas mentioned in https://github.com/jcsteh/osara/issues/122#issuecomment-323565074. It's not going to work sometimes and developers without deep expertise in Windows accessibility and how OSARA works aren't going to understand why, which will probably result in a bunch of issues/support requests being raised that will all just be "I can't fix this". That's not really something I want to deal with.

Aside from that, there's also the issue of needing to generate and ship a Python wrapper module. But maybe we could just provide instructions to Python devs to do this in their own code if they need to.

**Comment by Timtam** [comment]
> I'm a little reluctant to implement this because of the gotchas mentioned in [#122 (comment)](https://github.com/jcsteh/osara/issues/122#issuecomment-323565074). It's not going to work sometimes and developers without deep expertise in Windows accessibility and how OSARA works aren't going to understand why, which will probably result in a bunch of issues/support requests being raised that will all just be "I can't fix this". That's not really something I want to deal with.

Understandable, but something that a GitHub template and/or README comment can at least handle partially. Maybe even adding a FAQ to the README and pointing to that before creating an issue might prevent such questions beforehand. It would still be better than nothing I guess, and especially lua doesn't have any other easy way to communicate with screen readers, even adding external libs seems to be rather complicated, and we're not even talking about Mac here.

> Aside from that, there's also the issue of needing to generate and ship a Python wrapper module. But maybe we could just provide instructions to Python devs to do this in their own code if they need to.

That deffinitely sounds like a possibility, since alot of libs to communicate with all common screen readers under Windows, Mac and Linux are already available and are much more usable via Python than via EEL and/or lua.

Just my oppinion though, it would deffinitely great to have for all script developers.
