### ISSUE TITLE
Suggested shortcut for invoking automation item properties

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#138]
I agree with Gianluka that the most elegant solution for this would be to have shift f2 invoke the right properties dialogue at the right time, however, I wondered if control shift f2 would be a good ke in the mean-time. It makes a kind of mnemonic sense.

**Comment by ScottChesworth** [comment]
Control+Shift+F2 got commandeered by "Xenakios/SWS: Auto-rename selected takes" in the last keymap revision because I forgot about this issue being open.
@Justinmac84, how are you currently accessing the properties dialog for automation items there, via the actions list or do you have something mapped we could replicate? Seems there weren't any takers on making Shift+F2 context sensitive.

**Comment by jcsteh** [comment]
For what it's worth, having an action to open the right dialog depending on focus is certainly possible and not too difficult. It should be a new action, though, not an override of an existing one.

**Comment by ScottChesworth** [comment]
So something like "OSARA: Show media item/take/automation item properties (depending on focus)" that we can pop on Shift+F2? Sounds like a goer to me man.

**Comment by leonardder** [comment]
I'm happy to do this one, as I mainly use item properties pretty frequently.
