### ISSUE TITLE
Keymapping correlation with default keymaps

### ISSUE THREAD

**Issue by dl7fos** [jcsteh/osara#148]
Hello, a general problem which also exists bei the old ReaAccess is if keystrokes will accidently corresponding to the global keystrokes by Reaper. Example: Ctrl+Shift+M usually opens the track manager, however Osara turns on and off metronome. It would be much better to define a global Osara key which corresponds to all extra key commands. At this time it isn't really possible to use the Reaper default keymaps because of corresponding much keys by Osara. However, there are much helpful key commands.

Recommendation: Keep all key comms using by press one global key, like right Windows key, insert or Numlock, which could be pre-defined by the user if he uses a special notebook without some basic keys.

**Comment by jcsteh** [comment]
There are four reasons this can't/shouldn't be done:

1. OSARA uses REAPER actions to define keyboard shortcuts and make them configurable by the user. REAPER doesn't support modifiers like insert or right control (it doesn't differentiate between left and right control), nor does it allow you to change the modifier for an entire set of shortcuts.
2. A lot of the keyboard shortcuts included with OSARA aren't specific to OSARA. They're included because the default set of shortcuts included with REAPER is relatively small and doesn't include a lot of stuff needed by a keyboard only user. REAPER's builtin shortcuts tend to be targeted at users who use the keyboard for quick actions, but still use the mouse quite a lot.
3. Prefixing every single shortcut included with OSARA with another modifier would make usage very cumbersome.
4. Finally, a major change like this at this point in the game would mean existing users re-learning all of the shortcuts. Given that we've already had users depending on OSARA for years, this is an unreasonable change, especially given that the benefits are far from clear cut as per the earlier points.

**Comment by dl7fos** [comment]
Thanks a lot for the explanation. Maybe I should go a little deeper:

My current problem is regarding the track manager to sort the tracks and/or move it to organize them. Maybe there is another key command to do so? That could solve my issue.

**Comment by ScottChesworth** [comment]
It’s already possible to   rename and rearrange tracks on the TCP though (track conttrol panel - Reaper’s main screen). What tasks are you trying to perform that can only be achieved in track manager?

Typed on the move. Please excuse brevity and/or clumsy thumbs.

**Comment by dl7fos** [comment]
At first, I'm at the time not really familiar with Reaper commands especially Osara. What I was trying out is to re-order tracks. I did this with the mouse inside TCM. Is there another way to do so?

**Comment by ScottChesworth** [comment]
There sure is. Select tracks using Shift+Up or Down arrows, then the
standard commands for cut, copy and paste in whichever OS you're
running should work. Note that when you paste tracks, they'll always
insert underneath the track which is selected when you performed the
paste.

**Comment by dl7fos** [comment]
Thank you, this works very fine and is quick and easy. However, as I was searching how moving tracks in Reaper, I found nothing really helpful. I guess that's only because of Osara is installed? Is there any list of keystrokes which are used?

**Comment by iBlindTech** [comment]
Hi 

You can get a full list of Reaper keyboard commands with Shift+F1. Might I also suggest joining the RWP email list. Reapers Without Peepers. This is a good place to get support with Reaper and it’s use with OSARA.   
You can use the below link to find out more: 
http://bluegrasspals.com/mailman/listinfo/rwp <http://bluegrasspals.com/mailman/listinfo/rwp>

Also see the Reaper Accessibility Wiki at:   http://reaper accessibility.com 

Thanks 



On 9 Apr 2018, at 3:44 pm, dl7fos <notifications@github.com> wrote:

Thank you, this works very fine and is quick and easy. However, as I was searching how moving tracks in Reaper, I found nothing really helpful. I guess that's only because of Osara is installed? Is there any list of keystrokes which are used?
