### ISSUE TITLE
Make Play rate announcement a preference in Osara dialog

### ISSUE THREAD

**Issue by pianomagic88** [jcsteh/osara#153]
Jamie, what would be great is if the announcement of play rate, I.E. 0.6 cents, 6 percent, etc, could be made a preference in the Osara dialogue. Sometimes I just want to change the playmate of a piece of music without having to know what I've changed the play rate too. The control key to shut speech up would be just one more key to press when I wouldn't have too, if the speaking of play rate status could be made a preference. Thanks for consideration. After all, the focus should be on the music, not what play rate is changing too.

**Comment by jcsteh** [comment]
Does it make sense to just always silence these actions if audio is playing
(but report them if audio is stopped)? IMO, this serves the spirit of this
request without complicating the user experience.

**Comment by pianomagic88** [comment]
That makes perfect sense to me. If this request would be considered, again, with the way you set up the scenario, that would be ideal.

**Comment by ScottChesworth** [comment]
Interesting idea. If it were purely my vote I'd say no, because I've
come a cropper a few times by accidentally nudging the play rate in
fine increments while audio is playing and not noticed the change
immediately (never headbang on the job, kids, not even when you need
to make a band believe their riffs are good). That said, there are
some proposed keymap changes coming your way soon that should negate
the possibility of this happening again. Lemme ask the Whatsapp folks,
gather a consensus and get back to you.

**Comment by jcsteh** [comment]
I guess we start without the check box, and if there's major resistance, we
can add it. It's always easier to add something than to take it away.

**Comment by ScottChesworth** [comment]
Yep, fair enough. I'm not anticipating any resistance on this one man,
it was just a "would be nice" type thing from everyone who asked about
it.

**Comment by jcsteh** [comment]
Wait. The original comment here suggested OSARA already reports play rate (since it talked about having to shut up speech), but as far as I can see, this was never implemented. So this issue is also about actually providing that feedback, not just silencing it in certain cases.

**Comment by jcsteh** [comment]
Oh, I see. Feedback for play rate is covered in #131. I'll close this one, then, since we'll just cover the desired user experience when implementing it.
