### ISSUE TITLE
making nudge and shrink items on numeric keypad talk

### ISSUE THREAD

**Issue by chrisbelle2015** [jcsteh/osara#16]
would like when editing with the numeric keypad, that Osara gives feedback as to the action and what is happening

**Comment by jcsteh** [comment]
More specifics please. Preferably, please provide exact action names and exactly what you want reported. You can find action names using the Find shortcut button in the Actions Dialog.

**Comment by chrisbelle2015** [comment]
Oh boy, don't have reaccess installed anymore, and don't plan to install 
it most likely.

but I do remember that it did report changes when you grew or shrunk 
edges or nudged items, told you more or less what you had done.

I think reaper still does these more or less default actions on the 
numeric keypad, but it doesn't say anything with Osara when you're doing 
this.
At lest last time I checked.

sorry i can't be more specific right now, just do what you can.
C

**Comment by chrisbelle2015** [comment]
Ok, I'll try to make myself clearer.

You know I have a hell of a time with this step by step kind of thing 
Jamie, I'm a generalizations concepts kind of guy, I know it drives you 
programmer types nuts.
You were very patient with me when we worked on sonar 'grin'.

But here goes.

Combinations of the numpad 3 and 6 key with the control and alt keys 
allow you to grow or shrink edges of items.

All reaper says in the undo menu now is undo move items.

but in the actions list, we still have the same commands for growing and 
shrinking edges of items.
That we used to have in reaccess.

It would tell you if you grew or shrunk an item with the 3 and 6 keys,
in combination with control or alt incase you got mixed up you knew you 
were going the wrong way and could correcxt.

Now it says nothing and you just have to know.

In geneeral, I think most of us who ever used reaccess want the best to 
come back from that plug, I know it can't be exactly the same, I agree 
about maybe not having the fake overlay for volume and all that, but the 
good feedback about what you did, and how many items, and when you split 
it'd tell you, and all that sort of thing, that's the good stuff we want.

Well, thanks a lot you're doing a great job.
and yeh, just like snowy, reaper makes me feel retarded 'big grin'.

**Comment by jcsteh** [comment]
With respect, saying you're "a general concepts kind of guy" is not a valid excuse. You do not have to be a computer programmer or even a technically minded person to provide exact steps and requirements. Even example scenarios are fine.

If you want a command to report something, you clearly know what you'd expect it to report. At least you've now more clearly specified which numpad keys you're talking about. However, what exactly do you want reported? Do you want it to just say "grow items" or "grow items right"? Or do you want it to say "grew items by 10%"? It's not about what ReaAccess did. It's about what you're actually expecting. If you can't define your requirements, I can't be sure I'm implementing what you want. I don't want to go back and forth on this multiple times because we were unclear on what you actually wanted; I simply don't have time for that and I'm sure you don't either.

**Comment by jcsteh** [comment]
Just tested this with ReaAccess. It just reports the action name as it does for many actions. The problem i have with this is that it does this even when the command fails; e.g. if there are no items on the track. That is very misleading and is IMO worse than not reporting anything at all. I'll see if I can detect whether this has actually happened.

**Comment by chrisbelle2015** [comment]
I agree would rather not be lied to.

**Comment by chrisbelle2015** [comment]
yeh, I get it.

I feel more out of my element with reaper, sonar was like the back of my 
hand, and reaper makes even smart folks,
other devs
puzzle over things which should be simple.

I wish the folks who made all the clamor would get on board and
actually run Osara, and
you need more experienced reaper heads than me talking to you about this.

I'll do my best.

**Comment by jcsteh** [comment]
I totally understand; I'm very new to REAPEr as well. That's even more reason you need to be very specific about what you want; as a fairly new user, I can't just guess based on experience. My point is that you wanted me to support certain commands, but you didn't specify exactly what commands; there are quite a few numpad commands, some of which aren't related to what you want, and I'm not going to go through them all trying to guess what you want. Similarly, you wanted the commands to give some feedback, but you didn't specify *what* feedback; even saying "just the command name" or giving an example of what it might say would have been enough. Don't assume that what you want is obvious; when in doubt, be overly specific. That's the best way to ensure someone delivers what you wanted instead of something totally off the mark.

**Comment by chrisbelle2015** [comment]
Gotcha.

Well, for now if we could get realistic reporting of grown and shrunken 
items edges with the conbinations of numpad 4 and 6 using the
control and alt keys that would be great.

These commands are especially useful for cross-fading audio that is 
troublesome, you got a pop and click, like when you do a pitch change or 
take a little bite out of a audio chunk and you want to splice it back 
together.

Reaper does a nice job of doing this with growing and shrinking the 
edges of items in a way that
while it does create some flanging and doubling in extreme cases, does 
get rid of the pops and clicks.

And I always forget, did I just shrink the left edge, or did I just grow 
the right edge, and having immediate feedback on what I just did would help.
when trying to keep straight in my head
what the heck I need to do 'grin'.
