### ISSUE TITLE
Requesting action feedback when navigating to previous and next MIDI tracks and items from within the MIDI Editor and MIDI Event List Editor

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#160]
Action feedback has been requested for the following actions. I can definitely see the UX and productivity benefits if these are possible to implement.

Here are the actions we're using (all in the MIDI Editor and MIDI Event List Editor categories):
Activate next MIDI track (40835)
Activate previous MIDI track (40836)
Custom: Go to next midi item (_75564b5383268f4e8701b2465bb5e198)
Custom: Go to previous midi item (3d82f1008d23dd4c9849c028325d3743)

Also just noticed when filing this request that in the MIDI Event List Editor category, the CTRL+Down and CTRL+Up keystrokes which should be bound to "Activate next MIDI track" and "Activate previous MIDI track" are incorrectly assigned. It's a carry over from the previous key map. Surprised that got missed in testing. Apologies!

**Comment by jcsteh** [comment]
Due to the way we push text to be reported by screen readers, it's not possible to have feedback in the event list. I did get this working with NVDA at one stage, but it completely broke JAWS and apparently I have to support both, so... :(

In future, there might be another mechanism I can use once all screen readers support it, but it would only work on Windows 10.

**Comment by GianlucaApollaro** [comment]
I would say you provide feed back where you can, that is in the piano role, where that is mostly used

**Comment by RDMurray** [comment]
I have implemented this in #222 .

I had to replace the custom actions with Osara actions, because it doesn't seam to be possible to intercept actions that are executed from a custom action in the MIDI editor.
