### ISSUE TITLE
Potential accessibility improvements for the SWS groove tool dialog

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#170]
In the SWS Groove Tool dialog, everything appears to be standard controls that are reachable with the JAWS cursor or object navigation, but it would be a big productivity improvement if this dialog were navigable via a tab order. I'm guessing this is something that would be best implemented via the SWS folk, but we don't - so far as I know - have anyone on that team who knows the nuts and bolts of implementing accessibility yet.

If you get a spare minute to take a poke around that dialog, could you comment with anything that would be helpful to nudge them in the right direction so I can take that over to their GitHub and try to get some change happening over there?

Cheers for any advice.

**Comment by jcsteh** [comment]
I think this is deliberate for all dockable SWS windows (and this is one of those). They explicitly request that REAPER forward all keyboard actions to the main window so that people can still use REAPER commands while they're working with the window. ([Here's the relevant code in SWS](https://github.com/reaper-oss/sws/blob/b3ad441575f075d9232872f7873a6af83bb9de61/sws_wnd.cpp#L588) in case anyone asks what I'm talking about.) REAPER's transient sensitivity adjust window is similar.

Perhaps they might make an exception for tab/shift+tab and arrow keys in this window (and maybe others?)... or perhaps they could provide an option to disable this.

Btw, for SWS issues, I think it makes sense in future to just file an issue in their GitHub and mention me (@jcsteh) if you think you might need pointers from me. There's no need to track these issues for OSARA, since SWS has an open tracker anyway. Thanks.
