### ISSUE TITLE
multiletter navigation in parameters list request

### ISSUE THREAD

**Issue by ececrios907** [jcsteh/osara#182]
Have not been here in a while, but hoping to have the following request implamented.

As you all may know some plugins have hundreds of automatable parameters that are properly labeled, but we do not have multiletter navigation in the parameters list so we have to arrow through all parameters that begin with the same letter.

for example, Ozone from Izotope has a neat labeling method that goes as follows: CB1, CB2, EQb1, VC, VL  that respectively translate as compressor band 1, compressor band 2, equalizer band 1, vintage compressor, vintage limiter etc. there are over 600 parameters exposed so multi letter navigation would assist in quickly jumping to a parameter. Something similar to how we can pull up  the list of links on an html document and we can begin typing quickly to move to a link.

Thank you.

**Comment by jcsteh** [comment]
You can already achieve what you want by using the filter field, which
allows you to restrict to only parameters containing that text; e.g. you
could type CB to only show parameters containing the text CB.

Leaving open because multi-letter navigation in that list would be nice,
but it's low priority because it's not trivial to implement and there's
already a way to achieve this, albeit with a few extra keystrokes.

**Comment by ececrios907** [comment]
Lol. You will have to excuse my stupitity on this one. I overlooked this filter. Makes perfect sense, no need for this request.
Thank you.
