### ISSUE TITLE
Action feedback for control surface actions

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#193]
I'm using reakontrol with a Komplete Kontrol M32. I've observed that some actions that are invoked from the controller are spoken, such as metronome on/off. I assume this happens because ReaKontrol calls the actual actions under the hood, so Osara's action feedback is triggered there.
Would it be possible to give feedback on actions that are invoked for control surface specific functions, such as CSurf_OnPlay and CSurf_OnRecord, etc?

**Comment by leonardder** [comment]
It looks like SWS also creates its own control surface that does all sorts of fancy things. As it is not possible to hook control surface functions as with commands, it might work to create an OSARA specific control surface to speak certain things, such as volume changes. I'm going to check this out.

**Comment by jcsteh** [comment]
Note that there is a very old branch called surfaceVolPan which implements a prototype control surface. I originally wrote it to try to deal with reporting correct volume/pan levels while automating. It turned out not to work in the way I wanted it to and I subsequently discovered there's a better way to do this. However, it might be a good starting point.

Note also that reporting stuff like volume from surfaces may have unintended consequences. For example, I suspect it will  report levels when playing back automation, which is not what we want. Also, you may get double up from the action hooking and the surface, so you'll need to compensate for that. The action hooking is always going to be more reliable in the sense that we know what is a user action and what isn't.  That said, it'd obviously be nice to be able to report surface stuff if we can, as long as we can find a way to make it work without negative side effects.

**Comment by leonardder** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [31 Mar 2019, 00:17 CET](https://github.com/jcsteh/osara/issues/193#issuecomment-478297705 "2019-03-30T23:17:07Z - Replied by Github Reply Comments"):
> ... I subsequently discovered there's a better way to do this. 

Could you elaborate on this?

> I suspect it will report levels when playing back automation, which is not what we want. 

I agree. However, I think it will be pretty hard to distinguish between control surface actions invoked from another surface or by means of automation.

> Also, you may get double up from the action hooking and the surface, so you'll need to compensate for that.

I guess the system that deals with duplicated hooking, i.e. the isHandlingCommand boolean, could help in this.

> That said, it'd obviously be nice to be able to report surface stuff if we can, as long as we can find a way to make it work without negative side effects.

I guess a good starting point might be speaking play state changes from a prototype surface like in surfaceVolPan. I consider action feedback for volume changes of less relevance than record/play/scrubbing/scrubbing.

**Comment by jcsteh** [comment]
> > ... I subsequently discovered there's a better way to do this.
> 
> Could you elaborate on this?

See https://github.com/jcsteh/osara/issues/112#issuecomment-392628354.

> > Also, you may get double up from the action hooking and the surface, so you'll need to compensate for that.
> 
> I guess the system that deals with duplicated hooking, i.e. the isHandlingCommand boolean, could help in this.

I hope so. However, there's a chance that surface callbacks are called after the execution of the action rather than during its execution. Only one way to find out...

**Comment by leonardder** [comment]
I have a proto type branch that reports play state based on the control surface code. Some findings:

1. Sometimes, I notice duplicates to be fired. For example, when pressing play, SetPlayState is called once, but when stopping, SetPlayState is called at least twice. We can easily work around that by caching the last play state.
2. The stop state is now also announced at the end of a project, which is something I do like, others might not. This does not involve user interaction.
3. Apart from the duplicates, I think the control surface behaviour is accurate. If others agree that point 2 is a feature and not a side effect, I would even say that we no longer need to hook the play state actions.
4. note that, to avoid duplicates caused by user actions and control surface implementations, I had to change the several post action hooks for play state changes into action hooks, which allowed me to check isHandlingCommand in the surface code reliably.

**Comment by jcsteh** [comment]
This all sounds reasonable. A couple of things:

>     3. Apart from the duplicates, I think the control surface behaviour is accurate. If others agree that point 2 is a feature and not a side effect, I would even say that we no longer need to hook the play state actions.

Note that there are places in the code where we deliberately pause/play/stop for various reasons; e.g. moveToTransient(). We don't want pause/play/stop being announced in this case.

>     4. note that, to avoid duplicates caused by user actions and control surface implementations, I had to change the several post action hooks for play state changes into action hooks, which allowed me to check isHandlingCommand in the surface code reliably.

I've been thinking we should just use the main action hook for post actions as well. That is, keep the post functions the way they are, but just call them from a different place. That means we can still use isHandlingCommand even for post actions. There are other good reasons to do that too; e.g. post actions aren't currently supported in sections other than the main section. I originally thought post actions would be sufficient for most things, which is why I used them. However, that ship sailed a long time ago. :)

**Comment by leonardder** [comment]
Thanks for elaborating. I think I'll do the post action reformation 
first, and after that has been settled, I can continue on the control 
surface work.

**Comment by jcsteh** [comment]
Initial implementation in #196.
