### ISSUE TITLE
If automation showcase options has been changed, track's name announcement don't work.

### ISSUE THREAD

**Issue by vgjh2005** [jcsteh/osara#213]
Hi:
I just know how to do host automation with reaper. The controled plugin window must be opened when automate it.
so:
1. select preference > plugins> Only allow one FX chain window open at a time
2. select preference > plugins > Open track FX window on track selection change
3. press OK to back to the reaper main window.
4. Press up/down arror keys to browse trackview
5. Track's name announcement is very slow or don't work  at all.
Thanks for your good work.

**Comment by jcsteh** [comment]
Opening the FX chain window can be pretty slow depending on the effects on the track. Since you've configured things to do this on every track selection change, that's going to make track selection very slow. I don't know why it isn't reported sometimes, but I doubt there's anything I can do about this.

That said, you don't need to have the FX window open to get host automation working. You can do one of two things:

1. If you want this just for one instrument (e.g. I do this for Komplete Kontrol), open the FX chain, open the Add FX dialog and select the instrument, but don't press enter. Instead, open the context menu, choose Automation notifications and then choose Process all notifications.
2. If you want it for all instruments, open Preferences and select Plug-ins -> VST. Look for an option called Parameter automation notifications and change it to Process all notifications.

**Comment by vgjh2005** [comment]
Thanks for your good idea!
