### ISSUE TITLE
Spurious speech from NVDA in the TCP of Reaper 6.0

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#233]
Here are the oddities I've noticed when running Reaper 6.0 and NVDA 2019.2.1.

1. NVDA says "repeat off" when Reaper launches.
2. If "Report transport state" is checked in OSARA Preferences, NVDA consistently says "stop" when Reaper first opens, and intermittently says "stop" when Reaper regains focus.
3. NVDA speaks "time signature at edit cursor" when hitting enter after naming a new track. It also speaks volume related info intermittently.

None of these are showstoppers obviously, but if anything can be done to smooth out the UX, that would be marvelous.

**Comment by MatejGolian** [comment]
Probably some sort of permutation of the same problem. I have created a blank project with 2 tracks + I have made the master track visible. Next I have added one item to the first track. After selecting the added item with Ctrl + arrow keys and consecutively arrowing up to the master track, NVDA reports the following:
"master  MASTER20.00dB center"
If I select that item on track 1 again and arrow down to track 2 instead, NVDA reports "2 0 items  MASTER20.00dB center". So, spurious speech indeed.

**Comment by MatejGolian** [comment]
Plus when I try to add a track with Ctrl + T, NVDA speaks random stuff such as "Edit loop point" or "Draw a copy of the selected media item". Hopefully, fixing this will be much easier than what it appears to us uninitiated.

**Comment by jcsteh** [comment]
Urgh. This turned out to be quite tricky to fix. REAPER now moves focus
between two windows in the track view, which is kind of annoying.

**Comment by MatejGolian** [comment]
Over here NVDA still speaks extra stuff when moving away from a track if an item has been previously selected on that track. Again the exact same project as before.
1. this is what I get when focusing the first track with the arrow keys:
"1  1 item" - no problem with this
2. Selecting that item with Ctrl + right:
"1 untitled MIDI item" - still no problem
3. But after moving away to the master track with the up arrow:
>"master  MASTER30.00dB center
>MASTER10.00dB center
>MASTER20.00dB center
>MASTER30.00dB center" - the exact numbers spoken seem to vary
4. Moving away from the master track and focusing the first track:
"1  1 item" - again no problem
5. Selecting that item with Ctrl + right once again:
"1 untitled MIDI item" - OK
6. But focusing the second track with the down arrow:
>"2  0 items  MASTER30.00dB center
>MASTER10.00dB center
>MASTER20.00dB center
>MASTER30.00dB center" - obviously not OK

Also, now when using the "Custom: Insert and name track action" after entering the track name and pressing enter, in v5.99 NVDA announces the message "unknown" and in v6.0 it says "panel". I guess this is somehow connected to the new REAPER window structure.

**Comment by jcsteh** [comment]
> Over here NVDA still speaks extra stuff when moving away from a track if an item has been previously selected on that track.

Should be fixed in ab9f145ff5.

**Comment by MatejGolian** [comment]
@jcsteh, thank you, I can connfirm that the fix is working indeed. Now the only thing that's a bit off compared to the Osara builds before the Reaper v6 adjustments started coming in is what I already mentioned in my previous comment - namely that after pressing enter to confirm the renaming of a track, NVDA now announces "panel" instead of "track view". In case of Reaper v5.99 and the previous build of Osara NVDA spoke the message "unknown". So now it's the same in v5.99 and v6 in this regard. This probably makes perfect sense to you. I don't think that this really is much of an issue, I mean the fact that NVDA now announces "panel" instead of "track view" after a track rename operation, but I wanted to let you know that the user experience is a tad different now. If the previous user experience can't be fully restored (or only at the cost of complicated or hacky code), this is an absolutely negligible price to pay.

**Comment by jcsteh** [comment]
Yeah; I don't think this is worth fixing. Whether this is even a bug is
debatable.
