### ISSUE TITLE
Alt key stops working after inserting a track in Reaper 6.0

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#234]
Jamie has already drawn Cockos's attention to this and they've confirmed it'll be fixed. Figured I'd file it here as well though because it's a bug that's already made a brief appearance before. Perhaps @jcsteh can comment with the details of what's broken so that we can raise it with Cockos should it reoccur.

**Comment by jcsteh** [comment]
[Tweet from Cockos indicating they're fixing this](https://twitter.com/Cockos/status/1202590164905873408)

Technical: Alt key doesn't focus menu bar and alt+f4 doesn't close app when "REAPERTCPDisplay" HWND has focus. Don't really know why exactly, but this new HWND is what changed things.[Tweet from Cockos indicating they're fixing this](https://twitter.com/Cockos/status/1202590164905873408)

Technical: Alt key doesn't focus menu bar and alt+f4 doesn't close app when "REAPERTCPDisplay" HWND has focus. Don't really know why exactly, but this new HWND is what changed things.

**Comment by MatejGolian** [comment]
According to the change log, fixed in v6.0+dev1205. I can confirm that the alt key now opens the menu and closes the window when using alt + f4 - true when using NVDA and JAWS as well, but my copy of JAWS 2019 (no extra scripts) still does not read the TCP. I'm not a JAWS user, but obviously it's worth knowing about. This seems to suggest that there is something else going on here as well.
