### ISSUE TITLE
fx parameters dialog slider home/end keys reversed

### ISSUE THREAD

**Issue by ns-studios** [jcsteh/osara#241]
Hi,

In the fx parameters dialog, the home and end keys on the slider seem to be reversed, i.e., home used to go to the minimal value, and end to the maximum, but now it's the other way around, and it's really confusing because I'm so used to it being the other way around that I always end up doing the wrong one.

**Comment by jcsteh** [comment]
For audio sliders, the convention is for up arrow to increase (up) and down arrow to decrease (down). Similarly, the convention is for home to go to max and end to go to min, since home is normally the key further up on a standard keyboard. This is how it works for the volume sliders in Windows volume control, for example. I don't think this should be reverted.
