### ISSUE TITLE
Making the output of OSARA: Report track/item/time selection (depending on focus) easier to review

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#243]
The current output of this action can be a lot of info to take in all at once when reviewing complex selections. I've taken to copying its output to the clipboard using the "Speech history review and copying" NVDA addon, then pasting into Notepad for closer inspection where necessary. However, the output currently seems to be a string of messages separated by commas. Two ideas sprung to mind that would tighten this workflow up:

1. Could the action send separate messages, so that selection could be reviewed by navigating through the speech history?
Or 2. Would replacing the space that currently follows each comma with a linebreak cause anything bad to happen? My hope is that the output would show up as a handy list when pasted.

Not a priority really, just a UX tweak that I'd make good use of if it's easy to implement.

Action: OSARA: Report track/item/time selection (depending on focus)
ID: _OSARA_REPORTSEL

Thanks in advance,

Scott

**Comment by kyleman** [comment]
Working on adding line brakes in my forked copy. Would "\n" be enough for both platforms or does windows need "\n\r"? Running MacOS here.

**Comment by kyleman** [comment]
or would `std::endl` be a better platform agnostic approach?
@jcsteh

**Comment by jcsteh** [comment]
> The current output of this action can be a lot of info to take in all at once when reviewing complex selections. I've taken to copying its output to the clipboard using the "Speech history review and copying" NVDA addon, then pasting into Notepad for closer inspection where necessary.

As usual, I'm going to be painful and ask you to take a step back from the actual UX here. What's the use case/real world scenario here? Why do you want to examine this info separately? What might you do with it? The reason this matters is that we may be able to come up with a far better UX if we fully understand what we're trying to achieve.

For example, instead of just changing how the info is reported, we could:

1. Have two presses output to a text box in a little dialog, with each track separated onto a new line. That way, you can review the text without having to copy/paste. However, this would (probably?) mean you can't interact with REAPER while you're reviewing it. Does that matter? Depends on your use case.
2. Have two presses copy to clipboard, one track per line. I'm not a massive fan of that, since it forces you to interact externally, but maybe that's okay. That said, option 1 gives you the best of both worlds: you can choose to copy if you wish.

Addressing your UX questions:

>     1. Could the action send separate messages, so that selection could be reviewed by navigating through the speech history?

Not possible unfortunately.

>        Or 2. Would replacing the space that currently follows each comma with a linebreak cause anything bad to happen?

It's not great for braille users, since they are then forced to read all the tracks on separate lines whether they want to or not.

Addressing the technical question:

> or would `std::endl` be a better platform agnostic approach?

Yes, but I don't think this UX is a good idea because of braille; see above.

**Comment by kyleman** [comment]
Just push pr #245

**Comment by kyleman** [comment]
@ScottChesworth Said the reason for copying it or viewing it in an external spot is to verify the correct things got selected with a complex selection. You aren't going to be interacting with reaper at this point anyway.

I like option 1 personally. Makes the review seamless and eliminates the need for other add-ons or scripts to copy last spoken text to the clipboard.

UX: 2
pre change: braille display users have to pan over what could be a several dozen char long line. 
post change: braille display users can scroll between lines that might actually have a chance of fitting on their display.

**Comment by jcsteh** [comment]
> UX: 2
> pre change: braille display users have to pan over what could be a several dozen char long line.
> post change: braille display users can scroll between lines that might actually have a chance of fitting on their display.

That's not as clear cut as it might seem. Pre change, the content wraps and users have to pan, but post change, there's a big chance that a whole lot of display space gets wasted (particularly with 40+ cell displays), making reading a lot less efficient (more button presses, more hand movement due to lines being shorter, etc.).

**Comment by ScottChesworth** [comment]
I hadn't considered braille users, good catch @jcsteh .

Option 1 seems to be the best of both worlds. That'd maintain the current display space usage, plus enable closer examination of complex selections without the need for addons, so Mac folk would also benefit.

Re not being able to interact with Reaper whilst in that new dialog you're proposing, my thinking is that if a user spots an error and needs to adjust their selection, it'd only take a second to rebuild the dialog after making the necessary changes if they want to re-verify what's selected. Doesn't seem like a big issue to me.

**Comment by tbdalgaard** [comment]
@jcsteh Nice that you keep braille users in mind! The idea about a dialog box where each track is on a seperate line is a good idea. Especially for me as a heavy user of braille. It will get quite easy to get an overview if multiple tracks are selected, so I would personally prefer this method myself.

However, note that text in edit fields may wrap unexpectedly, perhaps you can force no wrap inside this dialogue box?

**Comment by jcsteh** [comment]
@ScottChesworth, is there any point in doing this for report muted/soloed/armed/etc. tracks? I didn't bother to read this issue properly (because why would I do that?), so I ended up implementing this for muted/soloed/etc., then realised that wasn't what this was about. If it's not useful, I'll just throw it away; no point in pointless clutter. If it's useful, it's trivial to merge it.

**Comment by ScottChesworth** [comment]
Can see those being just as useful in projects with high track counts yeah. I reckon merge it.
