### ISSUE TITLE
Bypassing effects in the FX dialog.

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#267]
Using NVDA as screen reader, in the FX dialog does not report whether an effect is disabled.
For example, if I want to try different compressors or equalizers, I create an effects chain and switch the bypass for each effect.
It would be helpful if the screen reader could recognize the bypassed effects when I scroll through the list with the arrows.

Thoughts?

**Comment by ScottChesworth** [comment]
Jim has had this functionality implemented for a while in his JAWS scripts. Would be great if we could match the functionality for NVDA users. I seem to remember there was some discussion previously, but can't find the thread. What's the chances, @jcsteh ?

**Comment by jcsteh** [comment]
It should be possible to get this info using TrackFX_GetChainVisible and then either TrackFX_GetEnabled (assuming enabled and bypass are the same thing) or TrackFX_GetParam with the bypass parameter (though that would be less reliable).

The real problem is exposing the info in an accessible way. Because this is a list view and those get handled specially by screen readers, I can't override the content using accessibility APIs. I haven't managed to come up with any clever way to deal with this that doesn't involve screen reader scripting.

**Comment by ScottChesworth** [comment]
I suspect you'll balk at this suggestion, but would playing some sort of beep when a plugin is bypassed be any easier to implement?

**Comment by jcsteh** [comment]
It'd be easier to implement, yes, but I'm not a fan. :)

**Comment by jcsteh** [comment]
In case people don't see or read my commit message, note that you have to tab to the Notes text box in the FX Chain dialog (one tab from the list) to hear the active/bypassed state. Pressing control+b while focused on that field will also read the change. This is far from ideal and is a big ugly hack, but it's the best I could come up with that doesn't involve screen reader specific scripting. It also only works on Windows, since I don't know how I can watch for focus changes in REAPER on Mac.

**Comment by Lo-lo78** [comment]
Hi James and everyone,

in your opinion if we created a feedback, taking from the bypass 
checkbox, to understand the one after the UI button, the screen reader 
could give feedback?

This way we don't move the system cursor.

A very convenient thing would be that when we move through the fx chain 
list, the plugins in bypass are announced by the screen reader and the 
active plugins read them without saying the status.

For example:

bypassed: VST: ReaComp (Cockos)

VST: ReaEQ (Cockos).

Perhaps taking from the checkbox screen readers could work automatically.

Regards!

**Comment by jcsteh** [comment]
As I explained in my comment above, it's not possible to override the content in list view items because of the way screen readers interact with them. So, this simply can't be done without screen reader specific scripting. This is the best I can do in OSARA.
