### ISSUE TITLE
Can OSARA provide functionality to select and move to the topmost and bottom-most tracks (or incorporate my custom actions)?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#269]
Hi,

I've had a request for this open in the Cockos forum forever, but it's not getting any traction. Can OSARA provide actions to do this?

Alternatively, perhaps incorporate the custom actions linked below, which have been thoroughly put through their paces and verified to work reliably?
https://www.dropbox.com/s/849tpczatzg8c5b/Select%20and%20move%20to%20first%20or%20last%20track%20%28Scott%29.ReaperKeyMap?dl=1

Control+Alt+Home and Control+Alt+End would be good spots on the key map.

Thanks in advance if there's anything you've got time to do.

**Comment by RDMurray** [comment]
I vote for including the custom actions in the keymap.

**Comment by ScottChesworth** [comment]
As an utterly transparent (and quite possibly inadequate) attempt to sweeten the deal, here's the custom actions already assigned to Control+Alt+Home and Control+Alt+end.
If there's anything else I can do to make this easy @jcsteh , just shout.
https://www.dropbox.com/s/lkbvp7vhgf0padj/Select%20and%20move%20to%20first%20or%20last%20track%20%28already%20assigned%20to%20Control%2BAlt%2BHome%20and%20Control%2BAlt%2BEnd%29.ReaperKeyMap?dl=1

**Comment by jcsteh** [comment]
Custom actions are part of the keymap, which I've mostly left up to other
folks. If there's no disadvantage to using the custom actions (as opposed
to building it into OSARA's code), I can't see any problems with that. I
guess the only disadvantage would be if it depends on SWS, since the rest
of OSARA's core functionality doesn't depend on SWS, but I don't think
anyone except me really cares, so I wouldn't block based on that. That
would need to be submitted in a keymap update, though.

Note that first/last track is harder than it sounds if you want to take
into account hidden tracks, closed folders, etc. like up/down arrow do.
However, you may have already dealt with all of that (somehow) in your
custom actions.

**Comment by ScottChesworth** [comment]
Moving to the last track does depend on SWS, yeah. I used:
Track: Select all tracks
Xenakios/SWS: Select last of selected tracks
OSARA: report track/item/time selection (depending on focus)
No idea how it copes with hidden tracks tbh. I'll check tomorrow.

**Comment by jcsteh** [comment]
Looks like this was done using custom actions in the latest key map merged in #312. Closing.
