### ISSUE TITLE
Help request for SWS extension accessibility issue

### ISSUE THREAD

**Issue by nofishonfriday** [jcsteh/osara#299]
Hi,

I'm a contributer/developer for the SWS extension.
It's been pointed out that there's an accessibility issue with one of the SWS' features, namely the Region playlist: https://github.com/reaper-oss/sws/issues/1404

As I admittedly don't have any experience at all with Reaper's accessibility features, I'm looking for info where to start solving this issue.
Would this have to be implemented/fixed on SWS side, or would this be a topic involving  OSARA?
What I found interesting is that the user says _VoiceOver works fine with the rest of REAPER and SWS_, so apparently there must already be a mechanism present handling this for (most) part of the SWS features?

Any help greatly appreciated. Thank you.

**Comment by ScottChesworth** [comment]
Hey, pleasure to see you posting here man. FYI I'm Scottsdale over on the Cockos forum, we've interacted there a bit.

The region/playlist manager doesn't seem to be any more or less accessible than any other SWS dialog at this point, I'm pretty sure the person who drew it to your attention is also the same person who's been posting news that he's figured out how to interact with it across my accessibility-focused groups today. :)

That said, it is one of many SWS dialogues that could really benefit from you implementing a tab order. The tab order is a longstanding convention on both OS's that all keyboard users will be well accustomed to. Without a tab order, we can only interact with the GUI by navigating the object hierarchy, which works fine for power users, but has a hella steep learning curve for newbies.

TBH, I'm not best placed to advise you on actual implementation, @jcsteh is the guy for that. What I can suggest is spending a few minutes comparing the keyboard interaction that's currently possible in a couple of SWS dialogues. A good example would be "Xenakios/SWS: Command parameters". Notice how in that window, you're able to cycle forward through controls by hitting Tab, cycle backward through controls by hitting Shift+Tab, and click buttons with Space? In an ideal world, that would be mirrored across all SWS dialogues. Compare it to the region/playlist manager, and you'll come unstuck pretty quick attempting to use those standard keyboard conventions.

Hope that helps a bit.

**Comment by soundwarrior20** [comment]
Hi I think I am the user your  referencing. I now no specifics of what I think  needs to be done, please see this Reaper forum thread for more info: 
https://forum.cockos.com/showthread.php?t=241888 
I hope this helps please let me know if you need any more info. And a big thank you for wanting to attempt to fix this. 
  

On 3 Sep 2020, at 20:22, nofish <notifications@github.com> wrote:

Hi,

I'm a contributer/developer for the SWS extension.
It's been pointed out that there's an accessibility issue with one of the SWS' features, namely the Region playlist: reaper-oss/sws#1404

As I admittedly don't have any experience at all with Reaper's accessibility features, I'm looking for info where to start solving this issue.
Would this have to be implemented/fixed on SWS side, or would this be a topic involving OSARA?
What I found interesting is that the user says VoiceOver works fine with the rest of REAPER and SWS, so apparently there must already be a mechanism present handling this for (most) part of the SWS features?

Any help greatly appreciated. Thank you.

**Comment by soundwarrior20** [comment]
Hi Scott thanks for this, further to my last reply. If you could manage to add an action for new playlist and add all regions that would be great. Thank you for this. 

On 3 Sep 2020, at 21:01, ScottChesworth <notifications@github.com> wrote:

Hey, pleasure to see you posting here man. FYI I'm Scottsdale over on the Cockos forum, we've interacted there a bit.

The region/playlist manager doesn't seem to be any more or less accessible than any other SWS dialog at this point, I'm pretty sure the person who drew it to your attention is also the same person who's been posting news that he's figured out how to interact with it across my accessibility-focused groups today. :)

That said, it is one of many SWS dialogues that could really benefit from you implementing a tab order. The tab order is a longstanding convention on both OS's that all keyboard users will be well accustomed to. Without a tab order, we can only interact with the GUI by navigating the object hierarchy, which works fine for power users, but has a hella steep learning curve for newbies.

TBH, I'm not best placed to advise you on actual implementation, @jcsteh is the guy for that. What I can suggest is spending a few minutes comparing the keyboard interaction that's currently possible in a couple of SWS dialogues. A good example would be "Xenakios/SWS: Command parameters". Notice how in that window, you're able to cycle forward through controls by hitting Tab, cycle backward through controls by hitting Shift+Tab, and click buttons with Space? In an ideal world, that would be mirrored across all SWS dialogues. Compare it to the region/playlist manager, and you'll come unstuck pretty quick attempting to use those standard keyboard conventions.

Hope that helps a bit.

**Comment by soundwarrior20** [comment]
Hi I think I am the user your  referencing. I now no specifics of what I think  needs to be done, please see this Reaper forum thread for more info: 
https://forum.cockos.com/showthread.php?t=241888 
I hope this helps please let me know if you need any more info. And a big thank you for wanting to attempt to fix this. 
  

On 3 Sep 2020, at 20:22, nofish <notifications@github.com> wrote:

Hi,

I'm a contributer/developer for the SWS extension.
It's been pointed out that there's an accessibility issue with one of the SWS' features, namely the Region playlist: reaper-oss/sws#1404

As I admittedly don't have any experience at all with Reaper's accessibility features, I'm looking for info where to start solving this issue.
Would this have to be implemented/fixed on SWS side, or would this be a topic involving OSARA?
What I found interesting is that the user says VoiceOver works fine with the rest of REAPER and SWS, so apparently there must already be a mechanism present handling this for (most) part of the SWS features?

Any help greatly appreciated. Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


On 3 Sep 2020, at 20:22, nofish <notifications@github.com> wrote:

Hi,

I'm a contributer/developer for the SWS extension.
It's been pointed out that there's an accessibility issue with one of the SWS' features, namely the Region playlist: reaper-oss/sws#1404

As I admittedly don't have any experience at all with Reaper's accessibility features, I'm looking for info where to start solving this issue.
Would this have to be implemented/fixed on SWS side, or would this be a topic involving OSARA?
What I found interesting is that the user says VoiceOver works fine with the rest of REAPER and SWS, so apparently there must already be a mechanism present handling this for (most) part of the SWS features?

Any help greatly appreciated. Thank you.

**Comment by ScottChesworth** [comment]
Always happy to explain this stuff from a user's perspective @nofishonfriday. Most days, I can get feedback jotted down pretty fast too, so feel free to hit us with links to test builds etc as you're working on this.

**Comment by soundwarrior20** [comment]
@nofishonfriday hi ide love to bater test your work if you could please help make this accessible that would be great! as I explained in the forum post I feel the actions I mentioned would really help. thanks again for all your help with this :)

**Comment by jcsteh** [comment]
It sounds like this is a dialog that needs some fixes on the SWS side and that there's nothing this needs in OSARA. I'd suggest any further discussion be taken to reaper-oss/sws#1404. That said, feel free to mention me on that issue if you require technical help others can't provide. Thanks!

FYI, any interactive control in a dialog should probably be in the tab order and should thus have the WS_TABSTOP style set. If you have property pages in the dialog, set WS_EX_CONTROLPARENT on the dialog to ensure you can tab into controls in the property pages.

**Comment by soundwarrior20** [comment]
hi @nofishonfriday sorry for the late reply, I'm just writing to confirm that your extension making the region playlist manager  accessible does work. Please would it be possible for you to implement the other changes you spoke about a while ago? Thanks very much

**Comment by nofishonfriday** [comment]
@soundwarrior20 
Replied here: https://github.com/reaper-oss/sws/issues/1404#issuecomment-730029114

(I suggest continuing the conversation there in the future, as this is a SWS related topic, not an OSARA one. :))
