### ISSUE TITLE
Requesting feedback for actions that change item pitch and rate

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#307]
As a sound designer, I use these actions very frequently so it'd be really useful to have feedback for them, also because changing the project playrate provides speech so it'd be better UX consistency. Not all of these actions currently have keymap assignments but I'm including them here as well for consistency:

- Shift+1 Item properties: Decrease item rate by ~0.6% (10 cents); Command ID: 40520
- Shift+2 Item properties: Increase item rate by ~0.6% (10 cents); Command ID: 40519
- Shift+3 Item properties: Decrease item rate by ~0.6% (10 cents), clear 'preserve pitch'; Command ID: 40800
- Shift+4 Item properties: Increase item rate by ~0.6% (10 cents), clear 'preserve pitch'; Command ID: 40799
- Item properties: Decrease item rate by ~6% (one semitone); Command ID: 40518
- Item properties: Increase item rate by ~6% (one semitone); Command ID: 40517
- Shift+5 Item properties: Decrease item rate by ~6% (one semitone), clear 'preserve pitch'; Command ID: 40798
- Shift+6 Item properties: Increase item rate by ~6% (one semitone), clear 'preserve pitch'; Command ID: 40797
- Shift+7 Item properties: Pitch item down one cent; Command ID: 40207
- Shift+8 Item properties: Pitch item up one cent; Command ID: 40206
- Shift+9 Item properties: Pitch item down one semitone; Command ID: 40205
- Shift+0 Item properties: Pitch item up one semitone; Command ID: 40204
- Item properties: Pitch item down one octave; Command ID: 40516
- Item properties: Pitch item up one octave; Command ID: 40515
- Ctrl+Backspace Item properties: Reset item pitch; Command ID: 40653
- Alt+Backspace Item properties: Set item rate to 1.0; Command ID: 40652

The best feedback for these would probably be announcing either the new item rate or pitch depending on what the action is modifying, or just saying "x items rate/pitch increased/decreased) if multiple are selected, just like actions on multiple midi notes in the editor are currently handled.

**Comment by ScottChesworth** [comment]
Note for @jcsteh : I've assigned medium priority because it's been a pretty popular request from users over the years. Would also squash the most valid criticism that was levied on a certain podcast recently. Can't say I see a huge need for it firsthand because I always playback to hear the resultant audio in my workflows, but hey, I guess everyone's different.

**Comment by RDMurray** [comment]
What would be the best feedback for pitch?  The Raw number as in the properties dialog, semitones or cents?

**Comment by ScottChesworth** [comment]
Semitones and cents would be the most intuitive thing to hear.

**Comment by RDMurray** [comment]
What about the rate?  I can see that in some cases semitones and cents would be useful, but other times the number from item properties would make more sense, especially when preserve pitch is checked.

We also have the problem again of what to report for multiple items.  We could go with the same approach as midi notes as @pitermach  suggested above, or the approach taken by the item edge movement commands which is to report information on the focused item.

**Comment by pitermach** [comment]
So my first thought was also that pitch would be generally more useful, but rate could have its uses as well. Looks like the choice is already made for us though, because if you use the actions that adjust the rate and turn off preserve pitch, the item pitch doesn't change in the properties so there'd be no point reporting it.

So, with that in mind, I think for the actions that change the rate and clear preserve pitch, the rate should be reported, while the actions that "pitch" items up/down would report the pitch.

**Comment by RDMurray** [comment]
I think it it best to match the UI as closely as possible, So that would mean reporting rate for all actions that change rate, even when they actually cause a change in pitch.

I think the current actions on the keymap are a bit confusing and incomplete actually.  You can only change rate by 6% if you want the preserve pitch checkbox to be cleared.  There is then no way to turn on preserve pitch again without opening item properties.  I propose getting rid of the "clear preserve pitch" actions, and adding "Item properties: Toggle take preserve pitch".

**Comment by pitermach** [comment]
Right, makes sense, report the rate for all actions that adjust it, and report the pitch for those that don't effect the rate at all (the actions mapped to Shift+7 through Shift+0). I also like the idea of giving a key to the preserve pitch toggle for individual items which is something I had to jump in and out of item properties to do.

As to your other questions with multiple selections, I didn't think of reporting the focused item but in a way that might give slightly more useful info than just hearing that the rate/pitch was increased or decreased.

**Comment by RDMurray** [comment]
@pitermach  Can you test the build in #674  and let me know if you are happy with the feedback?  

You will notice that pitching an item up and then back down to zero will result in a very small number due to floating point arithmetic.  The only way to make it exactly 0 is to use the reset command.  I know that reporting the number like this isn't the best UX, but if we round to 0 it hides the problem.  This has come up on RWP in the past.  There should probably be some way of indicating that the pitch isn't actually exactly 0 in this case.  There is the same problem for rate, but it is impossible to tell from the feedback.

What do you think?  Should Cockos be fixing this, since it is also impossible to tell from the item properties dialog?
