### ISSUE TITLE
Slight UX glitch in Peak Watcher: contextual hint related to channels is reported when Shift+Tabbing to the DB edit field

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#308]
1. Open a project, focus a track and hit Control+Shift+W for Peak watcher.
2. Tab through the controls until you reach the first edit field. Notice how when Tabbing forward, NVDA reports "When level reaches (dB):  edit  Alt+l". This is good.
3. Now Tab past the edit field, and Shift+Tab back to it. This time, NVDA will report "Notify automatically for channels:  grouping" before it reports the expected contextual hint in step 2. That's the bug.

To me this felt similar to whatever was previously going on with the non-standard tooltips in the Device category of Preferences, so I've tried slowing down the rate of Shift+Tabbing as previously suggested. IN this case though, speed doesn't seem to make a difference.

Thanks in advance for any tightening up that can be done.

**Comment by MarcoZehe** [comment]
I believe focus shifts between two distinct groups here when you tab and then shift-tab. Whereas previously, when just tabbing forward, you entered that same group earlier. So NVDA behaves correctly in that it reports the entry into a new groupbox upon focus change.

**Comment by jcsteh** [comment]
Marco is correct. All of those controls (the check boxes and the edit field) are part of the "Notify automatically for channels" group. They're grouped because they're all related to automatic notification for channels. You could imagine reading it as a full sentence:

"Notify automatically for channels (1 and 2) When level reaches (-6dB)"

NVDA reads a group whenever you enter that group, regardless of which way you enter it (from the start or end).
