### ISSUE TITLE
parameter name in the parameter dialogue not always spoken

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#32]
Hi,
I noticed that when we have two parameters with the same name one next to the other, only the first one gets announced when we arrow. It happens with readelay and the parameter called "1 length".
Thanks and keep up the good work

**Comment by jcsteh** [comment]
The reason is that the parameter name doesn't change, so screen readers 
think there has been no change. I notice ReaAccess prefixes the name 
with a number, but I'm not a big fan of this, as it means you have to 
hear the number before every parameter name. What I'll probably do is 
append a number after names that are the same.

**Comment by ScottChesworth** [comment]
Jamie, this seems like a good time to raise a request I've been mulling over. I find parameters being numbered helpful here, because when you're working with plugs that have a lot of parameters, they can help to build up a subconscious grasp and contribute to faster navigation through parameters. Good examples of where this comes in handy are multiband plugins such as ReaEq, ReaXcomp, or other third party drum soft-synths that tend to have a fixed number of parameters per drum or mic. That subconscious grasp means that for plugins I use regularly, I'm able to whiz through parameters knowing that it's 7 arrows from whatever I tweaked last to the thing I want to tweak next or whatever without listening to the screen reader. It's one of those things that I didn't realise I was using until it wasn't there, and having just picked up a few new plugs, I'm finding myself slower on the uptake without it. I agree that the number coming first sucks though. Could numbers be appended to each parameter? That way, you've squashed a bug and we've got the improved productivity going forward.

**Comment by jcsteh** [comment]
Sure, I can append numbers to all parameters. I definitely don't want 
them at the start, though.

**Comment by ScottChesworth** [comment]
I'm not sure anybody did really. It's particularly infuriating that each number currently has a colon after it. If I ever get a chance to mix for Ivan, I'll bill him separately for those extra pauses in speech feedback ;)

**Comment by jcsteh** [comment]
While i agree the pauses make things slightly less efficient (particularly at the start), IMO, there does need to be something that separates the number from the parameter if it's at the end. I know the number will always be the last thing, but having no separation makes it seem like it's part of the actual parameter name.
