### ISSUE TITLE
Marker announcement:

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#329]
Excuse me if I write so many requests, but I have wanted to do it for several months but did not know how:
thank you in advance:
I wanted to propose a combination of osara that announces the markers without moving on them.
If I have verse1, chorus, verse 2 in a song, I wish I could know which of the two verses I am in while reaper is playing.
I'd also like to have an option in osara's preferences to automatically announce markers in play when reaper passes over them.
Sorry again for my prolixity but I just wanted to explain.
Thanks, reaper it changed my life.

**Comment by ScottChesworth** [comment]
You can already examine all existing markers in a project without losing your current position using the Region/Marker Manager window, accessible via the View menu, or Control+Alt+Shift+R.

I'd +1 the second suggestion, optional reporting of passing a project marker could be super useful.

**Comment by jcsteh** [comment]
I'm experimenting with this. I've got it reporting markers and regions during playback. However, was the intention also to report them as you move the edit cursor while not playing? That raises some tricky UX questions (and some technical challenges too):

1. The intuitive thing is to say "report a marker as the cursor moves to it". However, what if the cursor moves over it but doesn't touch it? For example, say you have 4 bars, you have a marker at bar 2 and your edit cursor is at bar 1. You hit control+end, jumping to bar 4. If we report markers you move over, we'll say "marker 1" when you hit control+end. Is that desirable?
2. Should markers be reported in this way only for specific time movement commands or also for moving to items, etc.?
3. Technically, this is tricky because this marker reporting is handled by a completely different section of the code. I'm worried we'll accidentally end up overriding other messages reported by OSARA. We'll have to do some heavy testing on that.

**Comment by ScottChesworth** [comment]
Given that those are indeed tricky UX questions and that I've really only seen passing markers during playback being requested on the semi-regular, I'd say roll it out as you've got it going during playback now, and we can revisit this in due course if the masses want more.

**Comment by jcsteh** [comment]
To be clear, it's currently reporting outside of playback as well; I'm just
less certain about whether that's a good idea. I can disable that, but
re-enabling it later if people want it is going to be a bit painful because
it will require changing the name of the configuration option, etc. "Report
markers during playback" is quite different to "Report markers when the
cursor passes over them".

**Comment by ranetto** [comment]
Hi James, I'd say so but it's my way of thinking:
Should the markers be announced when you are in play and exactly when reaper passes over them or is in an area within it, say a joke to round?
When you move manually, I would say only with page up and page down it could behave the same way, so I'm at bar 4 and I have a marker at bar 3.1, when moving with "pageupp" I go towards three he announces it to me.
I would leave out, for the problems you described, the movement with the arrows as very fractional and therefore there would be too many investigations to do.
This would allow you to:
know when you enter a chorus while you are playing audio, know when you move through the song with "pageupp pagedown" which section of the song you are in, know which section you are going to when playing, etc.
I would say it would be more than enough.
What do you think james?
