### ISSUE TITLE
Return to the position of the last stretch marker that was moved

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#330]
Hello, I would like to propose an osara action to return, by selecting it, to the last stretch marker that we moved with osara.
It would be useful to be able to reply quickly without getting confused with other nearby markers.
Thanks in advance.

**Comment by ScottChesworth** [comment]
Why does OSARA need to keep track of that for you? There's a certain level of detail-based observation that's required to use any DAW nowadays. To me, it seems like it's the user's responsibility to maintain awareness of what they're moving and where they're moving it to.

**Comment by jcsteh** [comment]
You could also drop a temporary project marker to get around this. You could even create a custom action which moves stretch marker and drops a project marker at the same time.

I'm going to close this because there are already ways to deal with this and because this kind of narrow use case specific action is a really slippery slope. We could end up with an action to return to the last track moved, last item moved, last envelope point moved, etc.
