### ISSUE TITLE
Announce the value of the sensitivity and threshold of the transients

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#340]
Hi James and everyone!
I am exploring the transients and I feel the need to have some feedback from OSARA to know the percentage of sensitivity or the threshold of the transients.
When I do:

Transient detection sensitivity: Decrease
Transient detection sensitivity: Increase

Transient detection threshold: Decrease
Transient detection threshold: Increase

I don't know the actual value and that's why I can't understand the right setting; I have to go instinct!

When I go into the dialog box:

Transient detection sensitivity / threshold: Adjust ...

You can only adjust the first progress slider, the sensitivity one, when I go to adjust the second progress slider, the threshold one, I can't even use the NVDA object navigator.

Is it possible to have OSARA announce the values ​​when we do the shortcuts?
Thanks a lot!

**Comment by ranetto** [comment]
I think this would be very useful, also to be used in dynamic cropping of items.
I can only give a suggestion, when you have focused the second slider of the adjustment window, try to adjust its values with the controll and the arrows.

**Comment by ranetto** [comment]
Hi James and everyone, sorry for my unfamiliarity with "Gtub", but I didn't understand if this thing cannot be solved due to a lack of bees, or if it is being created: it would be very important: thank you James indeed!

**Comment by jcsteh** [comment]
@scottchesworth, I think I've found a way to force the tab and arrow keys in the transient detection adjust dialog to be handled by the dialog instead of the main section. The question is whether that's a good idea or not.

The reason that REAPER doesn't do this by default is because people generally want to be able to play with stuff while adjusting the transients. Tab is especially problematic because tab is move to transient and we're adjusting transients! I'd argue that for screen reader users, the inability to tab to transient here is outweighed by the need to be able to tab through the damned dialog. However, I'd like your opinion on this before I go charging ahead with it, especially as it's a bit tricky to get right.

There are a few paths forward here:

1. Implement the change I mentioned above, which would mean you can tab through all the fields in that dialog and use the arrow keys, etc. One nice part about that is you can also use the text boxes to type numbers.
2. Implement feedback for the increase/decrease commands.
3. Both of the above.

**Comment by jcsteh** [comment]
By the way, @ranetto, please keep in mind that I work on OSARA in my very limited spare time and am not compensated for it in any way these days. If something can't be done or is being done, I'll generally comment on the issue explaining that. If I don't comment, it probably means I haven't had time or inclination to look into it. Thanks for your understanding.

**Comment by ScottChesworth** [comment]
> @ScottChesworth, I think I've found a way to force the tab and arrow keys in the transient detection adjust dialog to be handled by the dialog instead of the main section. The question is whether that's a good idea or not.
> 
My answer to that question is "oh lordy lordy, yes!" :)
If I've understood you right, then the third proposal seems like the biggest win for the most amount of users. If both approaches can be implemented, then the dialog becomes way easier to use for people who want to configure in there, but folks who'd rather stay in the TCP, tune the sliders via actions and test their current settings by tabbing to transient can still do what they'd usually do with added action feedback.
Out of interest, is this a hack that could also be applied to other SWS dialogs as time permits? Asking because I haven't had much luck getting tab orders implemented going direct to their contributors yet.

**Comment by ranetto** [comment]
Hi James, I'm sorry but mine was absolutely not meant to be a rude claim or request: I know that you work in your free time and rightly without reward and therefore when you feel like it, I developing for myself I know how much sacrifice and how much will it takes for everything this, I simply asked you about this as I didn't understand how the matter ended. I really wish you could also make a profit from what you do and therefore who knows one day to be a reason for you as well as passion and help for others.
So for what you do I am always thanking you, people like me can do their job thanks to your free time and what you can do for us.
Often my constant passion leads me to always ask you for information on what is happening and to make requests, but I am not one of those blind people who only pretend, if I could I would finance you and I would also look for other loans, but since it seems to me that not you can do it, what you give us must be enough
it is only the passion that leads me to write to you so often and I often feel embarrassed to do so but I hope for your understanding.
As for this fact of transients, surely it would be very nice to implement what you have described, but I believe that if it were simpler or faster even the mere fact of implementing the listening of the values ​​through the two actions outside the window to adjust the two values of sensitivity and threshold could be enough at this moment and it would be of great help to adjust the transients and therefore with the tab know where the sound begins in an "item", and to use the "dynamic split".
I'm also sorry for my very bad English, I am often forced to use a translator to make myself understood by you and I hope this does not generate misunderstandings.
Thanks James:
   Stephen

**Comment by jcsteh** [comment]
> If I've understood you right, then the third proposal seems like the biggest win for the most amount of users.

You don't ask for much, do you? Would you like fries with that too? 😉

> Out of interest, is this a hack that could also be applied to other SWS dialogs as time permits?

Broken tabbing in SWS dialogs is a different issue. In the transient case, the dialog is actually tabbable and fully accessible, but REAPER very deliberately overrides the keyboard and passes stuff to the main section. In the SWS case, the dialogs aren't doing what they're supposed to do in the first place. I don't think it's hard to fix; someone just needs to do it.

**Comment by jcsteh** [comment]
All good, @ranetto. Just wanted to make sure the situation was clear.

**Comment by ScottChesworth** [comment]
> Broken tabbing in SWS dialogs is a different issue. In the transient case, the dialog is actually tabbable and fully accessible, but REAPER very deliberately overrides the keyboard and passes stuff to the main section. In the SWS case, the dialogs aren't doing what they're supposed to do in the first place.
Gotcha, thanks for clarifying. I'll keep chasing at the source then.
> Would you like fries with that too? 😉
> 
Kind of you to offer, but no fries required.
A mood board charting psychological state over a 365 day period so I can verify that the cow was comfortable becoming my burger will be quite enough, thanks.

**Comment by jcsteh** [comment]
I've landed the fix for the dialog. I'll deal with the actions another day.

**Comment by ScottChesworth** [comment]
Working like magic here. Thanks!

**Comment by jcsteh** [comment]
Implementation note for actions: I think these values can be retrieved with get_config_var using names "transientsensitivity" and "transientthreshold".

**Comment by ranetto** [comment]
I think it's gorgeous James:
can't wait as a kid!
