### ISSUE TITLE
Latest build not functioning for some mac users

### ISSUE THREAD

**Issue by KeithRempel** [jcsteh/osara#349]
When installing the latest version of osara (osara_2020.1pre-251,ef18c25e) no osara actions appear to be imported.

no speech feedback from osara
none of the osara actions show up in the actions dialogue. Specifically, none of the actions with osara in the name. 

I do have the custom actions such as “Cmd+Opt+Home Custom: Select and move to first track” But no feedback when pressing up and down arrow. F12 does not invoke shortcut help.

Have tried this on both a portable and standard installation.

I am able to use an older test build with the new key map without issue.
osara_2020.1pre-63,b630b6ef

I am running OS 10.14.5 on a late 2014 mac mini.
Have tried with reaper 6.14 and 6.12

Another RWP user experiencing the same issue is running OS 10.13 on a 2011 mac book pro.

Scott Chesworth did not have this issue on OS Catalina.

Thinking OS most likely has something to do with why this works for some and not others.

In case it is useful, here is a portable reaper with an unsuccessful install of OSARA.
https://www.dropbox.com/s/g9s9b2666wqw0j6/Broken%20portable%20reaper.zip?dl=0

Thank you to anyone able to solve this problem. Let me know if I can provide any more information.

**Comment by jcsteh** [comment]
Is your REAPER 32 bit or 64 bit? OSARA dropped support for 32 bit a few weeks ago, since new versions of Mac OS can't run or even build for 32 bit. We did ask users a few times whether this was going to be a problem, but didn't get any responses, so presumed this would be fine.

**Comment by KeithRempel** [comment]
Hi,
I am using 64 bit. At least, that’s what I downloaded and application title is “reaper 64”

**Comment by jcsteh** [comment]
In that case, I have absolutely no idea what's going on. Sorry. I'm not particularly experienced where Mac development is concerned and don't have a development environment readily set up, so I don't think I'm going to be able to lookinto this. Hopefully, someone else will be able to help...

**Comment by tbdalgaard** [comment]
Hi Keith!

I am running Catalina over here, but will be glad to take a testdrive with the portable Reaper you provided.
Should this thread stay open, or should I contact you via the information I have via rwp?

**Comment by KeithRempel** [comment]
Hi,
I suppose the thread should stay open. If this turns out to be an issue affecting all pre 10.15 users, might be an idea to make a note of it on the download page, and possibly provide a link to a stable OSARA version that people could access.

Would be curious to see what happened if you tried my portable. Think I might try updating my OS. I was concerned about compatibility with my interface. But there’s always time machine. Would be at least somewhat useful if we knew for sure that OS version was the variable. Email me off the thread if that seems more appropriate.
Thanks.

**Comment by tbdalgaard** [comment]
Keith, I just got a few minutes to test your build, and think I found something. Have posted to RWP about this, so other users can try my poor experimentation.
I have pasted my message to rwp below.

Hi Keith and Keith!

Keith R. made a portable OSARA which I have tested on my system and found some interesting observations. Note I tested on mac OS Catalina 10.15.7, and I do not have access to Mojave installs at the moment.

It seems to me that sws and the latest builds of OSARA in some rare cases will be blocked when Reaper is opened for the first time when the 64-bit version of Reaper is used.
If you at any point gets a warning about an extension being blocked, do not press cancel. Instead do the following:
Try to open system preferences, security and here find the general tab.
Go to the buttom of the window, and press VoiceOver-left arrow.
You may find an allow button at some point. If you continue moving to the left, you wil read which application or extension Mac OS did block.
Keith R.: I had to open your portable Reaper twice for this to show up, because I by mistake pressed Cancel the first time I got a warning.

Hope this helps, and please post your results.

**Comment by tbdalgaard** [comment]
Ok, now I have done some more experimenting, and there are something strange going on here!

I got sws to work fine inside your portable Reaper, and I got the keymap from OSARA going, but I could not get OSARA to show up inside Reaper at all.
I wonder if this has something to do with the way Mac builds are done. Can we roll back one version of the OS this was compiled under to see what's going on?

I tested with my old laptop running 10.13, and OSARA did for sure not play nice here.

I even tried running Reaper through Terminal, but got no output logging at all.

Are there any way we can try to get OSARA to give an error or perhaps Reaper to warn us that OSARA could not be loaded or run?

**Comment by jcsteh** [comment]
> Can we roll back one version of the OS this was compiled under to see what's going on?

We went from Xcode 9 to Xcode 11, but also changed from Travis CI to AppVeyor, which doesn't have Xcode 9 at all. It really isn't feasible for me to roll this back. Even if it were, it's not sustainable in the long-run. I'd be very surprised if everything built on Catalina can't be run on earlier versions; that'd cause a lot of problems for a lot of Mac developers.

> Are there any way we can try to get OSARA to give an error or perhaps Reaper to warn us that OSARA could not be loaded or run?

Not that I know of. The only error condition on load that OSARA has control over is whether your version of REAPER is too old (minimum v5.982). Otherwise, the error is occurring before OSARA even loads, so OSARA can't log anything. I don't know of any REAPER settings to warn about extension load errors.

All of that said, let's at least be certain where this started failing. While I unfortunately suspect the Xcode/AppVeyor shift is where the problem started occurring, it might be more recent than that. So, here are a few builds to try:

1. [Last build on Travis CI and Xcode 9](https://osara.reaperaccessibility.com/snapshots/osara_2020.1pre-181,86ecda19.dmg): I'm almost certain this will work, but this is our baseline.
2. [First build on AppVeyor with Xcode 11](https://ci.appveyor.com/api/buildjobs/0saakgukboky8aav/artifacts/installer%2Fosara_2020.1pre-220%2C96141ce3.dmg)
3. [First build which reverted some hacks needed to support Xcode 9](https://ci.appveyor.com/api/buildjobs/mp1cqf6wtmrp0y10/artifacts/installer%2Fosara_2020.1pre-222%2C01485e44.dmg)
4. [Last build before OSARA updated REAPER API header to 6.13](https://ci.appveyor.com/api/buildjobs/8q0cni78rb3xi3or/artifacts/installer%2Fosara_2020.1pre-241%2Cd55cb315.dmg)
5. [First build after OSARA updated REAPER API header to 6.13](https://ci.appveyor.com/api/buildjobs/50a19671bvfkafqo/artifacts/installer%2Fosara_2020.1pre-244%2C1abe3715.dmg)
6. [Last build before resizable Parameters dialog](https://ci.appveyor.com/api/buildjobs/limyt4uwkjvhcojo/artifacts/installer%2Fosara_2020.1pre-248%2Cc32f13fb.dmg)

**Comment by KeithRempel** [comment]
I have tried builds 1 2 3 and 5 from that list. Of those, the only one to function was the XCode 9. Didn’t go through all of these on my old laptop running 10.13.something, but the 1 I did try was broken. in the same way as on my mac mini.

Thanks anyway for the links. Was hoping for some sort of magic discovery leading to an easy fix.
