### ISSUE TITLE
Is any possible to visit those scripts with screen reader?

### ISSUE THREAD

**Issue by vgjh2005** [jcsteh/osara#354]
Hi jcsteh:
Recently, I am collecting ReaScripts from cockos forum via Reapack. I find lots of useful scripts. But they can't be visit by NVDA except for OCR recognition. Is any way to visit them and why can't they be visited? 
For example, Reaper update utility page:https://forum.cockos.com/showthread.php?t=242922
Thanks!

**Comment by jcsteh** [comment]
I don't understand what exactly is inaccessible. Can you please provide the
exact steps you took, what you expected and what happened instead??

**Comment by tbdalgaard** [comment]
I think we have to get the Reaper developers at this, since the window for the script that are shown as an example only opens a graphical window with no keyboard access.
Tested on Mac OS and while I could get the window in focus, nothing else was possible to focus when I was inside the window.
I guess this is an issue when lua is used alone, 
Could we get Cockos to look into this perhaps?
If they can provide some accessibility inside their SDKs that might be the best way, or should OSARA make some workarounds instead?

**Comment by ScottChesworth** [comment]
I've spoken to Cockos about accessifying ReaScript GUIs before. At that time, it was a job beyond their resources. That was quite a while back though, so I guess I can try again.

**Comment by jcsteh** [comment]
It's not (and will never be) possible for OSARA to make these accessible. The GUI building that ReaScript provides is very raw (drawing lines, shapes, text, etc.; checking for mouse clicks, keyboard input, etc.). There's no concept of semantics; i.e. nothing to tell a screen reader that something is a button (beyond how it looks). Unless REAPER provides ReaScript APIs to expose accessibility information (and the chances of authors using this are near 0 due to the complexity of doing that kind of thing from ground 0), these will probably never be accessible.

Closing because there's literally nothing we can do about this in OSARA.
