### ISSUE TITLE
UX smoother: SWS cycle actions still run when OSARA's Shortcut Help mode is on

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#359]
I'm just starting to get into making cycle actions, and noticed that the one I'm currently testing runs even when Shortcut Help mode is on. Is this something that can be squared away without too much effort?

No biggy if not, I can just include a warning in the ReadMe when I share the action, but figured I'd report it.

Cheers,

Scott

**Comment by jcsteh** [comment]
Do cycle actions show up in the REAPER actions list or are they entirely
separate? If they're separate, there's no way OSARA can intercept these.

**Comment by jcsteh** [comment]
Unless the SWS developers were willing to call some kind of hook in OSARA,
which I could probably implement easily enough.

**Comment by ScottChesworth** [comment]
They do show up in the actions list.

**Comment by Lo-lo78** [comment]
Hi James,

In the action list, cycle actions are represented with these IDs:


Alt+Shift+è; Description: Manolo - Vai al take marker precedente; 
Command ID: _S&M_CYCLACTION_1

Alt+Shift+à; Description: Manolo - Vai al take marker successivo; 
Command ID: _S&M_CYCLACTION_2

Y; Description: Manolo - muta e smuta i send della traccia selezionata; 
Command ID: _S&M_CYCLACTION_3


Il 04/11/2020 23:07, James Teh ha scritto:

**Comment by jcsteh** [comment]
Weird. In that case, I don't know why they wouldn't work. I guess maybe the
SWS action hook runs before OSARA's hook in this case? But then I don't
understand how OSARA is able to hook other SWS actions just fine.

**Comment by ScottChesworth** [comment]
I wonder if @nofishonfridays has any thoughts on what's going on here, what with him being a chap who knows his way around SWS?

**Comment by jcsteh** [comment]
> I guess maybe the SWS action hook runs before OSARA's hook in this case? But then I don't understand how OSARA is able to hook other SWS actions just fine.

Oh. I just realised: we only currently have post hooks for SWS actions; i.e. they run after the command, rather than intercepting it. We've never tried to intercept SWS actions; we've never needed to before this point. So, the SWS hook probably runs before OSARA's and the action runs before we get a chance to intercept it.

We might (and that's a big might) be able to get around this by installing OSARA's hooks after a slight delay instead of as soon as OSARA loads. Maybe, that would mean hooks for other extensions have already been installed, so OSARA's would be the last hook installed. But that assumes that the last hook runs first and I'm not even sure if that's a valid assumption.

**Comment by jcsteh** [comment]
@ScottChesworth, does shortcut help currently capture other SWS commands?

**Comment by jcsteh** [comment]
> @ScottChesworth, does shortcut help currently capture other SWS commands?

Looks like it does. In that case, I have no idea what's going on here, since looking briefly at the SWS code, cycle actions end up going through the same hook as other SWS actions.

**Comment by jcsteh** [comment]
> We might (and that's a big might) be able to get around this by installing OSARA's hooks after a slight delay instead of as soon as OSARA loads.

Tried it. Doesn't work. Out of ideas.

**Comment by ranetto** [comment]
Hi James, I try to give you a suggestion but take it for what it is:
as keyboard hooks behave differently depending on which process they go over, you may launch osara hook later than previous extensions but it would be difficult to calculate what delay time it takes because I think it is very variable according to system processes in use, but I would suggest you try to throw your hook, even normally to re-drop it and recreate it when the whole sequence is done.
Maybe intercept "ID" of the process in WindowProc callback?
If you intercept the keyboard message queue you may know where yours is and how to handle the queue itself.
But mind you, James is just poor advice:
if i can help i always try for what the help of an amateur developer is worth.
Thanks again for everything you do for us.

**Comment by cfillion** [comment]
> We might (and that's a big might) be able to get around this by installing OSARA's hooks after a slight delay instead of as soon as OSARA loads.

The hooks are run in the same order they were registered. Unfortunately OSARA would need to register its `hookcommand2` before SWS does to be able to intercept its actions. Most SWS actions are run from `hookcommand`: those work with Shortcut Help because OSARA intercepts them earlier via `hookcommand2`.

**Comment by jcsteh** [comment]
Ah. Thanks much, @cfillion. That makes sense.

I was originally wondering why SWS was always loading before OSARA. However, I just realised that SWS is in Program Files, where OSARA installs to %appdata%\reaper\UserPlugins. REAPER probably scans UserPlugins second.

That does lead to the question: in what order does REAPER load extensions from the same directory? Is it strictly alphabetical or is it whatever order is returned from the file system? I guess it's academic anyway, since relying on that feels really brittle.

Finally, I wonder if there is any chance SWS would be willing to set the command hooks after a very slight delay? Of course, it would be totally understandable if that was a "no", given that this would be very specifically for OSARA and even more specifically for cycle actions. Still, I figured it was worth asking.

**Comment by cfillion** [comment]
Extensions are loaded in filesystem-dependent order. SWS installs itself into UserPlugins too from [v2.11](https://www.sws-extension.org/download/pre-release/) onwards.

> Finally, I wonder if there is any chance SWS would be willing to set the command hooks after a very slight delay?

Installing the hooks later would break running SWS actions from startup scripts. Perhaps OSARA could expose an API function that SWS would call in its `hookcommand2`? SWS builds for testing the idea at reaper-oss/sws#1461.

```cpp
static bool OSARA_IsShortcutHelpEnabled()
{
  return isShortcutHelpEnabled;
}

// C++ only, won't be available to ReaScripts
rec->Register("API_OSARA_IsShortcutHelpEnabled", (void*)OSARA_IsShortcutHelpEnabled);
```
