### ISSUE TITLE
Export the fakeFocus state to Reaper API

### ISSUE THREAD

**Issue by outsidepro-arts** [jcsteh/osara#362]
After exporting the osara_outputMessage to Reaper API became possible to extend Reaper accessibility abilities via ReaScript, unnecessarily to pull new features to main OSARA code. Some people know one of proposed ReaScript languages and don't sure own skills to write optimized code for Osara paradigm. But another Osara feature cannot be realized directly in ReaScript and it is focus context. This variable state named as fakeFocus in the Osara code. may this state be exported to Reaper API like as osara_outputMessage? It might be present as function...

**Comment by jcsteh** [comment]
What's the use case for this? Can you give me an example of how you plan to use it?

I'm pretty wary of exposing this kind of internal stuff. For one thing, it makes things harder if we need to change the implementation in OSARA for some reason; we don't want to break scripts that might depend on it. There's probably not so much likelihood that a focus type will be removed, but if one gets added, scripts won't necessarily know what to do with it.  I'd be even less comfortable with a script being able to set this, since that might mess up other internal state.

Anyway, let's discuss real world scenarios first (i.e. something someone really wants to implement, not just a theoretical conversation) and we can go from there. If we make implementatoin decisions without understanding how they're going to be used, they're very likely to be bad decisions in the long-run.

**Comment by outsidepro-arts** [comment]
For example, i am writing the reascript complex right now that  realizes the switch track, item time ruler property or even more. There are planning a few scripts to switch to next or previous track, item and etc property depending on focus, then ajust or toggle this property. There are will be dynamicaly properties ribbon, everybody will be able to add a new property and needed action to interact with. But Reaper does not proposes any method to get last touched or interacted media element. Osara defines this using last reported event and does this confidently.
I'd tried to write any method to get the value at least approximately, but it was not works. reaper.IsMediaItemSelected() always returns the state of last touched item even if track navigation already has been executed.

**Comment by jcsteh** [comment]
It's still not clear exactly what your scripts will do. What are you trying to achieve that OSARA doesn't already do? Why does it need to know about fake focus? Please give an example of why and how a user might use such a script.

**Comment by outsidepro-arts** [comment]
Thank you, no function needed. Reaper API proposes the method reaper.GetCursorContext() which i've not found at first work time with non-fully API documentation
