### ISSUE TITLE
OSARA does not report if an fx is active or in bypass in the fx monitor

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#370]
Hello everyone!
i am doing an effects chain dedicated to mix analysis, for this i am using the fx monitor.
The fx monitor is very handy!
The problem is that if I want to know if the plugin is in bypass or active OSARA does not report it to me as for the fx of the tracks or the master.
Thanks!

**Comment by jcsteh** [comment]
Unfortunately, this isn't currently possible. The REAPER API doesn't seem to provide a way to determine which effect is selected in the monitoring FX.

Technical note: We use TrackFX_GetChainVisible to work out which effect is visible in the chain for normal track FX. However, this doesn't work for monitoring FX and I don't see any other API function to achieve this.

**Comment by ScottChesworth** [comment]
I've just written to Cockos to see whether they have any advice, and requested a new API if there's not a workaround.

**Comment by jcsteh** [comment]
> Technical note: We use TrackFX_GetChainVisible to work out which effect is visible in the chain for normal track FX. However, this doesn't work for monitoring FX and I don't see any other API function to achieve this.

As of 89f197ad, we use GetFocusedFX instead of TrackFX_GetChainVisible and TakeFX_GetChainVisible. This is a function I previously missed and is more appropriate for what we need. This does work for input FX, but not monitoring FX; it returns 0 for monitoring FX.

So, what we need is for Cockos to tweak GetFocusedFX to treat monitoring FX the same as input FX; i.e. return 1 to specify track FX, set tracknumberOut to 0 for master and set fxnumberOut to a value >= 0x1000000.

**Comment by jcsteh** [comment]
I emailed Cockos myself with this new info.

**Comment by jcsteh** [comment]
Fixed in latest REAPER dev build, so it'll be fixed in the next REAPER release (I guess it'll be numbered 6.20). No change to OSARA needed.
