### ISSUE TITLE
Osara is responding slow and the speech lags when using the report soloed tracks action

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#383]
it takes much longer to report how many tracks are soloed if there are many virtual instruments in use. It happened to me when I had more than 10 Kontakt instantiated. unarming tracks or bipassing fx makes no difference

**Comment by ScottChesworth** [comment]
Does this clear up if you disable "Report changes made via control surfaces" in OSARA Config?

**Comment by jcsteh** [comment]
It'd be helpful (and this applies to anyone filing issues) if you could provide exact steps to reproduce the issue. For example, when you say "report how many tracks are soloed", are you talking about track navigation (which seems to be how Scott interpreted it) or are you talking about the report soloed tracks command? Neither of these reports "how many tracks are soloed", hence the confusion.

All of that aside, my guess (and it's very much a guess given the lack of info) is that this is caused by the solo defeat reporting. The REAPER API doesn't properly support querying solo defeat, so OSARA has to inspect the raw track chunk data for that information. I guess if the track data is huge for every track, that might slow things down.

[Here is a build from just before the solo defeat support](https://ci.appveyor.com/api/buildjobs/x7qw7mwo7baqcuu6/artifacts/installer%2Fosara_2020.1pre-305%2C8e2a70c6.exe). Try that and see if it makes a difference. If it does, we'll probably need to revert the solo defeat code and ask Cockos for something better.

**Comment by GianlucaApollaro** [comment]
Hi,
I'm talking about the report soloed tracks command
And It happens mostly when there are many vstIs loaded, to me it happened with Kontakt,  and the tracks had no midi items, just an instrument per Kontakt instance loaded. I had a vst on every track

**Comment by GianlucaApollaro** [comment]
disabling "Report changes made via control surfaces" in OSARA Config made no difference.

**Comment by GianlucaApollaro** [comment]
Hi,
I performed some other tests with the latest build and the speech lags mostly when there are many instances of Kontakt or Komplete Kontrol loaded. Doesn't matter which screen reader is used. I tested with jaws and Nvda and both of them lag. Once with jaws reaper became not responding for about 3 seconds and then it said the soloed tracks. There is no difference how many track you solo, even when there are none you hear "Soloed none" after 5 or more seconds since when the key is pressed.

**Comment by jcsteh** [comment]
And did you test with the earlier build I linked above several days ago?

**Comment by GianlucaApollaro** [comment]
Yes, tested and no lag at all

**Comment by jcsteh** [comment]
Okay. In that case, we need a proper way to get solo defeat from the REAPER API that doesn't require the use of GetTrackStateChunk. Ideally, we'd want to be able to fetch this using GetSetMediaTrackInfo.

**Comment by ScottChesworth** [comment]
> we need a proper way to get solo defeat from the REAPER API that doesn't require the use of GetTrackStateChunk.
> 
News just in: GetTrackStateChunk throws screen readers into a funk!
> Ideally, we'd want to be able to fetch this using GetSetMediaTrackInfo.
> 
Can you lay out in brief why that would be better for accessibility? Is it the type of better that'll be okay on both platforms?
Asking so I can throw down a solid explanation of why we need the change we're requesting. Justin generally responds well to that.

**Comment by jcsteh** [comment]
This is educated guesswork on my part, but I think the reason this is slow is that GetTrackStateChunk (which retrieves the entire data for the track) takes  a while (or maybe OSARA takes a while to search the data) when the track contains a lot of stuff, as it would if there are a lot of FX. In contrast, GetSetMediaTrackInfo allows us to ask REAPER for a single property, instead of REAPER having to return the entire data. So, it's much faster.

**Comment by ScottChesworth** [comment]
Gotcha, thanks for clarifying. I've emailed Cockos asking for solo defeat status to be added to what can be queried using GetSetMediaTrackInfo, explained how GetTrackStateChunk seems to be causing performance hits at present, and asked whether they have any suggestions of how else we might approach obtaining info on solo defeat if the API can't be tweaked so that GetSetMediaTrackInfo meets our needs. More whenever I know it.

**Comment by jcsteh** [comment]
@ScottChesworth , given that this is causing performance problems (pretty sure I'm seeing this myself on KK tracks), I'm thinking we should partially revert solo defeat support for now. That is, you'll be able to get the state when you toggle it, but it won't be reported when navigating to tracks or using the report soloed tracks command. What do you think?

Of course, once we get proper API for this, this can be re-enabled.

**Comment by ScottChesworth** [comment]
Sounds sensible to me man.
