### ISSUE TITLE
A technical question about the parameter view

### ISSUE THREAD

**Issue by davidkreynolds** [jcsteh/osara#393]
Hi,
How does OSARA process data for the parameter list as invoked by pressing P?
When using CSI to control plugins, they use parameter numbers. It would be so convenient if you both used the same methodology to create the parameter list.
Not really an issue, but I'll close it if you can give me some kind of answer.
Thanks.

**Comment by jcsteh** [comment]
OSARA queries all parameters in the order they're exposed via the REAPER API. I guess you could say that means it uses "parameter numbers" internally, though I guess that depends if CSI has its own concept of parameter numbers or whether it uses the REAPER API numbers unmodified.

Note that the numbers shown after the parameter name in OSARA's dialog have 1 added to them for user friendliness, since REAPER parameter numbers are 0 based. That is, if OSARA says (1), the internal parameter number is actually 0.
