### ISSUE TITLE
OSARA does not give feedback when inserting an automation item

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#394]
Hi,
when I insert an item with the action:
Envelope: Insert automation item,
OSARA does not give any feedback, can it be implemented?
Greetings and thanks!

**Comment by Aleskis** [comment]
I would like to draw your attention to this request, because at the moment, we are adding verbalization to OSARA.

**Comment by ScottChesworth** [comment]
@leejul , can you check open issues for that problem where focus gets lost, and create a new issue if we don't already have it open? Thanks.

**Comment by jcsteh** [comment]
We will need to deal with the various actions here as separate chunks of work.

Insertion of automation items is based on either time selection or the current edit cursor position. We can hopefully determine which automation item was added based on that.

For deletion, we should hook any related actions that we don't hook already and we should clear OSARA's current automation item so that envelope point movement doesn't get stuck in limbo.

**Comment by jcsteh** [comment]
I think we have a bigger problem here. I always assumed automation item selection was only relevant for the currently selected envelope. This is true for points; e.g. if you select some points on a volume envelope and then select some points on a pan envelope, deleting points only deletes the points on the pan envelope. It turns out that when you select an automation item, just like media items, it stays selected even if you switch envelopes. That means if you move to an automation item on a volume envelope and then move to an automation item on a pan envelope, pressing delete will actually delete both of them, even though we only report that one of them was deleted. Big ouch.

I'm going to need to fix this at a deeper level before I tackle splitting, etc. because otherwise, we're going to incorrectly select multiple items and incorrectly report how many are being manipulated, furthering the problem we already have for deletion.

**Comment by jcsteh** [comment]
Please leave this open. There are still bugs here.

**Comment by Lo-lo78** [comment]
@jcsteh 
Sorry!
I didn't realize you had reopened it.
I thought I was wrong to close.
Ok!
👍

**Comment by jcsteh** [comment]
To be clear, I do understand why you closed this - the original request was only for inserting automation items - but there's a bunch of discussion here about other (fairly serious) bugs that need to be addressed. Maybe I'll move that over to a different issue at some point.

**Comment by jcsteh** [comment]
I filed #1029, #1030 and #1031 for the remaining items. The request for which this was originally opened has been fixed already, so I'm closing this (again) now.
