### ISSUE TITLE
Inquiring about Apple silicon support

### ISSUE THREAD

**Issue by kyleman** [jcsteh/osara#402]
What is the status of apple silicon support? 
As OSARA is not built for arm64/M1 has anyone tested and can confirm that OSARA still works fine under Rosetta?
I know this would require devs to buy a new machine, Is that something in the works? I would be open to making that transition and being the beta guinea pig if needed.

**Comment by ScottChesworth** [comment]
We definitely don't have budget for a new development machine at this point. Wait for Jamie to weigh in on the technical considerations before you pull the trigger on anything, but potentially, yes, an M1 lab rat called Kaaaaaaarrrrrrrl could be very valuable.

**Comment by kyleman** [comment]
Well, I was going to wait for the next round of more pro-esk machines, but people have been saying that these machines are beasts anyway. So I've been leaning more towards pulling the proverbial trigger. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pitermach** [comment]
In theory, it should all work. Cockos already has an M1 beta build on the website, though because most plugins haven’t been recompiled they actually recommend people stick to running it under Rozetta for the moment so that you can use Intel audio units. In practice, we’ll have to see. I have an M1 Mac on the way, so unless someone beats me to the punch I can give it a try and report back here. Though this may take a while because the shop says CTO orders can take between 5 days to 5 weeks so when I get it is anyone’s guess.

**Comment by jcsteh** [comment]
1. I can't be certain, but I don't see any reason OSARA wouldn't run under Rosetta. It doesn't have any code which should be specific to processor architecture.
2. However, this will only work with REAPER x64 builds. You can't run an x64 library inside an ARM64 process.
3. There is a native ARM64 build of REAPER currently in beta, so it probably won't be too long until that's considered stable.
4. OSARA isn't currently built for ARM64, so it won't work with REAPER native ARM64 builds at all. Building for ARM64 requires Xcode 12, which isn't yet installed on AppVeyor; see https://github.com/appveyor/ci/issues/3542. I'm not entirely sure what I need to change, but my guess is that once we get and update to Xcode 12 (and deal with any fallout that causes), it should be fairly straightforward to build for ARM64 (probably similar to the previous stuff we used to build for x86).

**Comment by ogomez92** [comment]
Hi.
Sorry about the duplicate issue. Osara runs perfectly under Rosetta.
