### ISSUE TITLE
Non-true report of cutting portion of item

### ISSUE THREAD

**Issue by outsidepro-arts** [jcsteh/osara#423]
If will try to cut a portion of item using action, for example, "Edit: Cut items/tracks/envelope points (depending on focus) within time selection, if any (smart cut)", OSARA will report "-1 items removed".
Actions:
1. Set any time selection within active item.
2. Perform the action which cuttes the item portion, for example Edit: Cut items/tracks/envelope points (depending on focus) within time selection, if any (smart cut).

**Comment by ScottChesworth** [comment]
@jcsteh, I went with high priority for this one because inaccurate feedback seems worthy (if for no other reason that in the year 2030 when Hartgen next checks OSARA, he'll probably pooh blood on another podcast).

**Comment by RDMurray** [comment]
I think this is because the feedback is based on counting the number of
items in the project before and after the cut action.  It would be easy to
give no feedback in this case, but I don't know how we could implement
accurate feedback.

**Comment by jcsteh** [comment]
When you cut a portion of a single item, it gets split, so an additional item gets added. This will also be evident visually. Strictly speaking, the correct feedback here would be "1 item added". The question is whether this would be too confusing, and if so, what to do instead. @ScottChesworth?

**Comment by ScottChesworth** [comment]
Well ideally I'd like to hear the number of items that have been cut, but if you're already counting items then presumably the API doesn't provide anything quite so simple. Honestly, my thought is that if clarifying the feedback isn't possible, perhaps get rid of it? For my money, no report is preferable to a misleading report.

**Comment by jcsteh** [comment]
Strictly speaking, we don't know how many items have been cut, and nor does a sighted person. When you cut, you only see what gets removed (or split). You don't technically know what's been cut until you paste. That's why OSARA says "1 item removed" instead of "1 item cut". And when you do split, you're not really cutting an item at all. You're cutting a portion of an item, so even if we could say "1 item cut", that'd be wrong.

I think the simplest thing to do here is to probably just say "cut selected portion of items" or something like that. It's less specific, but there's also less chance of inaccuracy or confusion.

**Comment by ScottChesworth** [comment]
Gotcha. In that case, yeah, I'd say echoing the action name is a reasonable middle ground. That way the folks who'll want a report will still have something, but nobody hears anything misleading.

**Comment by outsidepro-arts** [comment]
I think that this needs convert the value to positive value and report something like "Portion of X items removed".

**Comment by jcsteh** [comment]
I thought of that, but unfortunately, that's not correct either. If you
select one item on one track which is inside the time selection and a
second item on a second track which spans beyond both sides of the time
selection (so the second item has to be split), the difference between the
old and new item counts is 0. The first item makes the item count go down
by 1, since it is completely removed. But the second item increases the
item count by 1, since it splits and thus adds a new item. There are other
cases where this breaks too; e.g. if you select an item which only extends
beyond one end of the time selection, you'll get 0 items removed because
the item count stays the same (no complete item removed or added).

**Comment by ptorpey** [comment]
Perhaps just an indication that the split actually occurred successfully would be fine then.  Sighted folks can see that the action was successful and we should know whether or not our action succeeded also.

**Comment by jcsteh** [comment]
Yeah, that's the current thinking; OSARA would just say "cut selected
portion of items".

There might be a better way: walk through all selected items, count how
many of them overlap the time selection and then report "cut selected
portion of n items", where n is the count. That still doesn't tell you how
many items were truncated, removed completely or split, though. I guess we
could try to figure that out too and say something like "cut selected
portion of 5 items, 1 removed completely, 2 truncated, 2 split". The
question is whether any of this is worth the implementation effort, since
it'd be pretty painful to do. Also, I worry about accuracy problems, since
we have to get the info before the cut occurs, not after. If REAPER doesn't
do the cut for some reason, we might report the wrong thing. That said,
there's no reason I can think of REAPER shouldn't perform the cut, though
it'd need solid testing.

**Comment by ptorpey** [comment]
I think that just knowing an action is successful or not is probably good.  Folks can always check the number of items on a track if they want detailed info on the change.  Sometimes too much feedback isn’t good either!

 

--pete
