### ISSUE TITLE
bind shortcuts to Media explorer actions Increase/decrease preview volume and provide feedback

### ISSUE THREAD

**Issue by kara-louise** [jcsteh/osara#430]
These actions were added in reaper 6.19 and could be useful.
They are:
- Preview: increase volume by 1 dB; 42177
- Preview: increase volume by 0.1 dB; 42179
- Preview: decrease volume by 1 dB; 42178
- Preview: decrease volume by 0.1 dB; 42180

Not sure which ones would be most useful, but you can decide that.

**Comment by ScottChesworth** [comment]
Will do. Just the 1dB actions to be mapped by default I think, unless anyone has any strong feelings about the 0.1 ones?

**Comment by RDMurray** [comment]
I think 1dB is small enough.  Feedback should be possible, but these actions would still be useful on the key map without it.  BTW the current volume is read by NVDA when the media explorer is shown or can be found with object nav.

**Comment by ScottChesworth** [comment]
Should we just mirror the Alt+Shift+UpArrow and Alt+Shift+DownArrow assignments we're using to adjust track volume by 1dB in the Main category then? Is it confusing for those keystrokes to act differently inside Media Explorer? I guess there's also the question of whether adjusting preview volume instead of adjusting track volume will break any workflows in a significant way. It wouldn't here.

**Comment by RDMurray** [comment]
Sounds fine to me.  I'll get on with implementing feedback next.

**Comment by ScottChesworth** [comment]
Nice one. Can we have the report prepending the word "preview" for the first adjustment in either direction as a quick reminder that we're not controlling track volume in this view?

**Comment by RDMurray** [comment]
It might not be possible without a fix from Cockos.  I can't find anything in the API that can get that value.  We could probably get it from the GUI, but it would be better if Cockos could provide it, possibly as an addition to Get_config_value().
