### ISSUE TITLE
OSARA only reports CC name and number if it changes

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#435]
Would it be possible to have an option to always report a CC's name and number, regardless of whether or not it has changed?

**Comment by ranetto** [comment]
I also ask it would be very useful because it is so confusing.
If you always knew the event on which you fall, you would go much faster.
Could you also change the value with the 2 and 8 of the numeric keypad?

**Comment by leonardder** [comment]
The idea is that when you're moving through many CCs of the same type, the cc type is omited, resulting in faster navigation.

Thoughs @jcsteh? I'm afraid that we can end up with many config options if we don't do this right.

**Comment by ranetto** [comment]
The concept would be right, but in my case, it confuses me a lot because if you hear the type of event you can more easily understand if the value is consistent:
if you don't hear anything you always have to rethink what you were referring to:
then before the first event and often after the last one osara says random values or zeros and thus confuses you even more.
What do you think?
The same thing happens to me when I move the notes:
if I hear 35 percent, forty percent or so on, I often have to listen back to whether I'm on the first bit or the second or which.

**Comment by jcsteh** [comment]
I don't really want to have a configuration option for this. If it's confusing multiple users, I'd be inclined to remove the cache.

> The idea is that when you're moving through many CCs of the same type, the cc type is omited, resulting in faster navigation.

I think part of the problem here is that this works well if you're moving through CCs without doing anything in between. However, if I understand the code correctly (I haven't played with it myself), the CC info will also be omitted if you move to a CC, go fiddle with notes and other things for 10 minutes and then move to another CC later.

**Comment by Batworx** [comment]
What's wrong with having a configuration option for this? There are already configuration options to speak or not speak other things. This satisfies users on both sides of the fence. How and why is adding a CC reporting option any different?

**Comment by jcsteh** [comment]
Adding configuration options is always a tradeoff between flexibility and complexity. If every single piece of feedback were configurable, we'd end up with hundreds of options, which is bad in terms of both code and user experience. In this case, it seems like we have multiple users who don't like the current behaviour, plus there are use cases where the current behaviour doesn't really make sense (e.g. if you work with notes and then move to a CC which happens to be the same as the last CC you were examining a long time ago).

Sure, If we were certain that both behaviours worked properly and there were sufficient scenarios where both would be used, that might justify a config option. I'm yet to be convinced of that.

**Comment by ScottChesworth** [comment]
> > it seems like we have multiple users who don't like the current behaviour, plus there are use cases where the current behaviour doesn't really make sense (e.g. if you work with notes and then move to a CC which happens to be the same as the last CC you were examining a long time ago).
> 
So perhaps if a user closes the MIDI editor or switches to navigating some other type of data, OSARA discards the cache? Seems like it might also be useful to have a timer doing that after say a minute of inactivity. Is that doable?

**Comment by jcsteh** [comment]
> So perhaps if a user closes the MIDI editor or switches to navigating some other type of data, OSARA discards the cache?

Detecting the various ways the editor can be closed is tricky. We could discard the cache on note navigation though, which is probably the major problem for this use case. I'd be curious as to whether the proponents of disabling this are confused because this happens even after navigatin notes or whether they find it confusing even when only navigating CCs.

> Seems like it might also be useful to have a timer doing that after say a minute of inactivity. Is that doable?

It's doable, but messy and somewhat arbitrary.

It'd also be good to have confirmation that some users like the current behaviour of not repeating the CC. Aside from the justification of why it's done, I haven't seen anyone actually saying they like it and would be less efficient if it changed. @leonardder, as the implementor of this, is this behaviour you depend on or did it just seem like a good thing to do for efficiency? No criticism at all, just making sure we have a solid use case.

**Comment by ScottChesworth** [comment]
I can put a call out for feedback on CC navigation via the WhatsApp group and report back.

**Comment by leonardder** [comment]
@leonardder, as the implementor of this, is this behaviour you depend on or did it just seem like a good thing to do for efficiency? No criticism at all, just making sure we have a solid use case.

The latter, so I'm happy to remove the cache. I think many good arguments have been made to do that.
