### ISSUE TITLE
Note previews in the event list only work properly if their length is one beat or longer

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#439]
When previewing notes in the MIDI event list, the previews only play correctly if a note has a length of one beat or longer. If the length is even one tick shorter than a beat, the note is only played for about a quarter of the displayed length. This is not affected by the "ticks per quarter note for new MIDI items" setting in Reaper preferences.

**Comment by leonardder** [comment]
I'm not sure whether I can reproduce this. Can you tell waht's the length displayed when you press ctrl+f2 after selecting the note?
Also, how is the preview on the piano roll?

**Comment by Batworx** [comment]
@leonardder, the piano roll preview is not affected. I'm using a "ticks per quarter note" setting of 192. If I create a note with a length that's displayed as 0.1.000 in event properties, the note preview works just fine. However, as soon as I have a length of 0.0.191 or shorter, the preview length is only about a quarter of what it should be. For example, if I insert an eighth note with a length of 0.0.096, the preview sounds like a thirty-second note with a length of 0.0.024. See the second project I emailed on Monday.

**Comment by leonardder** [comment]
A bit of a noob question may be, but where do I change the ticks per quarter note setting?

**Comment by ScottChesworth** [comment]
Prefs -> MIDI -> Ticks per quarter note for new MIDI items.

**Comment by leonardder** [comment]
I just tried this again, and still can't reproduce. What happens for me is, when I set a note length to 0.0.191, the note is indeed shorter, but that's because REAPER only seems to allow two numbers after the last dot, up to 99. So 0.0.191 is translated into 0.0.19.
Or may be there's another (project) setting I'm missing here that allows you to set the length based on ticks?

**Comment by Batworx** [comment]
@leonardder @ScottChesworth To change the ticks per quarter note setting, go to Preferences, Media, MIDI, Ticks per quarter note for new MIDI items. To display events using ticks in the MIDI editor, in the Options menu, go to "Time format for ruler, transport, event properties," and select "Measures.Beats.MIDI_ticks."

**Comment by leonardder** [comment]
Ah, I got it.
I think this needs a change to the REAPER API for `parse_timestr_len` and `parse_timestr_pos` to support a mode of ruler. Thoughts @jcsteh , @ScottChesworth?

**Comment by ScottChesworth** [comment]
My thoughts can basically be summed up as "huh?" :)
Happy to ask Cockos for the change though once @jcsteh has chipped in.

**Comment by leonardder** [comment]
@jcsteh have you seen https://github.com/jcsteh/osara/issues/439#issuecomment-756238333

**Comment by jcsteh** [comment]
Sorry, I did see this but had trouble understanding it on a quick look, so put it off until I had more available brain power. Sadly, that never happened. :)

I see a few problems with adding a mode of ruler for parse_timestr_len/pos:

1. Which ruler? There's the ruler for the TCP, the ruler for the piano roll and this other ruler for event list, etc. We'd need either three separate ruler modes or "ruler for focus". (I'm now realising OSARA's own formatTime function probably needs to account for the various rulers too, but let's ignore that for now.)
2. Really, we're building hacks upon hacks here. Getting the MIDI event data by parsing the ListView stuff was always clever but potentially fragile. Since we have to ask for something, I wonder whether it'd be more future proof to just ask for a way to get the REAPER note/CC/event number from a given event list index. After that, we can work with REAPER MIDI functions.

**Comment by ScottChesworth** [comment]
I can certainly ask Cockos if they can provide a way to get the REAPER note/CC/event number from a given event list index. Historically I've not had so much luck with requests related to MIDI, but we have an open issue here, maybe that'll help. @jcsteh, do you have enough spare brain bandwidth to be CC'd in on this one? Suspect it might need some technical knowledge that I don't have yet.

**Comment by jcsteh** [comment]
I'd like to wait for @leonardder to chime in on my idea before we go to Cockos in case I've missed a reason this is a bad idea. :)

That said, if he agrees, I can take this one to Cockos myself if that's helpful.

**Comment by leonardder** [comment]
I really dig this idea. As you (@jcsteh) said, it is indeed pretty hacky what we're doing currently.

**Comment by ScottChesworth** [comment]
A starter with Cockos is in your inbox, @jcsteh.

**Comment by jcsteh** [comment]
Okay. It turned out it wasn't feasible for Cockos to implement retrieval of MIDI note/CC indices. Instead, you can provide a ListView index and get the event data:

> We added this in yesterday's +dev build (it will likely go into 6.41 this week, too):
> nevents = reaper.MIDIEditor_GetSetting_int(wnd,"list_cnt")
> ok,str = reaper.MIDIEditor_GetSetting_str(wnd,"list_0","")
> (the docs describe the string returned for list_X :)

So, we'll have to do some string parsing. I haven't looked at the new header yet and I probably won't have a chance to do this in the next few days. I'm providing the info here in case you are able to take a look before I do, @leonardder .

**Comment by leonardder** [comment]
I tried this with REAPER 6.41, it it looks like the last line returns false:

```
	auto focused = ListView_GetNextItem(hwnd, -1, LVNI_FOCUSED);
	auto setting = format("list_{}", focused);
	char eventDetails[255] = "\0";
	MIDIEditor_GetSetting_str(hwnd, setting.c_str(), eventDetails, sizeof(eventDetails));
```

**Comment by leonardder** [comment]
AH, think I'm passing the wrong hwnd. I should pass the hwnd of the midi editor, not of the list view.
