### ISSUE TITLE
Is it possible to give feedback to know if a send of a track is stereo or mono?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#452]
Hello,
I often do mono sends but OSARA doesn't give any kind of feedback for this.
I'll explain!
I do a send from track 1 to track 2, press the I key and open the dialog box:
Routing for track 1 "".
I'm going upstairs:
Send to track 2 "": Delete;
I press the applications button and the contextual menu opens, I look for the MONO element and I send; from now on the send will be mono.
Except that in the context menu the MONO element does not say whether it is disabled or active.
Do you think it is possible to give this info to the user?
I have projects where there are many sends and obviously I don't remember the whole project setup.
So I just try to logically understand if a send is mono or stereo.
Thanks for all you do!
👍

**Comment by jcsteh** [comment]
OSARA builds that context menu by looking at the accessibility information exposed by REAPER's UI. I just checked, and unfortunately, Mono is just exposed as a button, not a checkbox, so there's no way of telling whether it's enabled or disabled there.

We could probably expose this in the OSARA Track Parameters dialog as we do for send volume/pan/mute, though this might be rarely used enough that this could be annoying. Thoughts, @ScottChesworth?

Otherwise, we'll need to get Cockos to fix this in the I/O window. We may want to do that regardless.

**Comment by jcsteh** [comment]
> We could probably expose this in the OSARA Track Parameters dialog as we do for send volume/pan/mute, though this might be rarely used enough that this could be annoying.

To be clear, this is literally a three line code change I've already confirmed as working, so it's purely a question of UX, not implementation.

**Comment by Lo-lo78** [comment]
Hi James, OSARA's track parameters would be perfect. I wouldn't find it 
annoying; in addition to volume, pan, mute, after the send we could 
think of putting after the button, send mono.

For example:

Parameter:

Volume
Value:
-5.77dB
Parameter:
Pan
Value:
center
Parameter:
Mute

Value:

off

Parameter:

29 voice reverb send volume
Value:

-6.02dB

Parameter:

29 voice reverb send pan
Value:

center

Parameter:

29 voice reverb send mute

Value:

off

Parameter:

29 voice reverb send mono

Value:

off

It is definitely not a big priority but over time it will be 
comfortable, it is not to be underestimated!

Greetings!
