### ISSUE TITLE
Mac OS builds do not compile

### ISSUE THREAD

**Issue by vick08** [jcsteh/osara#457]
After the recent attempt to make OSARA compile on an M1 chip, the compilation on an Intel chip does not seem to work.
1. The path to Xcode is incorrect.
2. SWELL class cannot find a certain function.
3. As a result, Scons fails.

**Comment by jcsteh** [comment]
Compilation definitely works on Intel, as AppVeyor runs on Intel Macs and Intel + M1 universal AppVeyor builds are succeeding and have been verified to work on both chips. I'm not sure if the two problems you mention are related, but the first is definitely tricky.

We now explicitly need Xcode 12.3 to build. The problem is that you can have multiple versions of Xcode installed side by side, as is the case with AppVeyor. Unfortunately (and I was worried this might be the case), I guess the App Store distribution of Xcode doesn't install to a versioned location, so it can't be found on your system. I don't know of any way to search for Xcode 12.3 specifically if it isn't installed to a specific location.

I don't really know how to best address this.

1. We could make the user set their default Xcode for command line builds using xcode-select. However, that would force the user to set 12.3 to the default, which might not be what they want for other projects.
2. We could have the user pass in the directory to the requested Xcode on the scons command line. However, that's pretty tedious for the user.

Thoughts?

**Comment by jcsteh** [comment]
I guess most systems will only have the latest version of Xcode installed, so perhaps the xcode-select method is the best option. On most systems, the user probably won't even have to run it because they'll only have one version.

**Comment by vick08** [comment]
Thanks for the correction. I was about to make the same point. Renaming the
path to reflect the Xcode version is not a standard ′default pattern′, as
it is not in my particular case.
After I renameed the app to Xcode-12.3, the XcRun was able to start,
however, I am still getting invalid method" call from Swell. Thoughtts?

**Comment by jcsteh** [comment]
#458 should hopefully make it so you don't have to rename it. I asked for your feedback in that PR.

As for the invalid call in SWELL, is this a clean checkout or did you just pull? if the latter, you'll need to update submodules, since WDL got updated:
`git submodule update`

**Comment by vick08** [comment]
OK, updating the submodule did it. For some reason, I thought that checking out with --recursive will always update the submodule upon later pulls.
I can compile now.
