### ISSUE TITLE
Extraneous reports of "track view" and "pane" when navigating tracks and items

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#461]
Filing this on behalf of a friend who isn't on GitHub yet. On his Windows 10 machine with Reaper, OSARA, SWS and NVDA all up to date at time of writing, he's getting intermittent extraneous reports of "track view" when he navigates tracks, and hears the word "pane" being reported often when he starts navigating items.
I've checked out his View menu, nothing seems awry there. Have also checked that there aren't any rogue open/floating windows causing it.
Does anyone have any thoughts on how to further diagnose? Right now, I've not been able to reproduce it on any other machine.

**Comment by ptorpey** [comment]
Is it possible that there is some other window open that is not associated with Reaper?  I’m thinking of some apps that often don’t show any info to the user but somehow lie on top to obscure other programs.  I’ve seen this with some installers, iCloud, and a few other programs.  Maybe even some error message from another app.  Anything unusual in the Task manager?

 

--Pete

**Comment by jcsteh** [comment]
This actually happens on all machines. REAPER 6 moves focus between two GUI windows, one when you focus items, one when you focus tracks. On most machines, either the message from OSARA interrupts the speaking of this window focus or the window focus gets spoken after the OSARA message. That leaves me with two questions:

1. is the "pane" or "Track view" announcement before or after the OSARA message? if it's before, that's obviously a real productivity killer. If it's after, that's a bit ugly, but I see it as a minor polish issue because it doesn't kill productivity; you can just ignore it or interrupt it.
2. If it's before, the OSARA message really should interrupt it. If it isn't, that suggests the user is running an outdated NVDA or is running some add-on which interferes with NVDA's builtin behaviour for this. So, what precise version of NVDA is this? Does it still happen if the user runs with all NVDA add-ons disabled?

**Comment by leonardder** [comment]
@ScottChesworth Anything to add here? I'm afraid there's not much we can do about this in OSARA, I'm not sure we can nor want to silence the focus events. We can hack around this in NVDA of course.

**Comment by jcsteh** [comment]
@ScottChesworth , any further developments here? As per https://github.com/jcsteh/osara/issues/461#issuecomment-765061446, I suspect this is due to an NVDA add-on. If there isn't interest in digging in further here, I'd suggest closing. We can always reopen should the interest re-surface.

**Comment by ScottChesworth** [comment]
Keep this open for now. this does happen on my newer machine whereas it didn't seem to on my previous one. I'll check things out in more detail now that I can reproduce it easily and address the questions above soon.

**Comment by ScottChesworth** [comment]
So after a solid day of keeping an ear open for this on my machine, the "pane" and "track view" reports always come after the pertinent information. However, I'm almost certain that the person who reported this was experiencing something more invasive. I'll reconnect with them, check it out and either update or close this soon.

**Comment by jcsteh** [comment]
Closing, since I've heard nothing significant or actionable about this in quite some time. Please reopen if you have further info.
