### ISSUE TITLE
Control Surface Feedback

### ISSUE THREAD

**Issue by mattymc2** [jcsteh/osara#469]
Hey all. First up amazing work on Osara. It just gets better and better all the time and it is beyond appreciated.
I have been using the new control surface spoken feedback feature extensively and love it for not only TCP values but for using my control surface within plugins ETC. 
One little tweak if its at all possible. As I move my fader on say a track volume, NVDA reads out the value as it should. But then as I move the fader it continues reading out values one after another so if I've moved the fader considerably it takes a long Time for NVDA's speech to catch up. 
Would it be possible for the read out to be interrupted and just say the latest value? I appreciate that tis would have to be a bit of a balancing act as you don't want to miss values either if it was too sensitive. Just my thoughts.

Cheers
Matt

**Comment by jcsteh** [comment]
What screen reader are you using? If you're using NVDA or Narrator, this should already be happening. If you're using JAWS, there's nothing I can do to fix this, since JAWS deliberately ignores UIA notification events, so OSARA has to fall back to an older hack to push messages.

**Comment by mattymc2** [comment]
Hey James. Using the latest NVDA with win 10. 
Cheers

**Comment by ScottChesworth** [comment]
Fancy seeing you here, @mattymc2!
Sounds like maybe OSARA is still reporting via MSAA instead of UIA. Dunno why that would be the case, but here's a way to check and change it if necessary.
1. Go to your Reaper resource path. For a full install, that'll be %appdata%\Reaper.
2. Find the file named "reaper-extstate.ini". This is where settings specified in the OSARA Config dialog are stored.
3. Open reaper-extstate.ini in Notepad or whichever clean text editor you use, and check whether this line is present:
uiaNotificationEvents=0
If it is there, change the 0 to a 1 (0 is disable, 1 is enable).
If it's not there, try adding uiaNotificationEvents=1, that should force OSARA to use UIA.

Restart Reaper, re-test whether fader movement interrupts and let us know how that goes.

**Comment by jcsteh** [comment]
There's another simpler possibility, which is that you have an NVDA add-on installed which is interfering. Please try restarting NVDA with add-ons disabled and see if that helps. You can do that from the exit NVDA dialog. In particular, I believe the Win 10 Essentials add-on has been known to cause this, though I may be misremembering.

**Comment by ScottChesworth** [comment]
Oops, forgot about that simpler bit. You're correct that Win10 App Essentials was the one that plays silly buggers. So far as I know @mattymc2, everything that add-on did is now baked into NVDA anyway, so if that turns out to be the cause, just remove the add-on.

**Comment by ScottChesworth** [comment]
@mattymc2, did you get this resolved?

**Comment by jcsteh** [comment]
I'm reasonably certain this isn't an OSARA bug, so closing due to lack of response. If the problem persists and the suggestions above don't help, please feel free to reopen. Thanks.
