### ISSUE TITLE
Portuguese (Brazil) translation

### ISSUE THREAD

**Issue by gabrielschuck** [jcsteh/osara#483]
Crowdin username:  gabriel-schuck
Language:  Brazilian portuguese (pt-BR)
reaperlangpack name: pt-BR.ReaperLangPack (https://stash.reaper.fm/v/36617/pt-BR.ReaperLangPack)

[pt-BR.zip](https://github.com/jcsteh/osara/files/6035768/pt-BR.zip)
Thanks!

**Comment by jcsteh** [comment]
Thanks. Invite sent.

**Comment by jcsteh** [comment]
@gabrielschuck, I notice that your translations are removing the placeholder braces from some of the strings. So, for example, we have the string:
showed {} envelope
which has been translated as:
Mostrando envelope
As noted in the translator comments, {} will be replaced with the name of the envelope, but since the {} is missing, the name can't be placed. Wherever there are braces, you should ensure those braces show up in your translation just as they did in the original string, though you can move them wherever you need to in the message.

Thanks.

**Comment by gabrielschuck** [comment]
Thanks @jcsteh for the warning! I will change the punctuation verbosity here so as not to pass any braces, it went unnoticed.
