### ISSUE TITLE
No speech feedback when hitting Control+Windows+Delete

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#488]
When hitting just the Delete key, Osara speaks how many items/tracks/etc. have been deleted as confirmation of the action.

When using the Control+Windows+Delete key to delete items there is no speech feedback.  Would be nice if this action could provide similar feedback to hitting the Delete key.

--pete

**Comment by ScottChesworth** [comment]
Question is, how do we report what's been removed productively?
With entire item removal, the reporting is informational but still short to listen to. no matter how many items were selected, "X items removed", job done.
With area of item removal, do you want to hear the area that's been removed reported in the primary ruler format? What happens when multiple items are selected? Something like "Here to There removed from X items"? Feels kinda long to listen to.
Does anyone have a better idea?

**Comment by jcsteh** [comment]
I think this should say something like "selected area of x items removed". However, we have the same issue as smart cut here: removing the items could add items due to splitting, so the normal way we calculate this isn't going to work. I think we need to write unified code to handle both this and smart cut of items.

**Comment by ScottChesworth** [comment]
> I think this should say something like "selected area of x items removed".
> 
Sure, that'd work.

**Comment by ptorpey** [comment]
> Agree with @ScottChesworth 
"I think this should say something like "selected area of x items removed"."

I would find any info about what has changed to be useful just to verify that the proper thing was done.

**Comment by ptorpey** [comment]
Didn't mean to close and reopen.  Just wanted to add a comment.

**Comment by ptorpey** [comment]
Just adding a comment to this old issue.
