### ISSUE TITLE
It is not possible to rename individual notes in the midi editor

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#495]
Hi,
I noticed that it is possible to rename individual notes in the midi editor.
I mean that a single note can be a sample, for example we could call it kick.
The action of the midi editor is:
Rename current note ...
40411
In theory the selected note can be renamed with any name but when I start the action nothing happens.
Maybe I didn't understand how it works but I know that there is the possibility to change the names according to your needs.
I'm not talking about the txt file with all the notes but to change the name of a single note.
I know it can be done!
Greetings and thanks!

**Comment by jcsteh** [comment]
This appears to be a REAPER bug. If you run the action by pressing space on the Run/close button instead of pressing enter on it, the rename text box gets focus as it should. If you press enter to run that action (either from the File menu or from the Actions dialog), the rename text box gets focus for a split second and then disappears. My guess is that it's catching the enter keystroke too early and treating it as if the user pressed enter to dismiss the field.

**Comment by jcsteh** [comment]
There are two other ways you could work around this bug:

1. Bind a shortcut key that doesn't include the enter key.
2. In English, press alt+f, n, r (File menu, Note/CC names, Rename current note).

**Comment by Lo-lo78** [comment]
Yes, James, perfect; it works! Maybe in the future, if Reaper solves the 
problem, we could improve! Thanks and regards!

**Comment by ScottChesworth** [comment]
I can take this to Cockos. Will report back when I get confirmation of a fix.

**Comment by ScottChesworth** [comment]
This will be fixed in today's dev build, and all being well, should be included in Reaper 6.26. Re-open if you're still having issues when that version drops.
