### ISSUE TITLE
Can action feedback around item grouping be improved?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#501]
Three observations on the spoken feedback OSARA currently provides around item grouping came in from @vick08. Pasting them here with a couple additions to see how much scope there is for improvement.
1. Items do not report when they are a part of a group.
Is it possible for OSARA to report whether an item is grouped when the user selects it, like how item muting and soloing is already reported?
2. If I have multiple groups of items within a project, OSARA reports "added to group" each time I create a new group, but it is not clear which group. Do they even have numbers or is this association between grouped items purely visual?
3. If I hit Control+Alt+G "on any item, OSARA reports "removed from group", even if that item has never been assigned to a group. Is there any way to make this feedback contextual, perhaps checking whether the item is assigned to a group and only reporting if removal actually happens?

Thanks in advance for any thoughts/improvements.

**Comment by jcsteh** [comment]
>     1. Items do not report when they are a part of a group.
>        Is it possible for OSARA to report whether an item is grouped when the user selects it, like how item muting and soloing is already reported?

Yes. Do you want the group number or just the fact that it's grouped?

>     2. If I have multiple groups of items within a project, OSARA reports "added to group" each time I create a new group, but it is not clear which group. Do they even have numbers or is this association between grouped items purely visual?

Each group has a number. What makes this messy is that, from what I recall, if you keep pressing control+g, REAPER will just keep creating new groups. Nevertheless, are you saying you want to hear "added to group 5", for example?

>     3. If I hit Control+Alt+G "on any item, OSARA reports "removed from group", even if that item has never been assigned to a group. Is there any way to make this feedback contextual, perhaps checking whether the item is assigned to a group and only reporting if removal actually happens?

It's possible, yes. I guess I figured most users wouldn't bother removing an item from a group if they didn't group it in the first place. Still, being pedantic here, yes, we can do better.

It'd be helpful to get a solid idea of what UX you're wanting here for the various possibilities (moving to a grouped item, adding an item to a group, removing an item from a group, attempting to remove an item from a group when the item isn't grouped).

Implementation note: We're going to need to make the item grouping commands fully hooked commands instead of post commands so we can inspect the group id before the command messes with it.

**Comment by ScottChesworth** [comment]
> 
> It'd be helpful to get a solid idea of what UX you're wanting here for the various possibilities
> 
Adding an item to a group:
I think OSARA's current report is already close, just add the group number.
Example report: "3 items added to group 1"
My rationale behind adding group number to the report is that it'll provide users with an unobtrusive reminder when they have multiple groups present in a project without them needing to hunt and peck to figure that out. My research indicates that sighted folk manage this information by assigning colours to groups.

Moving to a grouped item:
OSARA would ideally report grouped alongside other statuses like mute.
Example report: "1 Take 34.wav muted grouped in group 1"

Removing an item from a group:
Add group number as above, IE, "3 items removed from group 1"

Attempting to remove an item from a group when the item isn't grouped:
No report needed IMO, because nothing changed. This follows the rationale of existing navigation commands. For example, if you're already positioned at the beginning of the project and you hit Control+Home, no movement occurs, ergo OSARA doesn't speak.

**Comment by vick08** [comment]
Thanks @ScottChesworth and @jcsteh. You guys nailed it down. I really have nothing more to add to what Scott already wrote.
Thanks for looking into this.
