### ISSUE TITLE
Please add support for reporting RMS on master track to Peak Watcher

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#505]
API access to this info was provided in Reaper 6.26. Would be great to get OSARA tapping into that whenever someone has time.

Thanks in advance.

**Comment by ptorpey** [comment]
+1 – Nice that Cockos added this.

**Comment by jcsteh** [comment]
There are a couple of problems here:

1. As has been discussed elsewhere, this can only be done on the master, so adding it to the level type combo box isn't ideal. On the other hand, adding it to the track combo box feels even worse, since that then contradicts the type combo box.
2. As I understand it, people tend to want to set a window size for RMS. I believe that's configurable by right clicking the meter, but we don't have any way to access this context menu.

**Comment by ptorpey** [comment]
1.	As has been discussed elsewhere, this can only be done on the master, so adding it to the level type combo box isn't ideal. 

[PT] If folks really want RMS, might @scott request cockos enable RMS for all tracks (since they already have RMS for Master, should be easy)

2.	As I understand it, people tend to want to set a window size for RMS. I believe that's configurable by right clicking the meter, but we don't have any way to 

access this context menu.

[PT] Does that make a difference to screen reader users considering that we’re only grabbing the value from the API function?

**Comment by jcsteh** [comment]
I think it's possible to set the RMS window size via the API (get_config_var with mvu_rmssize variable?), but that would require OSARA to provide its own UI for that, which sucks.

**Comment by jcsteh** [comment]
> [PT] If folks really want RMS, might @scott request cockos enable RMS for all tracks (since they already have RMS for Master, should be easy)

Even visually, only the master has RMS meters. Tracks only have dB peak meters. So this isn't a simple API change.

> [PT] Does that make a difference to screen reader users considering that we’re only grabbing the value from the API function?

I think so? The RMS window size is a time in ms, I presume over which the values are averaged (since RMS is all about averages).
