### ISSUE TITLE
Reporting the state of free item positioning mode

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#519]
Free item positioning mode drastically changes how Reaper behaves. Ergo, it would be beneficial to have this reported in two ways:

1. Feedback for the following toggle:
Action: Track properties: Toggle free item positioning
ID: 40641

2. Can we be notified if FIPM is on when moving to a track?

As ever, thanks in advance.

**Comment by ScottChesworth** [comment]
In a fit of sleep-deprived ambition, I've attempted to implement action feedback for the FIPM toggle action above, but when I build, scons is disappointed in me:
src\reaper_osara.cpp(1827): error C2065: 'postToggleFreeItemPositioning': undeclared identifier
Does anyone have time to nudge a newb toward declaring this? My intentions are good, I'll add it to the ReadMe and everything. :)

**Comment by jcsteh** [comment]
Nice. Hard to say without seeing your code, but my guess is that you're defining the postToggleFreeItemPositioning function after the POST_COMMANDS array instead of before it. You could forward declare it to get around that, but the way the file is structured, all the post functions happen before the POST_COMMANDS array anyway. So, I'd place your new function after the end of the postToggleEnvelopePointsMoveWithMediaItems function.

**Comment by ScottChesworth** [comment]
Some progress. Can build now, but whenever I hit the key I've assigned to the action I get a report of "enabled free item positioning" irrespective of whether it's being enabled or disabled (I've verified that the state of the setting is changing as expected in the second track context menu). One other clue might be that as things stand, the report happens even if I don't have any tracks in the project, so there's clearly still a penny that hasn't dropped yet on how these pieces fit together.
If you have time to take a gander, here's the code. Essentially I'm attempting to lift your EnvelopePointsMoveWithMediaItems stuff wholesale and repurpose it. Think of it like taking recycling seriously, even though we both know it's abject laziness. :P

My new function (placed where advised) looks like this:
void postToggleFreeItemPositioning(int command) {
	outputMessage(GetToggleCommandState(command) ?
		translate("enabled free item positioning") :
		translate("disabled free item positioning"));
}

Then in the POST_COMMANDS array, I've added this:
{40641, postToggleFreeItemPositioning}, // Track properties: Toggle free item positioning

Any advice appreciated. Feels like I'm dangerously close to getting something useful done here. I haven't been this excited since the first time my snarky calculator program successfully insulted its creator. :)

**Comment by ScottChesworth** [comment]
Oh wait, isn't the POST_COMMANDS array for generic reporting? Maybe this doesn't need to be referenced there. But then, why is the postEnvelopePointsMoveWithMediaItems in both places.
Hmmm. Does OSARA need someone handling insults? I'm a dab hand at those.

**Comment by ScottChesworth** [comment]
Commented my addition in POST_COMMANDS array, just in case the hunch above was correct. Could still build, but now action feedback doesn't happen at all.
Not that, then.
DOH!

**Comment by jcsteh** [comment]
> outputMessage(GetToggleCommandState(command) ?

GetToggleCommandState only works for global or project toggles. In contrast, this is track specific, so you have to query the track for the right info.

Most track info is retrieved via the GetSetMediaTrackInfo function. That function has a string argument which specifies what piece of info you want and what type it returns. You then have to cast to that type, since that function is generic and can return many types. This is documented in the REAPER API header which REAPER can generate for you with an action (search for C++ in the actions list). OSARA keeps a copy in include/reaper/reaper_functions.h.

First, you have to get the current track:

```
MediaTrack* track = GetLastTouchedTrack();
if (!track) {
	return;
}
```

Now you have the track, you can get the info from it. The magic string for FIPM is B_FREEMODE (as found in the REAPER API header). So, instead of your previous:

`GetToggleCommandState(command)`

you'll want something like this:

`*(bool*)GetSetMediaTrackInfo(track, "B_FREEMODE", nullptr)`

**Comment by jcsteh** [comment]
Btw, the `*(bool*)` is really ugly and is because that function can return lots of different types. Breaking this down:

1. The `(bool*)` bit means: Cast this return value to a pointer to a bool, since that's what REAPER tells us B_FREEMODE returns.
2. The `*` at the beginning means: take this pointer to a bool and dereference that pointer so we can get the actual value of the bool.

**Comment by jcsteh** [comment]
> Oh wait, isn't the POST_COMMANDS array for generic reporting?

No; that's POST_COMMAND_MESSAGES. POST_COMMANDS basically says "here's an action id and here's the function you should call when that id happens". So you definitely need that bit.

**Comment by jcsteh** [comment]
Btw, the way you tell whether GetToggleCommandState will work or not for a given action is to look in the actions list and see whether it shows on or off. For example, if you look at Options: Solo in front, you'll see it shows on or off depending on the current state. In contrast, track and item specific actions don't show that in the actions list.

**Comment by ScottChesworth** [comment]
Thanks so much man. Think I understand how it fits together now. Well, understand it on paper. Feel free to place bets on what I'll trip over in practice, this turkey ain't cooked through yet. :)

**Comment by ScottChesworth** [comment]
> 2. Can we be notified if FIPM is on when moving to a track?
> 
I think I understand how to get that going, but it just occurred that when we had solo defeat being reported a few months back, that caused unacceptable lag. Would implementing this cause the same thing?

**Comment by jcsteh** [comment]
The lag with solo defeat occured because we had to fetch the entire data for the track and search it for the solo defeat info because REAPER didn't provide a more direct way of retrieving it. In contrast, there's an explicit and direct way to retrieve FIPM (this B_FREEMODE thing), so we shouldn't see lag in this case.

**Comment by ScottChesworth** [comment]
Gotcha. I'll try to get that going in a bit then. Should just be able to add it to the existing pull request I think.

**Comment by mattymc2** [comment]
You guys are bloody smart. That is all

**Comment by ScottChesworth** [comment]
> 
> You guys are bloody smart. That is all
> […](
One of us is. The other chap copies and pastes carefully. :)

**Comment by jcsteh** [comment]
Keep persisting! I want to flag that the REAPER API isn't particularly easy to work with. As much as I respect the power and flexibility it offers and Cockos's unwavering commitment to ensuring we have everything we need, parts of the REAPER API are pretty ugly and most of it is pretty poorly documented (and parts of it aren't documented at all). So, don't feel bad if you find it confusing at first. It's certainly not an easy starting point for diving into code, that's for sure. I've tried to make OSARA as clean and logical as I can, but there's only so much one can do. :)
