### ISSUE TITLE
The translations have not been compiled since May 21, is it a bug?

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#546]
Hi guys, how are you?
As part of the PMA team and one of the collaborators in the Latin American Spanish translation, I reported that the translations are not being compiled.
I think it applies to all languages, but would there be any reason for that? Or is it a bug that no one has reported? I do not like to bother, but we have already started July and the last template that people who are not translators have with Osara is from May 21. In fact, I thought the language template was compiling together with the latest Osara snapshot.
Thank you very much and sorry for anything.

**Comment by jcsteh** [comment]
I think the last translatable string added to the template was on 27 May:
`Report t&rack numbers`
I definitely see that string on Crowdin.
There have been fixes since then, but nothing that added or changed strings reported to users.
The 21 may date is the last time I pushed translations back to GitHub. I haven't done that since then because there haven't been many strings to sync, but I can do it soon.
