### ISSUE TITLE
horizontal zoom in midi editor

### ISSUE THREAD

**Issue by HenriNH6** [jcsteh/osara#561]
Good day. I would like to ask you to add the horizontal zoom narration function in the reaper in the midi editor. My problem is that many times I want to scroll notes freely without a time grid, and I use the - and + keys to specify how large or small parts the note will scroll to ignore the time grid, but osara in the midi editor does not tell horizontal zoom values. Could it be added to osara? Thank you very much, have a nice day.

**Comment by ScottChesworth** [comment]
Unfortunately we don't have access to this via the API. That's been requested from Cockos, but I haven't seen any movement on it yet.
Here's a workaround that will hopefully tide you over:
In the MIDI editor, hit Applications key on Windows or go to the menu bar on Mac.
Go to "View", then "Piano roll timebase", choose "Project synced".
Now in the "MIDI Editor" category of the actions list, reassign both of the keys used to adjust Zoom on your key map to "Misc: Pass through key to main window".
Once this is done, you'll be controlling the TCP horizontal zoom from inside the MIDI editor which OSARA can provide feedback for, and the zoom ratio within the MIDI editor will sync to that.
Note: you may also find it helpful to assign a keystroke to the action "View: Set horizontal zoom to default project setting" so that you can quickly reset zoom when back in the TCP. OSARA also provides feedback for that change.

**Comment by HenriNH6** [comment]
Hello Scott. Thank you very much for your advice and help. I did a survey and my results are like this. My midi editor is synchronizing with my project, this is great and if nothing else, if I zoom in or out on my horizontal zoom in the project, it will also work in the midi editor. As for the response, I don't know if I understood correctly how to set the shortcuts for the midi editor, I'm sorry I'm not so good at English and the google translator obviously doesn't translate it well for me. I tried to set different shortcuts for horizontal zoom and response in the midi editor for the main section and also for the midi section. When I opened it, Osara didn't give me. I also tried to keep the same shortcuts for the midi editor and for the main section and the zoom response didn't work. Apparently because the midi editor has its shortcuts that do not intersect with the shortcuts in the main section, if I understood correctly. I also tried to completely remove the shortcuts for the horizontal zoom with the section for the midi editor, but the shortcuts for the main section in the midi editor do not work. If I misunderstood it, can you write me a more detailed procedure so that the google translator also translates it correctly? Thank you very much again for your help and I wish you a beautiful day.

**Comment by ScottChesworth** [comment]
Ok, if you've got the zoom syncing then you're half way there already. Try this:
1. Open the MIDI editor, then hit F4 to load the actions list. You will automatically be placed into the MIDI Editor category of actions, because Reaper is smart enough to realize you were in the MIDI Editor when you did that.
2. Paste this next line into the search filter exactly as shown:
Misc: Pass through key to main window
3. Hit DownArrow to move to the search results, and you'll find the action called "Misc: Pass through key to main window". This already has a bunch of keystrokes assigned, but we're going to add two more.
4. Hit Tab twice to find the "Add" button. activate that, then type whichever key you want to use for zooming out (the OSARA default is NumPadMinus). When you hit Enter to save that new assignment, Reaper will probably warn you that the key is already assigned. It's fine to choose Yes, you need to override the prior assignment.
5. Repeat the step above, but this time after you've hit the Add button, type the key you want to use to zoom in (OSARA default is NumPadPlus).

Once you've done those steps, close the actions list and check whether hitting those keys you've just assigned speaks the zoom ratio now.

If you're still stuck, shout. We'll get it figured out. :)

**Comment by HenriNH6** [comment]
Hello Scott. Thank you very much. I already understood that and now everything works as it should. I also added the keyboard shortcut shift + num plus to reset the horizontal zoom to the default value of the project, I came up with the shortcut myself. It was very simple, I understand that in this action, osara in the midi editor works with shortcuts from the main section, a perfect tweak. Thank you from the bottom of my heart for your help, I have not been able to solve this for many years and I am happy about it, have a nice day. Good luck to you.
