### ISSUE TITLE
Respect measure offsets set in project settings

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#566]
Project settings (alt enter) allows an offset to be made in measures.  It is quite rare but it would be nice to be able to start from a measure of zero so pressing control home gets you to 0.1.0.
I think Reaper supports this but Osara is not.
However, I'd put this request pretty low down on the priority list and if it risks complicating a load of other stuff I wouldn't say it is worthwhile.

**Comment by MatejGolian** [comment]
@CastleStarter I personally think that that would be a nice addition. If it gets implemented into Osara I think having support for the project start time offset would be nice as well, since that setting is closely related to the project start measure. Not a must have - more of a luxury request compared to other things, but I for one would definitely make use of it if it got implemented. So, I'll file an FR for it.

**Comment by leonardder** [comment]
I love this idea. I think it can be especially handy for music with an up-beat, and I use that pretty often.
