### ISSUE TITLE
Suggestion/Request: Automatically Select MIDI CCs Under Selected Notes

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#574]
Hi there,
I think it would be nice if underlying CC messages got automatically selected when moving to and selecting notes in the piano roll. Can you think of a scenario where having this behavior as default would pose a problem? Personally I can't think of anything.
Rather than changing the way Osara currently works, perhaps creating custom actions would be a better and more elegant way to do it.
It should just be a matter of running the following action after the Osara ones:
Name: Edit: Select all CC events under selected notes
ID: 41735
I'll create custom actions for this and upload them to Dropbox, but I'd really love this behavior to be the default in the future.
Any thoughts?

**Comment by MatejGolian** [comment]
Update: I've tested my idea and while it works, the drawback is that since CC events also get selected, one always has to use the up and down arrow keys if one wants to edit note events. It's pretty obvious - don't know why I haven't realized it... I assume that this would make things complicated and unintuitive for most people.
So, if you think it's a good idea, would it be possible to add the Edit: Select all CC events under selected notes action on its own to the key map as an alternative?

**Comment by ScottChesworth** [comment]
> Would it be possible to add the Edit: Select all CC events under selected notes action on its own to the key map as an alternative?
> 
Sure. Any suggestion of a logical mapping?
Ideally we'd have action feedback implemented for that. Dunno if everything is already in place for a newb like me to be able to add that (I'm not familiar with how it all works in the MIDI editor yet), but I can try.

**Comment by Flameborn** [comment]
Not sure if there has been any change regarding this, but in the fairly up-to-date OSARA version I am using, the left/right arrows move between notes only, and the Next/Previous CC event actions are unmapped.

While I don't see editing both midi notes and CC events at the same time, it would be nice to have a unified interface.

This way, the left/right arrows would select the Next/Previous event similarly to how it works now, except with the addition that a mapped action could toggle between all/midi notes only/CC events only when moving around, acting as a filter.

This way, there would be hardly any reason to switch the midi editor to all midi events view, as OSARA would essentially handle all events, possibly defaulting to selecting midi notes only, so that the existing behavior is preserved. To achieve what this issue requests/suggests, one would need to toggle to all events, and move around as expected.

Having these unified would be a huge timesaver, because CC 1 (usually mod wheel), CC 2 (breath controller), as well as CC 11 (expression) and CC 64 are used extensively, especially for orchestral instruments.

**Comment by MatejGolian** [comment]
That's great. I was thinking we could use either C or U as the shortcut as those keys are still free and kinda logical within the constraints: U as in 'under selected notes' or C as in 'CC events'. I'm having a hard time deciding which one would be better as they both make sense, but perhaps U is a bit better in this case since people tend to associate C with copy related operations. Furthermore, leaving C available for some other more common action could be a good idea. What do you think?

**Comment by MatejGolian** [comment]
@Flameborn, those are some excellent ideas and I'd definitely be up for that. Assuming that it can be done, of course. So that's a huge plus 1 from me. :D

**Comment by ScottChesworth** [comment]
> in the fairly up-to-date OSARA version I am using, the left/right arrows move between notes only, and the Next/Previous CC event actions are unmapped.
> 
Control+Dash and Control+Equals are mapped to "OSARA: Move to previous CC" and "OSARA: Move to next CC" respectively.
Add Shift to extend selection as you move.
Add Alt to move between CC lanes.
Take away all modifiers (IE just Dash or Equals) to decrement or increment the selected CC.

**Comment by ScottChesworth** [comment]
> I'm having a hard time deciding which one would be better as they both make sense, but perhaps U is a bit better in this case since people tend to associate C with copy related operations.
> 
we already have a copy action on Control+C which is standardized and Control+Shift+C is smart copy, so I can't see a problem with using unmodified C for this. Maybe it'll get more folk curious about the potential of editing CC in piano roll view. The features have existed for over a year but I'm still only seeing a handful of people who know they're there for the tweaking.
Now I just need to carve out a bit of time for fiddling with things I don't understand to try and get it talking.
Keep your extremities crossed. I'll try not to delete the internet. :)

**Comment by Flameborn** [comment]
> Control+Dash and Control+Equals are mapped to "OSARA: Move to previous CC" and "OSARA: Move to next CC" respectively.
Ah, so they are mapped now, this is great to know, thank you!

In case this is not what you are planning to take up, is there any possibility of doing this with just one action/shortcut? I.e. move between all events? This way, notes and CC events would be selected as well, similarly to what I described in my unified events post.

**Comment by ScottChesworth** [comment]
> In case this is not what you are planning to take up, is there any possibility of doing this with just one action/shortcut? I.e. move between all events?
> 
That's a mile beyond what I can contribute code-wise. I'm just about capable of getting easy things to talk and updating the ReadMe accordingly lol.
> This way, notes and CC events would be selected as well, similarly to what I described in my unified events post. I'm asking because the left/right arrow makes a lot more sense with a filter than having two sets of shortcuts, to me at least.
> 
Thing is, Reaper doesn't provide previews for moving through CC's, and selecting those individually can be pretty slow going because of the resolution that's available when moving controls during live input. To me, it seems a lot more intuitive to select based on notes, then extend that selection to the underlying CC messages and refine CC selection from there if needs be.
I agree that two separate sets of keystrokes isn't ideal, but so far it seems like we're talking about a lot of work for minimal benefit. Or at least, benefits that haven't been made clear yet.

**Comment by leonardder** [comment]
I added the sentToKeymapCrew label since this deals with a keymap change.

**Comment by RDMurray** [comment]
> 
> Sure. Any suggestion of a logical mapping? Ideally we'd have action feedback implemented for that. Dunno if everything is already in place for a newb like me to be able to add that (I'm not familiar with how it all works in the MIDI editor yet), but I can try.

You could add an entry to the MIDI_POST_COMMANDS array to call postMidiSelectEvents() after the action.  This would say e.g. "8 events selected".

Is that acceptable feedback? It would be consistent with select all events and invert selection.

**Comment by MatejGolian** [comment]
@RDMurray, for me that's perfectly acceptable, but than again I'm not in charge and others may deem otherwise.

**Comment by RDMurray** [comment]
Now I think about it, I'm not sure what the feedback should be.  What I proposed above would report the total number of selected events, including the notes already selected.  Is this okay, or should it only report the additional events selected?  

It might also be good to support "Edit: Toggle selection of all CC events under selected notes".  In that case should it say how many events were unselected, or the total selected events? 

In fact since that is a more versatile command, maybe it is the one that should be added to the keymap?

**Comment by MatejGolian** [comment]
@RDMurray, adding 'Toggle selection of all CC events under selected notes' to the keymap instead seems like a good idea.
Regarding the feedback, it's a bit hard to decide, as it makes sense both ways. Just reporting the number of selected/deselected CC events seems more logical considering the name of that toggle action, but that does not necessarily mean that that's what the feedback needs to be based on. Further more, if Osara only were to count the additional events, things could hypothetically become confusing if the feedback didn't make it clear that that action only deals with CC events. So, I guess what I'm getting at is either just count the number of selected/deselected events, but include the abbreviation 'CCs' in the feedback, or always report the number of all currently selected events like you originally proposed. I'm not a programmer, but the latter seems more simple and foolproof to me. Maybe there's no need to make things unnecessarily complicated here...
Just my 2 cents, hope I was at least of some help...

**Comment by MatejGolian** [comment]
I commented over at the thread for the related PR, but I thought I'd leave a comment here as well just in case. @RDMurray, tested and working fine, so I thing this can be closed once it makes it into the public build.
