### ISSUE TITLE
Pianoteq 7 removes OSARA focus

### ISSUE THREAD

**Issue by betov75** [jcsteh/osara#577]
Hi,

When I open the FX window for Pianoteq 7 using F shortcut, after closing the window, OSARA stops reporting. But it's not crashed since I only have to move to another virtual desktop on Windows and go back to Reaper. Then, it works again. Changing the focus from Reaper to another opened window on the same virtual desktop don't bring back the reporting. The issue occurs without exception and the trick to bring back OSARA also works all the time.

That problem is only with Pianoteq 7. VST 2.0 or VST 3.0 version. All my other plugins work fine. I assume the Pianoteq 7 plugin is the culprit here.

Thanks!

**Comment by jcsteh** [comment]
Thanks for reporting. I believe that's a known bug in the JUCE framework. In any case, it's a bug elsewhere, not in OSARA, so I can't do anything about it here.

**Comment by jcsteh** [comment]
@ScottChesworth , I assume this has been reported to JUCE and is being tracked somewhere?

**Comment by ScottChesworth** [comment]
It's been reported, but accessibility related issues aren't being tracked anywhere public that I'm aware of. In the run up to the release of 6.1.0 they wanted bugs filed via forum instead of GitHub. Now that the release is out, I'm probably gonna switch to filing via GitHub just so I can find/bump stuff easier.

**Comment by leonardder** [comment]
Github makes sense. Could you please link to this issue there? That will link things up appropriately.
