### ISSUE TITLE
There are problems with: Custom: Select and move to first track e Custom: Select and move to last track

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#603]
Hello,
I often use these two custom actions and I noticed a strange phenomenon, in practice these two custom actions come into conflict with the action from time to time:
OSARA: Report track / item / time selection (depending on focus)
Try this:
Create 8 tracks and then go from first to last and there is no problem.
An incorrect aspect occurs when you switch from track 3 to 8, the OSARA action will be activated: Report track / item / time selection (depending on focus), as if it were pressed twice opening the selection window, having to press the Close button or esc.
The same phenomenon also happens if you go to the third last track from 6 to 1.
It doesn't happen with the other tracks.
Does it happen to you too?
Greetings!

**Comment by RDMurray** [comment]
I can reproduce this, but haven't managed to track down why it is happening yet.

**Comment by Lo-lo78** [comment]
I have no idea why this happens!

Maybe OSARA action:

"Report track / item / time selection (depending on focus)",

intercepts selections incorrectly.

In custom actions there are various selections and there maybe the 
action OSARA misinterprets the selection.

Regards!

**Comment by ScottChesworth** [comment]
I can't reproduce with those steps, but could get a selection dialog to appear when I moved from track 3 to the top. I think it's related to the position of the mouse pointer in some way, because when I moved the mouse, it stopped happening here.

**Comment by jcsteh** [comment]
I can't get "Select and move to last track" to work at all. For me, it always just selects the next track.

**Comment by jcsteh** [comment]
Having said that, I think I know what's going on here. Oops.

**Comment by jcsteh** [comment]
The thing that actually reproduces this is quickly pressing next track (or previous track) multiple times before you use the first/last track action. Actions intercepted by custom actions have to be hooked via a different code path due to a REAPER quirk/bug. That code path didn't reset the command repeat data, so OSARA thought the report selection action was repeated when in fact it was the previous/next track action. Fix incoming.

**Comment by ScottChesworth** [comment]
> That code path didn't reset the command repeat data, so OSARA thought the report selection action was repeated when in fact it was the previous/next track action. Fix incoming.
> 
Aha, that's good to know! I have two actual OSARA actions ready and working here, planning to submit those as a PR soon, I just need to get the Mac key map change done. IMO, replacing these custom actions would be preferable, because with my new actions, the feedback is standardized when moving to first or last track.

**Comment by jcsteh** [comment]
Yeah, I think builtin actions are going to be better anyway, but I figured
this was worth fixing regardless, as it would've bitten someone in some
other way soon enough.
