### ISSUE TITLE
Can OSARA fix where focus lands after closing the Auto add FX dialog on Windows?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#610]
There's a disparity between where focus lands on Windows and Mac when users close the Auto add FX dialog. The Mac behaviour aligns with the visual UX.

1. Make sure that "Auto-open FX add dialog when opening empty track FX chain" is checked in the Plug-ins category of Reaper Prefs. Checked is its default state, so unfortunately the glitchy behaviour described below is what most Windows users will experience.
2. On Windows, hit F on a track. The Auto add dialog appears, all is well. 
3. Now hit Escape to dismiss the FX ad dialog. Visually, an empty FX window is still on screen, but keyboard focus goes back to the main window instead. Manual redirection of focus is required before users can paste plug-ins/load FX chains/access the FX menu bar, and users aren't being informed that the FX window is still open.
4. Comparing above steps on Mac, keyboard focus does land in the empty FX chain list properly on the first press of Escape when dismissing the Auto add dialog, then a second press of Escape closes the FX window proper. Ideally, this would also be true for Windows users.

I've already taken this to Cockos. Justin said:
> in Windows when you close a window the focus automatically goes to the owner window, which in this case is the main REAPER window. I'll look at if we can code up a solution around this, but it might be a big can of worms so maybe not too soon...
> 
Ergo, I'm raising it here to see whether we can rustle up a solution sooner with less technical headaches.

I've also noticed that reporting as I navigate through tracks becomes sporadic when that stray FX window is still on screen, so I'm gonna label this as a bug and P1 for now. Feel free to adjust accordingly if I'm over-egging it @jcsteh.

Any thoughts appreciated.

**Comment by jcsteh** [comment]
The problem is that there's no reliable way (that supports multiple languages) to detect the Add FX dialog. Technically, there's no reliable way to detect any dialog, but you can sometimes get around that if the controls in the dialog have ids that don't appear elsewhere on the same kind of control. I think we've had bugs caused by this in the past. I might be able to manage something, but I'm not hopeful. Furthermore, detecting when that dialog closes is also tricky to do reliably. We risk ending up in a situation where OSARA incorrectly focuses the FX chain dialog when it shouldn't, which is IMO worse than the current situation.

Cockos might be able to help here by providing a reliable way to detect specific dialogs, but the approach I have in mind is pretty hacky and very specific to OSARA. They could set a window prop on the dialog HWND (SetProp) with a value indicating which dialog it is. For example:
```
const char name[] = "AddFX";
SetProp(dialogHwnd, "REAPERWindowId", (HANDLE)name);
```
We'd need that for the FX chain dialog as well. That doesn't fix the problem here, but makes it more likely that OSARA could reliably hack around it.

> I've also noticed that reporting as I navigate through tracks becomes sporadic when that stray FX window is still on screen,

Can you be more specific? I can't think of any reason this should be the case. Most of OSARA is coded in such a way that other windows open on screen just shouldn't ever matter because OSARA doesn't rely on screen coordinates or scraping for 99% of what it does. If that isn't the case here, that seems worthy of investigation.

**Comment by ScottChesworth** [comment]
> Cockos might be able to help here by providing a reliable way to detect specific dialogs
> 
Thanks, I've passed that along to Justin.

> Can you be more specific?
> 
I haven't written up reproduction steps because I can't get it to happen every time, but here's what happens when it does. When an empty FX window is open on screen that I'm not aware of, sometimes the screen reader stops reporting as I move between tracks. The actions to navigate the track list still work as expected, but the report doesn't happen. Here, moving a few tracks in either direction will bring reports back to life temporarily, but until I close the empty FX window, they'll vanish again before too long. I've been looking for patterns in where it happens in the track list, whether it's every X amount of movements etc, no dice. The only constants seem to be that dismissing the empty FX window instantly clears it up.
Would it be at all helpful if I record the behaviour next time it bites me?

**Comment by jcsteh** [comment]
Bizarre. Recording the behaviour probably won't be helpful. What might be interesting is the NVDA+f1 output for the focus when it occurs, assuming you're using NVDA. If you're using JAWS, I can't help you. :)

**Comment by ScottChesworth** [comment]
> What might be interesting is the NVDA+f1 output for the focus when it occurs, assuming you're using NVDA.
> 
Gotcha. Will post that ASAP.
> If you're using JAWS, I can't help you. :)
> 
I'm yet to see reports delivered by JAWS being afflicted. Oh the irony. :)

**Comment by ScottChesworth** [comment]
Justin says:
Hmm let me look, it might be easiest to enumerate the HWND for each track and find it that way…

I dunno what that means, but hey, it doesn't seem like a no.

**Comment by jcsteh** [comment]
The lack of reporting might actually be an NVDA bug, though I'm not sure
what would cause it.

I don't quite follow what Justin is saying there. Each track has an HWND,
yes, but we're trying to identify/find the Add FX/FX Chain dialogs, not the
track HWND.

**Comment by ScottChesworth** [comment]
I've put that point to Justin. Let's see.

**Comment by Lo-lo78** [comment]
Hi, I don't know if it's useful but there is an action that closes all 
windows except the one where the focus is:

SWS/S&M: Focus main window (close others)

I use this action a lot to clean windows left open after a long session.

Greetings

**Comment by ScottChesworth** [comment]
Yeah, I know. That's useful as a workaround, but it's not something we could provide contextual feedback for, so it would still be good to get this tightened up at the source IMO.

**Comment by Lo-lo78** [comment]
I don't know what the right way could be but if I can give an opinion it 
could link a feedback to the action of SWS.

Do you like Scot as an idea?

**Comment by ScottChesworth** [comment]
Like I said, we can't provide contextual feedback for the result of that action. We could say that the keystroke has been pressed, but we can't reliably collect information about which windows have been closed, if any. The current UX differs from what's on screen visually, and the way focus behaves on Mac is already correct, so IMO, the best resolution would be to figure out a way to get focus under control in the Windows build.

**Comment by jcsteh** [comment]
I thought of another approach to deal with this, though it's a bit risky. Rather than making this specific to the FX dialogs, we could do it for any foreground window change where the previous foreground window (e.g. dialog) disappears. That is, window a gets activated, window b appears, then window b closes or disappears. We would force focus back to window a. This would also deal with the case of opening the OSARA config dialog within the MIDI editor.

To that end, I'd be interested to know whether that OSARA config + MIDI editor issue happens on Mac. I'm starting to suspect it doesn't. If it doesn't, that means we don't need to worry about Mac for that issue and puts more weight on this as a good solution solving multiple problems.

**Comment by ScottChesworth** [comment]
There's an API-based proposal from Justin in your inbox too, just in case you haven't seen that yet. In any case, I've got an observant Mac user who can confirm the situation. Will check and report back (she's not on GitHub yet).

**Comment by ScottChesworth** [comment]
> To that end, I'd be interested to know whether that OSARA config + MIDI editor issue happens on Mac.
>
Jenny K just confirmed that it does happen on the Mac. Although, recovery isn't so bad over there because they have a well-known keystroke to cycle open windows within the current application, plus VO navigation is all object-based anyway.

**Comment by jcsteh** [comment]
That's unfortunate. I wouldn't be able to make the solution I proposed above work on Mac.

**Comment by ScottChesworth** [comment]
Hey @jcsteh, I've just been poking about in the ReaScript docs looking for something I need for my next PR, noticed these functions and wondered whether you'd already seen them?

HWND TrackFX_GetFloatingWindow(MediaTrack* track, int index)
returns HWND of floating window for effect index, if any

HWND TakeFX_GetFloatingWindow(MediaItem_Take* take, int index)
returns HWND of floating window for effect index, if any

Would they help to detect the presence of the troublesome windows at all? Felt like they might, but I'm not smart enough to work 'em yet.

**Comment by jcsteh** [comment]
Ah, I forgot about those. They would help to detect the FX chain I think,
but not the Add FX dialog. I guess we could just always through focus to an
open floating FX window if focus ever hits the track view, but that seems
pretty drastic. It might also end up throwing focus to the wrong FX window
if there happened to be two (or more) open.

**Comment by jcsteh** [comment]
> > in Windows when you close a window the focus automatically goes to the owner window, which in this case is the main REAPER window.

There's probably a really good reason this isn't the case, but just in case it's something Justin hasn't thought of, I wonder if there's any reason the Add FX dialog can't be owned by the FX chain dialog? That should mean Windows returns focus to the correct place itself.

**Comment by RDMurray** [comment]
> I thought of another approach to deal with this, though it's a bit risky. Rather than making this specific to the FX dialogs, we could do it for any foreground window change where the previous foreground window (e.g. dialog) disappears. That is, window a gets activated, window b appears, then window b closes or disappears. We would force focus back to window a. This would also deal with the case of opening the OSARA config dialog within the MIDI editor.

It would also deal with returning focus to the menu editor after adding an action from the action list.  Are there any cases where this behaviour would be undesirable? I can't think of any.  It would be a big improvement on Windows!

BTW, SWS identifies windows by the title which they translate before comparing. See Get*Wnd functions in Breeder\BR_Util.cpp

**Comment by jcsteh** [comment]
I was just looking at this again, since in REAPER 6.81, escape from the auto add dialog seems to be focusing the track view again instead of the FX chain. However, from what I can see, the FX chain isn't actually open at all, so focus can't return to it since it isn't there. Did something change here?

**Comment by ScottChesworth** [comment]
Haven't seen any mentions of change around this in REAPER's dev log, but I can reproduce your current findings. For some reason my brain is having a tough time redigesting this thread. Where does that leave us?

**Comment by jcsteh** [comment]
Well, if we're both correct, there's nothing to do here. Pressing escape from the auto add dialog doesn't leave the FX chain open, focused or otherwise. I was just confused because I could swear it used to, hence this issue being opened and hence the foreground PR #726 I landed to fix it, although that also fixed other issues.

The reason I came back to this was the discussion about identifying dialogs which originally started in https://github.com/jcsteh/osara/issues/610#issuecomment-983081356.
