### ISSUE TITLE
Incorrect toggle button behavior via the OSARA FX parameters window

### ISSUE THREAD

**Issue by Flameborn** [jcsteh/osara#615]
I am trying to activate a VST3 plugin's toggle button via OSARA, shown as a slider through Reaper's track FX window when the UI is not visible. In OSARA's FX Parameters window,I see the two possible values (On/Off), however, setting the parameter to On does not seem to toggle the button to the on state, at least the plugin does not seem to do anything other than resetting the parameter state to Off after a few seconds.

I'm in touch with the support of the plugin developers, and they are able to toggle the button through Reaper's FX window when the automatable parameters are shown.

According to Reaper, the Off state's value is 50000.0%, OSARA shows 0.0% and 1.0% for Off/On respectively.

Is it possible that OSARA normalizes this value between 0.0% and 100.0% and an incorrect value is set for the On state of the parameter?

This currently affects Sonible's Smartcomp, though their other Smart plugins may produce similar results.

**Comment by jcsteh** [comment]
Where do you see 50000.0? If you tab to the edit field in the OSARA Parameters dialog, what value do you see?

OSARA has no way of knowing when something is a toggle. It handles all params the same way. It increments the raw value, gets the formatted text value and keeps doing that until the formatted text value changes. If that isn't working, it suggests the plugin incorrectly reports a formatted value for a given raw value. The raw value is what you see in the edit field after the slider.

OSARA does query the minimum, maximum and step values from REAPER, so if the plugin really does support raw values like 50000, OSARA should be trying those.

Finally, do you get a different result if you use home/end to adjust the slider instead of the arrow keys? What raw value do you get then?

**Comment by Flameborn** [comment]
> Where do you see 50000.0?
If I bring up the track FX window, then press the UI button to display the automatable parameters instead of the plugin's interface. NVDA via object navigation among other things sees the parameter control, usually a slider, and a value, which in this case is 50000.0%. There is no change if I toggle the parameter via OSARA's FX Parameters window.

> If you tab to the edit field in the OSARA Parameters dialog, what value do you see?
0.0% and 1.0% for off/on respectively.

> Finally, do you get a different result if you use home/end to adjust the slider instead of the arrow keys? What raw value do you get then?
OSARA in both cases reports the state change, e.g. from off to on. If I use the left/right arrow keys, the plugin resets the parameter state to off, but nothing else happens. If I use the home/end keys, the parameter state remains on the on value.

According to the support team, when this parameter's value is changed via Reaper, the plugin modifies other parameters as expected, i.e. registers that the button was toggled. I unfortunately can't verify this, nor look at what value OSARA sees when the parameter is toggled via Reaper, as there is currently no way to modify the automatable parameters on Windows without OSARA to my knowledge.

**Comment by Flameborn** [comment]
An update: It looks like if the parameter is changed via the home/end keys, the button state on the plugin UI changes as well, but for some reason the plugin does not work as expected. This is likely something they have to look into.

I'm assuming the different behavior with the arrow keys is a plugin issue as well, possibly an incorrect report of raw value to formatted text as you suggested.

Thank you very much for your explanation. I'm closing this for now.
