### ISSUE TITLE
with the new Reaper action: "Edit: Insert note at edit cursor (no advance edit cursor)" there is no note feedback

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#638]
I'm rehearsing this new 6.44 action in piano roll and it would be nice if when we insert a note without moving the edit cursor, the inserted note has sonic feedback. Normally when we insert a note it goes forward in the grid and the inserted note sounds.
It would make midi writing even faster.
Greetings!

**Comment by MatejGolian** [comment]
Nice request @Lo-lo78! Furthermore, @ScottChesworth, I think it would be useful to have this action available in the keymap by default. What are your thoughts? My suggestion would be to differentiate between I and Shift + I so that pressing Shift + I would advance the cursor, while pressing the I key on its own wouldn't. Inserting notes without advancing the cursor is the simpler task of the two, that's why I think not adding modifier keys to it makes more sense. I don't have any suggestions for the numpad variants of these shortcuts.

**Comment by ScottChesworth** [comment]
Yep, "add Shift if you want the edit cursor to shift" makes that easy to remember. It's gonna break muscle memory for our beatmaker folks who sequence drums on the grid, but I'm sure they'll endure.
I'll have a look at getting feedback and mapping done later tonight. Not sure how note previews are handled, Cockos might need to provide that part of the equation.

**Comment by jcsteh** [comment]
Note preview is handled inconsistently. REAPER does preview for some actions - I thought insertion was one of them - but OSARA also has code to handle previews itself for actions where REAPER doesn't. I wonder why REAPER chose not to do preview for this new action. Or maybe I'm wrong and OSARA handles preview for insertion.

**Comment by jcsteh** [comment]
I'm wrong: OSARA handles preview for insertion always.

**Comment by Lo-lo78** [comment]
Yes, when you have to choose a note you hear the preview, but with this 
action, if you insert it, it does not give any feedback.

**Comment by Lo-lo78** [comment]
It's ok, with the latest OSARA snapshot it works.

Sorry, I didn't download the latest version of OSARA.

🙂

**Comment by jcsteh** [comment]
Note that I did not change the key map here. That will need to be handled separately.

**Comment by Lo-lo78** [comment]
Hey James, on Github I removed the messages because I tried the action 
and it works.

I don't know if it's the changes in the piano roll but I was amazed that 
it now works perfectly.

I put this action in the keymap.

Thank you!

👍

**Comment by jcsteh** [comment]
It works because I fixed it a few days ago. :)
