### ISSUE TITLE
Key map changes for February 2022

### ISSUE THREAD

**Issue by RDMurray** [jcsteh/osara#667]
This is a list of issues for the February Key map update, due to be merged on 2022-02-28.

# Test Builds
Please report any inaccuracies, problems or ideas in the comments below before the end of Feb.
[Windows](https://ci.appveyor.com/api/buildjobs/n88cjcv9a91s4e3d/artifacts/installer/osara_pr685-843,1c22f409.exe)
[Mac](https://ci.appveyor.com/api/buildjobs/24g4k3cd0yaxw514/artifacts/installer/osara_pr685-843,1c22f409.dmg)

### Main section
- FX: Toggle delta solo for last focused FX: Shift+F6 (replaces Track: Toggle solo for master track)
- FX: Clear delta solo for all project FX: Alt+Shift+F6
- Scrub: Toggle looped-segment scrub at edit cursor: / (replaces View: Move edit cursor to play cursor)
- OSARA: Report regions, last project marker and items on selected tracks at current position: Control+Shift+R
- Time selection: Swap left edge of time selection to next transient in items: Control+Shift+[
- Time selection: Extend time selection to next transient in items: Control+Shift+]
- OSARA: About: Control+F1
- Help: About Reaper: F1
### Media Explorer section
- Preview: decrease volume by 1 dB: Alt+Shift+DownArrow
- Preview: increase volume by 1 dB: Alt+Shift+UpArrow
### MIDI Editor section (also mirrored in MIDI Event List Editor section where available)
- Edit: Insert note at edit cursor (no advance edit cursor): I and Numpad5
- Edit: Insert note at edit cursor: Shift+I and Shift+Numpad5
- Edit: Toggle selection of all CC events under selected notes: C
- Navigate: Move edit cursor to start of selected events: Control+Shift+Home
- Navigate: Move edit cursor to end of selected events: Control+Shift+End

## Tasks
- [x] #664
- [x] #665
- [x] #430
- [x] #638 
- [x] #574
- [x] #672 
- [x] #632 
- [x] #693

**Comment by MatejGolian** [comment]
I guess mainly to @ScottChesworth, do the keyboard bindings related to #574 and #638 have a chance of making it for this round?
I ask because we two kind of arrived at an agreement, but I don't know what others had to say about it.

The shortcuts we talked about were
- Edit: Insert note at edit cursor (no advance edit cursor): I
- Edit: Insert note at edit cursor: Shift+I
- Edit: Toggle selection of all CC events under selected notes: C
I originally suggested a different action for number 3, but @RDMurray had a better idea.

**Comment by ScottChesworth** [comment]
> do the keyboard bindings related to #574 and #638 have a chance of making it for this round?
> 
Yep. I've added to the task list and proposed changes in top comment.
> we two kind of arrived at an agreement, but I don't know what others had to say about it.
> 
Everything that others have had to say about it so far is here on GitHub in the related issues. Just FYI, we're trying to migrate key map activity over here now, the intent being that discussions will be more open, updates will be less sporadic, better organized and easier to track. An overhaul of the process was needed because the key map was lagging behind progress that's been made in other areas. We'll be testing proposed changes and aiming for key map revisions to go live at the end of each month. Whether all members of The Key Map Consortium WhatsApp group will choose to adapt is yet to be seen. If the old guard don't make it, we might have lower numbers indicating consensuses for a while, just until new contributors start getting involved.

**Comment by MatejGolian** [comment]
Thanks Scott.
Hope I'm not too pushy, but since this is the time for submitting proposals, could you also consider my requests in #585? No Osara feedback necessary.
The things I suggested there were
- Navigate: Move edit cursor to start of selected events: CTRL+Shift+Home
- Navigate: Move edit cursor to end of selected events: CTRL+Shift+End
I think that there would be no harm in adding these since these key combinations are free and apart from that I think that they are fairly intuitive. Honestly, I can't think of another MIDI editor scenario where these key combinations would make sense and if it objectively is so, adding them should not pose much of a dilemma.
I have no other keymap requests for the time being. That being said, I believe that there are still a couple of issues open with keymap stuff.

**Comment by RDMurray** [comment]
@MatejGolian  I have added these to the proposed changes above.  Is that ok with everyone else?

**Comment by ScottChesworth** [comment]
> Is that ok with everyone else?
> 
Looking good to me. Thanks, I forgot to come back to it.

**Comment by RDMurray** [comment]
There is a keymap related discussion int #307  about the actions for changing item pitch and rate.  In short, I am proposing that we should get rid of the "clear preserve pitch" variants and add a key bound to "Item properties: Toggle take preserve pitch".

**Comment by MatejGolian** [comment]
> @MatejGolian I have added these to the proposed changes above.
Thanks a lot. Just for the record, as I wrote before, I don't think having Osara feedback is really necessary for these actions, but should they get incorporated into the keymap and should someone find voice feedback useful in this case, I won't have any objections.

**Comment by leonardder** [comment]
Could https://github.com/jcsteh/osara/issues/632 be considered for februari as well?

**Comment by ScottChesworth** [comment]
We've reached the middle of the month and I've just made sure the top comment is up to date. My partner will not be best pleased with a key map to test for Valentine's day, so unless anyone else gets to it first, I'll post test builds with the top comment incorporated tomorrow.
Alternatively, I still haven't had chance to wade through the hundred or so messages that need listening to from the WhatsApp group and we don't seem to be getting any input from its members yet either, so perhaps we should do a single week of testing this month?
Thoughts @RDMurray , @jcsteh?

**Comment by jcsteh** [comment]
I'm not sure I follow the argument for a single week of testing given the
lack of input from the Whatsapp group. Are you thinking there might be more
critical feedback there we need to take into account? Wouldn't two weeks
give people a chance to test this in daily usage and thus enable them to
provide more constructive feedback?

**Comment by ScottChesworth** [comment]
> Are you thinking there might be more critical feedback there we need to take into account?
> 
Yep, that. I'm presuming they were batting useful stuff around, just haven't had time to summarize the conclusions.

**Comment by jcsteh** [comment]
I don't have a useful opinion. Commenting here really isn't that hard -
it's a simple text box with a simple button - so I'm inclined to say that
if people have strong opinions they want considered, they should make the
effort to provide them here. That said, I get that's not how things work in
this community and you want to be more inclusive than that... which is why
this probably isn't a useful opinion. :)

**Comment by RDMurray** [comment]
I think we could go with what we have for now and leave going through the Whatsapp messages for march.  

Btw, the IOS app for Github is also accessible; I'm using it right now.

**Comment by ScottChesworth** [comment]
Test builds are up, see top comment. @RDMurray, I restructured a bit, moved installers and changes above tasks, hope you don't mind.
I've left the task for adjusting volume of previews in the Media Explorer unchecked because we still need feedback for that, but the actions are already mapped.

**Comment by RDMurray** [comment]
I don't think we will be able to get feedback going for the media explorer any time soon.  We can leave the issue open, but this is just about the keymap, so it should probably be checked.

**Comment by ScottChesworth** [comment]
> I don't think we will be able to get feedback going for the media explorer any time soon.
> 
I took a tentative poke at that earlier and couldn't for the life of me figure out how to get it happening, relieved to read this lol.

**Comment by ScottChesworth** [comment]
The crash fix for Mac Peak Watcher is now included in the test build up top.

**Comment by MatejGolian** [comment]
@ScottChesworth, thank you and good job! I think that now it's as good as it gets with those 2 actions.
BTW, I think I have discovered a bug related to note deselection. It has nothing to do with the workings of those 2 actions per say, but who knows - it could have been the reason why your note selections sometimes did not end up being as you expected. I will do some more testing and likely create a new issue a bit later.

**Comment by RDMurray** [comment]
I'm working on the media explorer feedback in #684 .  No idea if it works on Mac.  If someone could test the [Build](https://ci.appveyor.com/api/buildjobs/6dqtkierq5g3xhan/artifacts/installer/osara_pr684-842,09761994.dmg), that would be great.  It currently only supports the 1 dB actions.

I do have a mac VM here, but haven't used it for ages, so would have to learn to use voiceover again :)

**Comment by ScottChesworth** [comment]
You're bloomin' marvelous @RDMurray! Something I'm not clear on yet, how would I merge #684 into our test builds above? Suppose I could yank local copies of those branches, smoosh them together and push, but is there an easier browser-based way that I'm missing?

**Comment by RDMurray** [comment]
The builds are ready @ScottChesworth , I'll update the first comment.

**Comment by ScottChesworth** [comment]
Oops, already done it before I saw this.

**Comment by ScottChesworth** [comment]
I update top comments like people leave @mattymc2's gigs. Hastily, sometimes with scant disregard for those around me. :)

**Comment by ScottChesworth** [comment]
It's merge day folks! Consider this your final call for feedback.

**Comment by RDMurray** [comment]
There's just the about action to be added.  I can't imagine that being controversial.

**Comment by ScottChesworth** [comment]
Yah, I'll hop over to Mac and add that before merging.
