### ISSUE TITLE
Key map changes for March 2022

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#696]
This is a list of changes and additions in the March 2022 key map update.

## Main Section Additions and Changes:
- Item properties: Normalize items (peak/RMS/LUFS): Control+Shift+N (replaces "Item properties: Normalize items to +0dB peak" for extra flexibility)
- Track: Toggle track pre-FX volume envelope visible: Control+Alt+Shift+V (replaces "SWS: Save list of open projects")
- Track: Toggle track pre-FX pan envelope visible: Control+Alt+Shift+P (replaces duplicate mapping of "OSARA: Configuration")
- Track: Toggle track mute envelope visible: Control+Alt+F5

## Media Explorer Additions and Changes:
- Autoplay: Toggle on/off: Alt+A (moved for parity with new keystrokes to access toolbar controls)
- Start on bar: Toggle on/off: Alt+S
- Tempo match: Toggle on/off: Alt+T
- Tempo match: x2: Alt+2
- Tempo match: /2: Alt+/
- Preview: Play/pause: Space (replaces play/stop, thus freeing up Control+Space to handle multi-selection in the list box)
- Preview: Rewind to start: Control+Home
- Preview: Play reversed: Shift+LeftArrow
- Preview: adjust pitch by -1 semitones: Shift+9
- Preview: adjust pitch by +1 semitones: Shift+0
- Preview: reset pitch: Control+Backspace
- Preview random file in current folder/database: Control+Shift+R
- Browser: Go to shortcut 1 through shortcut 10: Control+1 through Control+0
- Browser: Go to previous shortcut in list: Control+-
- Browser: Go to next shortcut in list: Control+=
- Create new folder: Control+Shift+N
- Edit: Rename file: F2
- File: Delete (recycle): Delete
- Media: Insert in selected media items as new take: Control+Enter
- Media: Insert on a new track: Alt+Enter
- Media: Insert into active sample player: Shift+Enter
- Media: Insert into sample player on a new track: Alt+Shift+Enter
- Set as favorite: Control+D
- Dock Media Explorer in Docker: Shift+D

## MIDI Editor Additions:
- It's now possible to move to previous/next marker using Semicolon and Apostrophe, matching TCP behaviour

**Comment by KeithRempel** [comment]
Consider binding lower case e to the action Track: Insert/show ReaEQ (track EQ)

I find this to be a nice time saver.

Not sure how widely used the envelope processor is, but I suspect more people would get mileage out of a quick button for ReaEQ.

As always, thanks to all for the ongoing development.

**Comment by MatejGolian** [comment]
@KeithRempel, I personally support this idea.

**Comment by ElCrackLoko** [comment]
Isn't there a place where you can see all the key commands that have been assigned in real time to date?
I was thinking of the list of actions, but it would be better to see them in a file.

**Comment by ScottChesworth** [comment]
> Isn't there a place where you can see all the key commands that have been assigned in real time to date?
> 
Yeah, hit Shift+F1. The full key map will load in your default browser.

**Comment by ScottChesworth** [comment]
Apologies for the lack of action this month folks. Somehow I didn't get notifications of the first couple of comments. I'll be back over the weekend to get some movement started. Guess we're just looking at a single week of testing this month though.

**Comment by ScottChesworth** [comment]
> Consider binding lower case e to the action Track: Insert/show ReaEQ (track EQ)
> 
As things stand, we wouldn't be able to do this for many plug-ins without significant reorganization. Is EQ an exception? Users can already define those shortcuts for themselves and in doing so, they can choose whichever plug-ins they use.

**Comment by ElCrackLoko** [comment]
What would be useful would be to add the parameter to automate the gain in PreFX, (preFX volume) since it does not depend on any Plugin, but rather on Reaper itself. And if we want to get cool, we can also add the PreFX panorama, although I don't use it. It could be well thought of reorganizing these last 2 commands for PreFX so that they coincide with the PostFX volume and pan commands. Although I don't understand why in the Reaper context menu (Control+Shift+F10, Envelope submenu, they are duplicated, one with "Active" and the other with "Visible", if in the end both do the same) Now, something that does It would be useful for those of us who compose RAP, to add, if possible, an automation parameter for the Mute, to make that extreme cut effect in certain parts.

**Comment by ScottChesworth** [comment]
Please include suggestions for shortcuts

**Comment by ElCrackLoko** [comment]
For PreFX panning it could be Control+Shift+Alt+P (replacing Osara's repeated config action) and for preFX volume it could be Control+Shift+Alt+G, I would have liked them to match the volume and pan in postFX but Control+Shift+Alt+V already has a default action with SWS which is to save the list of open projects, there it is up to you to maybe take my suggestion to move the SWS command to Control+Shift+Alt+ G to free up V for Volume PreFX or replace the SWS command, that's up to you. For Mute you could assign Alt+M

**Comment by ScottChesworth** [comment]
I don't want to bind anything to Alt+M because that would block access to the Item top menu (and perhaps more importantly, I argued for months to get all of those menus unblocked in the 2020 overhaul lol). Mute could go on Control+Alt+F5 though.
I think the SWS action on Control+Alt+Shift+V can go, volume pre-fx is more useful. Ditto that variant of pan, we're only replacing a duplicated assignment so that's not a big deal IMO.
We'll need to implement feedback for all of this. Leave it with me, I'll try to get that going soon.

**Comment by pitermach** [comment]
I proposed some new Media Explorer keys for some of the recently added actions in #722

**Comment by ptorpey** [comment]
Most of the hotkeys for moving by bars/beats are assigned to variants of PageUp/PageDown.  However two of them are assigned to Home/End.  

 

Here are the hotkeys currently assigned to the PageUp/PageDown keys:


control+PageUp = Move edit cursor back one beat
Control+PageDown = Move edit cursor forward one beat
PageUp = Move edit cursor back one measure
PageDown = Move edit cursor forward one measure

 

Meanwhile the following bar/beat hotkeys are not assigned to variants of PageUp/PageDown:
Alt+Home = Move edit cursor to start of current measure
Alt+End = Move edit cursor to start of next measure

 

While the next two hotkeys assigned to variants of PageUp/PageDown have nothing to do with moving by bar/beat:
Alt+PageDown = SWS: Select nearest previous folder
Alt+PageUp = SWS: Select nearest next folder

 

I wonder if it makes sense to swap the Alt+Home and Alt+End hotkey assignments with the with the Alt+PageUp and Alt+PageDown assignments so that we have:

 

Alt+end = SWS: Select nearest previous folder
Alt+Home = SWS: Select nearest next folder

Alt+PageUp = Move edit cursor to start of current measure
Alt+PageDown = Move edit cursor to start of next measure



This way all of the bar/beat movement hotkeys are assigned to variants of PageUp/PageDown.  

 

The negative of doing this is that old users are probably used to this set of assignments now.  On the other hand, assigning all bar/beat movement hotkeys like these to PageUp/Pagedown is probably more logically consistent and easier for newer users to assimilate.  I’m guessing that the reason this always throws me is that, as we discussed in another thread, I often work in hours/minutes/seconds format so the bar/beat navigation hotkeys aren’t burned into my muscle memory and I’m always wondering where the “move to start of next/previous bar” hotkey is.

 

--Pete

**Comment by ElCrackLoko** [comment]
Wow, but what a great idea brother had to move the Alt+Home and Alt+End assignments to go to the beginning and end of bars to pageUP and page Down! I couldn't agree with you more @ptorpey I've been confused several times about moving to the beginning and end of bars using Alt+ Page Up and Alt+ Page Down, seriously.

**Comment by jcsteh** [comment]
I'm with Scott on this one, which unfortunately leaves us with a bit of a stalemate. I guess we'll have to see where others land.

**Comment by ElCrackLoko** [comment]
I think that if you can do what @ptorpey suggested, which I think is quite right, what more than better. But if you can't, then nothing happens either. Although in my opinion, everything related to a couple of keys would be better, like going to the beginning and end of bars with Alt+ Backspace and Alt+ Page Forward respectively.
Changing the subject and talking about commands, we have 2 repeated commands that this has bothered me a lot of times as a private user jajajaja, and it is the W to go to the beginning of the project. I mean, here's the Control+ Home command to do that, you could leave the W with another more useful action that doesn't hurt the edit cursor, I'll explain my scenario.
I'm on my Midi controller, ready, with my left hand ready to play the low notes and I quickly position myself blindly, with my right hand on the keyboard of my Laptop, on what I believe is the letter R for recording.
With the idea of ​​my composition in mind and before I forget, I press R, and it's not R, but W.
I have to release my left hand from my controller and place the edit cursor where I wanted to start recording, again; I know that my laptop is the one with the problem and many probably consider me an idiot jajajaja, but I am guided by the notch or high relief that the keyboards have and I just have one of those in the letter S, those that are the same as the J and F.
My silly suggestion, perhaps, would be to make better use of it by assigning something better to the W, if possible. Sure I could remap the W by removing that action, but I'd rather be the same as everyone else with Osara's original KeyMap.

**Comment by MatejGolian** [comment]
I agree that freeing up the W key is a good idea - and not just in the MIDI editor. It feels like an unnecessary and unintuitive duplicate. I don't currently have any ideas what that key could be used for instead either, but like @ElCrackLoko I too believe that someone will come up with a suggestion sooner or later. And if you don't feel like removing it right away, could we keep it as a potential candidate for something else for the future?

**Comment by ScottChesworth** [comment]
Top comment now has test builds with all mappings complete and most new feedback in place. I made a few executive calls in the Media Explorer, also through in some extras beyond what's been suggested in issues. Hope you likey. Please test the heck out of things, I'd still like to merge on schedule ideally. Apologies for the shorter than usual testing period, I'll try not to make a habit of cramming like this.

**Comment by ScottChesworth** [comment]
Hey @RDMurray, any chance you'll have time to rescue me with the feedback that's yet to be completed? I tried, but made a mess. :(

**Comment by ScottChesworth** [comment]
> I agree that freeing up the W key is a good idea - and not just in the MIDI editor. If you don't feel like removing it right away, could we keep it as a potential candidate for something else for the future?
> 
Sure. Come at me with a suggested replacement next month.

**Comment by RDMurray** [comment]
@ScottChesworth The envelope toggles work fine when bound to cmdToggleTrackEnvelope.  Should I push the changes to your mar22keymap branch?

**Comment by RDMurray** [comment]
@ScottChesworth  never mind, just saw your comment on #732 .

**Comment by ScottChesworth** [comment]
I've just done the same thing here following Jamie's advice. Will update the PR and the test builds in the top comment shortly.

**Comment by ScottChesworth** [comment]
Oh, never mind, just saw your other comment. Argh, feedback loop.

**Comment by ScottChesworth** [comment]
New test builds up top. Do your worst.

**Comment by ScottChesworth** [comment]
One last issue I'd like to get squared away this month. Snowman brought it to my attention that we currently use Control+Space for play/pause in Media Explorer. However, that doesn't work when focus is in the list box, it gets overridden by multi-selection.
I think we should reassign Space to play/pause, and remove play/stop. If all you want is to stop the previewing, the behaviour will appear unchanged. If you want to restart the preview from the beginning, then hitting Control+Home does that.
Any objections?

**Comment by pitermach** [comment]
The keymap is working great here, I can confirm the Mac matches up with Windows this time ☺️

Re: CTRL+Space, no objections from me, it's actually how I had it set up in my personal keymap. I also tried it on Mac and it doesn't work right here either with the key getting past to the main Window and doing a play/pause on the project rather than the media explorer.

**Comment by ScottChesworth** [comment]
Merge day is upon us. Final call for feedback from anyone who's been using the test builds.

**Comment by ScottChesworth** [comment]
Aaaaand the merge commences. Props to everyone who got involved.
Key map activity during April will be tracked using #736.
