### ISSUE TITLE
The new osara causes the function of Ctrl+up and down arrows to edit custom actions to fail

### ISSUE THREAD

**Issue by cn-peter** [jcsteh/osara#704]
Hello everyone.
The new version of osara cannot use Ctrl + up and down arrows to move the selected item when editing custom actions.
Ctrl + up and down arrows are built-in hotkeys in reaper.
Wondering if it's possible to exclude editing the list of custom actions?
but. The new features are nice.

I am using the simplified Chinese version of win11
I use automatic translation of.

**Comment by RDMurray** [comment]
Sorry, this is caused by pr #698 
I didn't know Reaper had this shortcut.  It's annoying that they repurposed a standard listview shortcut for it.  I will see what I can do.  

Is the shortcut dialog the only listview where we need multiple selection to work?

**Comment by c469591** [comment]
hi, I'm a friend of peter's.
I am using traditional Chinese windows 10.
I would like to add that I think the author may have misunderstood.
The current problem is that some people want to use ctrl+up or ctrl+down to move different actions in f4 where they want to edit custom actions.
Of course, if there are other shortcuts to achieve the same purpose can also be.
For example, my custom shortcut consists of three actions, a, b, and c,
If I want to add an action before the a action, I will not be able to complete it.
I can't use the shortcut key to move my new action forward because my new action will be after a, b, and c. I can't use the shortcut key to move my new action forward.
The only solution is to re-edit a custom shortcut and add it in order from the first action, which will be very troublesome.
So peter would like to ask if there is a solution to this problem that we are currently encountering.
Thank you!

**Comment by cn-peter** [comment]
yes. CTRL + up and down arrows are currently supported in only two places.
1. Customize the second list of the editing window
2. FX add the custom folder of the window to move up and down

Thanks for reading

**Comment by cary-rowen** [comment]
Hi @RDMurray 

Yes, I tried using NVDA to move the mouse to the current navigator object to sort the list with an emulated mouse, however I found that the NVDA mouse position was wrong. There doesn't seem to be any other solution for this at the moment.

Cary
Cheers

**Comment by RDMurray** [comment]
> yes. CTRL + up and down arrows are currently supported in only two places.
> 
>     1. Customize the second list of the editing window
> 
>     2. FX add the custom folder of the window to move up and down

I don't think this bug should affect the fx browser because it is a treeview.  

@jcsteh what do you think is the best way to detect the second list in the edit custom action dialog? The window control ID is 1322.  That doesn't appear anywhere in the (incomplete) list at [ChildWindowIDs and Window-ClassNames in Reaper](https://raw.githubusercontent.com/mespotine/ultraschall-and-reaper-docs/master/Docs/Reaper-Windows-ChildIDs.txt) 

Do you think it would be okay to go on the ID?

**Comment by RDMurray** [comment]
@ScottChesworth Is this shortcut for reordering lists widely known?  I could only find it in the Reaper changelog.  If not, do you think Cockos might be open to changing it to something that doesn't clash with a standard listview shortcut?

**Comment by c469591** [comment]
hi
osara_2022.1pre-864
This version I can use ctrl+ up and down to move the second list of custom signs,
but
osara_2022.1pre-867
I can no longer use ctrl+ to move the same list up and down,
Is this a bug, or is it a change made in the new version?

**Comment by cary-rowen** [comment]
Hi @c469591 

Exactly this is a regression.

Cheers

**Comment by RDMurray** [comment]
@c469591  It's a bug caused by a change I made to allow ctrl+up/down to work for multiple selection in the action list.  I didn't know at the time that Cockos had assigned the same keys to reorder the list in the custom action editor.

There will be a solution soon, I'm just trying to figure out the best way to do it.

**Comment by c469591** [comment]
thanks RDMurray
So if I want to use shift+alt+directional keys to adjust the order, is this the work of osara or do I have to use the reaper?
Is this osara's job or do I need to key billion reaper to make changes?

So if I want to use shift+alt+direction keys to adjust the order, is this osara's job or should I type reaper?
Is this osara's job or do I have to ask reaper to make changes?

**Comment by RDMurray** [comment]
We could also single out the custom action dialog, since afaik it is the only listview that allows reordering in this way and Cockos wouldn't have to do anything.

**Comment by jcsteh** [comment]
I don't think there's a clear convention for this, no. Ideally, it wouldn't
override a standard convention, but I honestly don't think this is worth
pursuing with Cockos.

That said, it might be tricky to identify the Custom Action dialog unless
the list view has a control id which just happens not to conflict with some
other list view. We can hope.

**Comment by ScottChesworth** [comment]
@RDMurray. Can you try a fix using the window control ID as above? If you don't have time, feel free to remove the assignment.

**Comment by RDMurray** [comment]
Yes no problem. Should only take a couple of minutes. I'll do it this morning.￼

**Comment by jcsteh** [comment]
Fixed in #710. @RDMurray , just FYI, you have to do "fixes #xxx". If you put a colon in there (like "fixes: #xxx"), GitHub won't recognise it.

**Comment by jcsteh** [comment]
Ignore that. Looks like it did close and I thought it was open for some reason. Durp.
