### ISSUE TITLE
Add Feedback For View: Toggle snap to grid In The MIDI Editor

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#708]
Please, add feedback for the MIDI editor action 'View: Toggle snap to grid'. The action ID is 1014.
Making sure this action is in the desired state is useful, when you want to split notes, but you want to make sure that they get split exactly where your cursor is and not right on the grid. There may be other scenarios where this info comes in handy, but this is my use case.

**Comment by ScottChesworth** [comment]
This action doesn't show its state in the actions list. Can we report its state? If so, I don't know how.

**Comment by MatejGolian** [comment]
What exactly does it mean that it doesn't show its state?
I ask because, when I open the actions list, I either see
'Alt+S; View: Toggle snap to grid; on'
or
'Alt+S; View: Toggle snap to grid; off'.
I'm not arguing, I'd just like to understand the issue here.

**Comment by MatejGolian** [comment]
@RDMurray, if I get a vote, I'm in on your suggestion. Provided that it's not that hard to implement, of course. Two questions come to mind though:
1. Out of curiosity, I imagine that your solution would only really make sense in case of actions where reporting whether they are on or off is sufficient. How difficult is it to find out if a given action is just a simple on/off one? If it's possible to make all these actions talk, so to speak, without too much hassle, I think having it the way you propose is way better than doing it individually for each requested action, even if this could theoretically result in some messages being grammatically incorrect.
2. If we take my request as an example, what would the feedback be? "snap to grid on" and "snap to grid off"? If so, that would be great.

**Comment by pitermach** [comment]
I like this idea, though if it gets implemented there should be a place in code to exclude actions if something gets too talkative. IE "Toggle loop segment scrub at edit cursor" is something you wouldn't want announced, but it's also the only one I can think of off the top of my head hence the suggestion.

**Comment by jcsteh** [comment]
> Wouldn't it be a better idea to have feedback for every togglable action rather than implementing them one by one? It might result in slightly strange grammar, but it would be quite a big increase in accessibility without affecting existing functionality.

While I understand and support the idea of doing less work for more accessibility, this idea worries me a lot. Even actions as simple as play and pause are toggle actions and there are a whole bunch more. We'd have to exclude all of those to avoid stuff like "pause off" and "play on". And there are actions like the aforementioned loop segment scrubbing toggle that probably shouldn't report anything, so those would need excluding too. I think there'd be a lot of actions we'd need to exclude and the ones remaining would often not provide the most effective feedback. There'd also be a period of annoying users while we figure out which actions need to be excluded, since I doubt we'll get them all on a first pass.

**Comment by ScottChesworth** [comment]
I wonder if there's a middle ground though? Bear with this vague notion because I don't know how @RDMurray is thinking of reporting all toggle actions with catchall code, but I wonder if there could be some sort of thing implemented that just reports on or off if a toggle action is run that we don't already have specific feedback in place for?
That way, users would have state information, but we'd avoid bombarding them with superfluous reports and/or weird grammar.

**Comment by jcsteh** [comment]
Yeah, I realised he was thinking along those lines. I was originally
thinking play, stop, etc. didn't have action bindings - I thought they were
only handled via the surface transport code - but it seems they actually
are bound after all. Even that aside, this still worries me.

I guess we can try it and see how it goes, but I worry that we won't get
enough feedback here to know whether it's going to be more problematic than
it's worth.

The other thing is that there are some toggle actions that refuse to change
state if the state change is invalid; e.g. trying to pause when you're
already paused. To avoid a situation where we confuse the user into
thinking they changed something when they didn't, we should probably report
nothing if the toggle doesn't work. That is, we have to check the state
both pre and post action.

**Comment by ScottChesworth** [comment]
Well, it's possible to instigate more feedback than we typically get here if needed. One easy way would be for me to stream using a test build, with a few breaks for feedback. I don't stream often, but decent numbers usually show up when I've done it in the past, and previous recordings have all gotten a good amount of downloads too. that would be a good way to gauge what the reception is likely to be. We could put a test build out on the support channels and have a specific thread on RWP for folks to report any actions they use that shouldn't speak. Assuming silencing actions would be reusable code, I could probably cope with fielding the initial rush of exceptions until we've knocked off the sharp edges.

**Comment by jcsteh** [comment]
It's less about users knowing what it's like and more about users with
different usage patterns who discover problematic cases. So, a test build
distributed via RWP would probably be more useful than a test stream.

Anyway, despite my reservations, I guess I'm happy for us to give this a
shot and see where it lands. With toggle actions, the likelihood of us
reporting a change when no change was made is much lower than with normal
actions, so that at least is much less of a concern here.
