### ISSUE TITLE
When folders are multi-level

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#763]
Hello,
I wanted to report that I have had some problems with the folders.
I often do projects that have folders and sub folders and I don't understand when I close the first level or second or third level folder.
I give an example:

traccia 1 1 open folder 
traccia 2
traccia 3
traccia quattro open folder 
traccia 5 end of folder
traccia 6
traccia 7
traccia 8 end of folder

The problem is that if the second folder contained in the main folder is updated with a new track and closes the folder, I don't know if it does so with the first or second level one.
I always have to rehearse.
Is it possible to number the levels of the folders?
For instance:

traccia 1 1 open folder 1
traccia 2
traccia 3
traccia quattro open folder 2 
traccia 5 end of folder 2
traccia 6
traccia 7
traccia 8 end of folder 1

It is very useful when you have very complex projects; if for some reason you make a mistake you risk that the routing is all wrong.
If you find a system with OSARA to distinguish folders and sub folders that would be great!

Greetings!

**Comment by RDMurray** [comment]
To add to this, there is currently no easy way to know which folder is closed by an end of folder track. To see what I mean, create 3 open folder tracks so that you have a folder within a folder within a folder. Then create another track and press Shift+enter repeatedly. notice that there are three options for end of folder, depending on which folder is being ended. We should have appropriate feedback for this.

Let's discuss the Ux for this, as it doesn't seem obvious how to make it intuitive.

I am imagining something like a tree view, where folder level is spoken for everything except top level tracks. It could alternatively work like indentation in NVDA where the level is only spoken when it changes.

**Comment by ScottChesworth** [comment]
I'm not familiar enough with the API to know how much information you can obtain about nesting, is there a way to ascertane that reliably?
If so, here's what I'd propose re reporting:
1. When hitting Shift+Enter to set folder state and navigating the track list, OSARA prepends the word "folder" as it does now, and "nested folder" where relevant.
2. When hitting Shift+Enter to set closure, OSARA reports "end of folder" as per usual for non-nested, then "end of first nested folder", "end of second nested folder" etc.

To report nesting levels when navigating the track list seems like it'd add too much feedback before hearing the track name, hence the suggestion that it's only reported when setting closure.

Thoughts?

**Comment by Lo-lo78** [comment]
@RDMurray 
Isn't it easier to represent it like this?
1 open folder 1
2 
3 
4 open folder 2
5 open folder 3
6 
7 end of folder 1
8

Then if I shift + enter in track 7 it cycles:
shift + enter, folder
shift + enter, end of folder 3
shift + enter, end of folder 2
shift + enter, end of folder 1
shift + enter, track

Then when you open a new folder in track 10, the numerical count starts again.

It is also interesting the representation in sub-folders as in the tree menus as the screen reader does.

**Comment by pitermach** [comment]
> To report nesting levels when navigating the track list seems like it'd add too much feedback before hearing the track name, hence the suggestion that it's only reported when setting closure.

I don't necessarily think so. When screen readers include level information for trees they usually do it at the end of an announcement, and if that were the case for Osara I don't think it would be too annoying.

So, assuming you had a track that was part of a folder I'm imagining an announcement like "3 kick 4 items folder level 1", where the level would increase if the track was nested in a subfolder.

Something else that might help here could be changing the "end of folder" announcements to also tell you the name of the folder that's ending, since the beginning of folder includes this info already and if you're in a lot of nested folders it might help orient yourself a bit easier.

**Comment by ScottChesworth** [comment]
Hmm, we need to tread carefully with these reports to make sure that there's clear distinction between folder nesting and track numbers though. Remember there's also the case to consider where track numbers are silenced in OSARA Config, but still reported if tracks/folders are unnamed.

**Comment by mattymc2** [comment]
+1 to this. If possible would be hugely helpful

**Comment by RDMurray** [comment]
Please test the build in #840  and give me feedback on the UX.

I tried the treeview-like idea first, but it felt clumsy with the level numbers.

In this one the track list could look something like:
* 1 open folder instruments
* 2 open folder strings
* 3 violin
* 4 cello end of folder 2 strings
* (...)
* 20 end of folder 1 instruments

Shift+enter reports the folder that is being closed. If report track numbers is disabled it reports the number instead when the folder doesn't have a name.

**Comment by RDMurray** [comment]
I updated it to report nested folder for folder tracks inside other folders. IMHO adding a number for nesting level is too verbose, and is more than 1 level of nesting really a common use case? 

 Please test the latest build in #840 and let me know what you think.

**Comment by Lo-lo78** [comment]
@RDMurray 
Yes my problem was with the end folder.
If you understand the end folder which folder it belongs to it is ok for me.

**Comment by Lo-lo78** [comment]
@RDMurray 
Perfetto!
Works well.
👍
