### ISSUE TITLE
Actions to toggle individual prefs-settings via shortcuts

### ISSUE THREAD

**Issue by mespotine** [jcsteh/osara#766]
I would like to ask for some toggle-actions, that allow turning on/off the various options you can currently only set in the Osara Preferences.

Some of these are helpful but I can imagine, that they might not be needed all the time, so an easy way to turn them off/on via shortcut would be very helpful.
It is possible to set it in the preferences, but to me, it feels a little tedious to have to always go into the preferences to toggle them. 
For instance "Report markers during playback" is something, you might not always be interested in, so if I could toggle this easily via shortcut, this would be awesome.

I have tried to turn them on/off in Lua by setting the extstates Osara uses, but this didn't work.

Having the settings toggleable via action would be awesome, especially if you could see the toggle-state in the actionlist as well.

**Comment by leejul** [comment]
I support this approach, I have been waiting for this possibility for a 
long time.
Thanks again guys for your work, I really appreciate it.

**Comment by jcsteh** [comment]
It's worth noting that all of the settings in OSARA preferences have keyboard shortcuts. For example, to toggle reporting of markers, you can press control+f12, alt+k, enter. I'm not questioning the validity of this request, just noting this her for anyone who may not be aware and also because given this, it's hard to justify giving this high priority.

**Comment by TimNoonanVoice** [comment]
I don't want to be troublesome, but do the shortcuts apply only to Windows, or also to Mac?

I've tried pressing various keys with and without modifiers, with no obvious success.

That said, I am not an advanced Reaper user, so find the dialog reasonably adequate.

Thanks
Tim


On 20 Aug 2022, at 9:35 am, James Teh ***@***.***> wrote:


It's worth noting that all of the settings in OSARA preferences have keyboard shortcuts. For example, to toggle reporting of markers, you can press control+f12, alt+k, enter. I'm not questioning the validity of this request, just noting this her for anyone who may not be aware and also because given this, it's hard to justify giving this high priority.

**Comment by ScottChesworth** [comment]
There's a strong use case that hasn't been mentioned in this thread yet, that being the ability to assign more control of OSARA's feedback to buttons on surfaces. If anyone could jot down an outline of how it would be best implemented, I'd gladly chip away at it, just not sure where to start.

**Comment by jcsteh** [comment]
Ah. It's possible SWELL (the Cockos GUI library) doesn't/can't expose them
on Mac.

That's a fair use case I hadn't considered, Scott. You could implement this
by adding a toggle action for every single config option, but config is
painful enough as it is right now without adding even more boilerplate. I
think the right solution here is some macros which can manage most of this
pain from a single set of config definitions, which would make config in
general a lot less painful. Thinking about implementing what I'm
considering hurts even my head, though...

**Comment by jcsteh** [comment]
I've started poking at this, but it'll likely take me a while and multiple attempts.

**Comment by mespotine** [comment]
No problem. Take your time and thanks for looking into this 🙂
