### ISSUE TITLE
We need a new build to be generated ASAP, snapshots not currently available from AppVeyor

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#774]
It's been over 30 days since snapshots were generated, so AppVeyor has axed those artifacts for Windows and Mac. I think the solution was a new build last time this happened, but I'm not 100% sure what that involves. Can someone either clue me in on what to do or take care of it? Cheers.

**Comment by jcsteh** [comment]
There were pending translation fixes, so I just synced those, which will generate a new build. I could also have forced a rebuild on AppVeyor if there hadn't been anything else to push.

**Comment by ScottChesworth** [comment]
Thanks man. Can I do either of those things from here if needed in future? Or if not me, can any other contributor who's more familiar? Just thinking about redundancy really, we could get caught out by a quiet period while you're away on holiday.

**Comment by jcsteh** [comment]
Ideally, I'd add you as a collaborator on AppVeyor so you could trigger a
re-build. Unfortunately, that seems non-trivial because OSARA is hosted
under my GitHub user rather than having its own GitHub organisation.
There's probably a way to do it, but I don't have time to figure it out
right now.

If worse came to the absolute worst, you could push an empty commit to
OSARA's master branch.
