### ISSUE TITLE
Is it possible to develop an OSARA action to insert a CC with the edit cursor in the Piano Roll?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#794]
Hello,
in the piano roll it is possible to move between the CCs. We can select a CC. We can move between the lanes of the CC but it is not possible to insert it as if it were a midi note.
Did I miss something?
Only in the Event List it is possible to insert a CC midi event and midi notes.
I did a custom action for the Piano Roll but it's not perfect:
kawa: MIDICC2_Insert_CentorCCValue_(atLastTouchedLane)
OSARA: Move to next CC
I would prefer OSARA to have a dedicated action to insert a CC after choosing it from the lanes.
We have the Reaper action:
Edit: Insert note at edit cursor
It would take an action like:
OSARA: Insert CC at edit cursor
Obviously in the MIDI Editor section which refers to the Piano Roll. As for the MIDI section, the Event List Editor already works well with Reaper.
Thank you and greetings!

**Comment by RDMurray** [comment]
Yes, I think this is necessary, and it is an accessibility feature since it is possible to do this with the mouse.

**Comment by MatejGolian** [comment]
I agree and I personally think that it would be better, if it would be handled by Reaper itself and not Osara.
All we need is an action like "Edit: Set or insert CC event at edit cursor".
I can open an FR for this over at the forum, I'll post the link here once I do so, so feel free to join me there.

**Comment by MatejGolian** [comment]
Here is the thread:
https://forum.cockos.com/showthread.php?p=2607227

**Comment by Lo-lo78** [comment]
> Here is the thread: https://forum.cockos.com/showthread.php?p=2607227

I tried to register but there is a graphic captcha and there is no audio captcha.
😢
Yes also in my opinion it is important to have an action to insert a cc in the piano roll.
If it was a Reaper action that would be great.

I'll register as soon as I can!
@MatejGolian 
Thank you for writing to Cockos.
👍

**Comment by Timtam** [comment]
Is there any progress on that front? We could write a simple dialog like this already, as the REAPER API already exposes functions to manually create events of sorts, so we could probably write up a small dialog or something ourselves if we need to.
The optimal situation IMO would be to switch with the previous/next lane commands not just between the CC lanes but between notes as well, having left and right to scroll through whatever is currently selected and have delete key and everything else consider the currently selected events, no matter if its notes, CC event or whatever, but I guess that's too far off track to ever become reality ;). I however pretty much dislike that the select previous/next CC lane commands only work if you already have a CC event of sorts, because that means that you'll either have to go through the event view or insert a note and change it into a CC event in order to have those two actions do anything at all.

**Comment by ScottChesworth** [comment]
I've had some conversation with Cockos about this, think perhaps I haven't quite managed to get the clooginess of the current situation across. Will make a screen cap explaining the issues in situ, that usually helps.

**Comment by ScottChesworth** [comment]
Reopening because I think this is still needed.

**Comment by Lo-lo78** [comment]
@ScottChesworth 
The action is already there:
kawa: MIDICC2_Insert_CentorCCValue_(atLastTouchedLane)

**Comment by ScottChesworth** [comment]
That's from ReaPack though, right? Needs a native action IMO, either from REAPER or us.
