### ISSUE TITLE
Problem reporting compressor gain reduction

### ISSUE THREAD

**Issue by FelipeZanabria** [jcsteh/osara#796]
When the compressor setting is changed, Osara announces the lowest value shown in the ReaComp window.
For example, you have a raw signal peak of -12 dB. When compressed, the ReaComp window would show the modified value.

The box following the rms size edit field shows the amount of dB lost. The output gain box, which follows the previous one, shows the peak, which in this case is lower than the example 12 dB.
Osara announces the second frame, and if the viewer is not reset, it will continue to do so.
Rebooting the viewer works as expected, for example announcing a -3dB reduction.

**Comment by jcsteh** [comment]
For gain reduction, more reduction is considered to be significant, rather than less reduction. If you want the value to be continually updated, change the "Hold level" option accordingly.

Does this address your issue?

**Comment by FelipeZanabria** [comment]
In that case it is not a greater or lesser reduction, instead, it is the level of the uncompressed audio, and the compressed audio, which is reported by changing the settings. Changing a parameter is reported, for example:
Suppose the compressor has the ability to set the ratio to infinity, like a limiter.
Having a sine wave with the maximum peak of -12 dB, it is easy to deduce that if the threshold is set to -14 dB, there is supposed to be -2 dB of reduction.
So, going back to the Osara report, I think I should announce that -2 dB reduction, instead of possibly -14.
The maximum peak before compressing is not always known.
It seems to be something that works what you have said.

**Comment by RDMurray** [comment]
@FelipeZanabria  This is exactly what happens. I just put a sine wave through reacomp to test this. With a sine wave peaking at -12, threshold -30 and ratio inf, peak watcher reports gain reduction of -15.2, and the resulting peak of the sine wave is -27.2. It's not quite -30 because the detector of the compressor uses rms, not peak. 

This matches the gain reduction shown in reacomp, as long as you reset it which can be done by clicking on the gain reduction in the reacomp window.

Closing because it seems to behave as it should.
