### ISSUE TITLE
Hot request. Is there a possibility that there is a spectrum analyzer on OSARA?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#806]
Hi everyone!
After Peak Watcher I think an important analysis tool is the spectrum analyzer.
Is it possible that OSARA can work on this?
The ears don't always go where the spectrum analyzer goes.
If you don't have a subwoofer it is very difficult to have consistent bass frequencies.
I know it's hard work but I hope it can be done.

Thank you!

**Comment by jcsteh** [comment]
Implementing that would require an audio effect, since extensions don't have access to playing audio data in realtime like that. That said, there's already the [Accessible Spectrum Analyser](http://depic.eecs.qmul.ac.uk/apm/spectrum.html), which does just that. It does it using sonification rather than speech, but it's an open question whether this could really be made useful with speech anyway.

**Comment by Lo-lo78** [comment]
Yes, it's QueenMaryUniversityOfLondon's AccessibleSpectrumAnalyser.
It is too difficult to use.
In my opinion, numbers and words are easier to understand.
If I read 20 db at 80 hz above normal I can correct it better than with sound.
Much more accurate.
There is the JS: 5-Band Splitter which could help for the audio source.
It divides the audio into 5 bands and with the JS: Audio Statistics you can take the data in ca more comfortable table to navigate.
It's a bit hot proposal!

:)

**Comment by ptorpey** [comment]
Interesting idea.

 

I wonder if such a concept would be amenable to being implemented in a ReaScript that can be used as an action to create an HTML table as with the Dry Render functions?

 

--Pete

**Comment by ScottChesworth** [comment]
> In my opinion, numbers and words are easier to understand. If I read 20 db at 80 hz above normal I can correct it better than with sound. Much more accurate.
>
I was involved in the research sessions when QMUL were exploring how a frequency spectrum could be presented in an accessible way, we explored a couple of concepts similar to what you've described. Unfortunately, the results became less intuitive and more difficult to make decisions from surprisingly quickly every time we tried analysing anything beyond basic tests in lab conditions. Can't say I use what QMUL developed much nowadays really, but it was the clear winner in terms of practicality and intuitiveness at the time. Given that screen reader tech hasn't notably changed since, I think it's fair to say that someone would need to come forward with a very well fleshed out proposed UX that hasn't already been explored. If you're that person, cool, feel free to write up your ideas, but for now I'm gonna close this as not planned because it doesn't seem likely we'll be able to take it forward.
