### ISSUE TITLE
Alt + p alt ++ f alt + c in the OSARA FX parameter window in the progress slider and close button do not work. Activate TCP actions

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#808]
Hi everyone!
When I am in the progress slider or the close button the shortcuts in the OSARA FX parameter window have no effect. Reaper's actions are activated.
They can cause misunderstandings while working.
Thank you!

**Comment by ScottChesworth** [comment]
Hmm, more examples of the slippery sloap @jcsteh warned us about then. I'm starting to suspect that guy knows his stuff.

**Comment by ScottChesworth** [comment]
I'm trying to tighten this up by not passing Alt+C, Alt+F and Alt+P through to main window like Jamie did with Up and Down arrows a couple weeks back, but not having much luck.

Code:
			// Retain Alt in combination with C, F and P for navigation
			case VK_MENU && 0x43:
			case VK_MENU && 0x46:
			case VK_MENU && 0x50:

When I try to build, scons says a thousand times no:
src\paramsUi.cpp(559,17): error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
                        case VK_MENU && 0x43:
                                     ^  ~~~~
src\paramsUi.cpp(559,17): note: use '&' for a bitwise operation
                        case VK_MENU && 0x43:
                                     ^~
                                     &
src\paramsUi.cpp(559,17): note: remove constant to silence this warning
                        case VK_MENU && 0x43:
                                    ~^~~~~~~
clang-cl /Fobuild\x86_64\envelopeCommands.obj /c src\envelopeCommands.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
src\paramsUi.cpp(560,17): error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
                        case VK_MENU && 0x46:
                                     ^  ~~~~
src\paramsUi.cpp(560,17): note: use '&' for a bitwise operation
                        case VK_MENU && 0x46:
                                     ^~
                                     &
src\paramsUi.cpp(560,17): note: remove constant to silence this warning
                        case VK_MENU && 0x46:
                                    ~^~~~~~~
src\paramsUi.cpp(561,17): error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
                        case VK_MENU && 0x50:
                                     ^  ~~~~
src\paramsUi.cpp(561,17): note: use '&' for a bitwise operation
                        case VK_MENU && 0x50:
                                     ^~
                                     &
src\paramsUi.cpp(561,17): note: remove constant to silence this warning
                        case VK_MENU && 0x50:
                                    ~^~~~~~~
src\paramsUi.cpp(560,9): error: duplicate case value '1'
                        case VK_MENU && 0x46:
                             ^
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um\winuser.h(494,27): note: expanded from macro 'VK_MENU'
#define VK_MENU           0x12
                          ^
src\paramsUi.cpp(559,9): note: previous case defined here
                        case VK_MENU && 0x43:
                             ^
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um\winuser.h(494,27): note: expanded from macro 'VK_MENU'
#define VK_MENU           0x12
                          ^
src\paramsUi.cpp(561,9): error: duplicate case value '1'
                        case VK_MENU && 0x50:
                             ^
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um\winuser.h(494,27): note: expanded from macro 'VK_MENU'
#define VK_MENU           0x12
                          ^
src\paramsUi.cpp(560,9): note: previous case defined here
                        case VK_MENU && 0x46:
                             ^
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um\winuser.h(494,27): note: expanded from macro 'VK_MENU'
#define VK_MENU           0x12

Any tips on what I'm doing wrong would be much appreciated. I would've thought && would be what we'd want so that keystate is detected for the modifier and the accompanying letter, but near as I can tell, that's the first thing scons is unhappy about? I'm also not sure what "previous case defined" means, searching the code, the lines I've added are the only places where those are used.

**Comment by jcsteh** [comment]
1. Excepting alt+c/f/p isn't going to work for non-English locales. I think we'll need to except alt+any letter.
2. The case statement is matching based on the vk code of the key you just pressed. You can't use `&&` in a case statement, and even if you could, you need to check the state of held keys, not the key just pressed. I think this is going to need a completely different `if` check outside of the switch statement. You can check if alt is being held down with `GetAsyncKeyState(VK_MENU) & 0x8000`.

**Comment by ScottChesworth** [comment]
Damn, I was sure I'd read that those keycode values are consistent across locales, that's why I tried to use them.
Would there be a way we could accept Alt plus any letter, excluding Alt plus F keys? That way Peak Watcher would still be usable.
Hmm, out of my depth again. *sigh*

**Comment by jcsteh** [comment]
> Damn, I was sure I'd read that those keycode values are consistent across locales, that's why I tried to use them.

The key codes might be consistent, but the words are different and so the access keys are different (not c/f/p).

> Would there be a way we could accept Alt plus any letter, excluding Alt plus F keys?

Key codes and locales are messy. I can probably get this working for most Latin keyboards, but even then, some non-English characters might break (É, etc.).
