### ISSUE TITLE
Speech when announcing sends and receives should put word folder or track last 

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#827]
In Windows, when I am on a track and do alt application key and go to either the send or receive submenus, the list of options to  create the send or receive for are announced with either the word track or folder first followed by the track number and then its name.   Could the word folder or track be announced at the end to speed up navigating this list?  Saying the word folder or track does not help me pin down my position so is not that useful to announce.

**Comment by jcsteh** [comment]
That menu is entirely the domain of REAPER itself. The only thing OSARA does is provide an action to open the menu that doesn't require using a mouse. So, I would suggest taking this one up with Cockos.

**Comment by ScottChesworth** [comment]
I've asked.

**Comment by CastleStarter** [comment]
Thanks for the explanation Jamie.

Best, Chris

**Comment by CastleStarter** [comment]
Thanks Scott.  Will wait and see.  

Best, Chris

**Comment by ScottChesworth** [comment]
Here's what's coming:
1. The word "track" and the Colon symbol will be removed (axing track because it prevents navigating by number, axing Colons because with most speech synths they force an annoyingly long pause).
2. The word Folder will still be prepended for relevant entries, but Colons after those are going as per above reasoning.

The upshot is that instead of hearing "Track 32: Guitar" you'll hear "32 guitar", and instead of "Folder: Percussion" you'll hear "Folder percussion". This approach means that now we're able to use numbers for quicker navigation (example: in a project with 80-something tracks, you could tap 4 to jump to the start of the 40's), and even if you're not sure of a ballpark track number, you'll be able to jump to a nearby folder by tapping f.

Colon symbols are also being removed from Audio Hardware Output submenu, again, just making those choices quicker to hear. Numbers are still gonna be prepended though because some I/O naming convensions would be ambiguous without them.

Hope that's what you were after. :)

**Comment by CastleStarter** [comment]
I’m kinda stuck for words.  That’s awesome.

Yes, I could rabbit on here but in short, that is just awesome.  I’m talking about the process of getting a feature request in and responded to.

Many thanks. Chris.

**Comment by ScottChesworth** [comment]
These tweaks are up in the +dev build for Jan 2nd. All seems solid here, but if anyone wants to put more feedback in before they go into a stable release, now's a good time.

**Comment by ptorpey** [comment]
If Cockos is going to fix lables, here are my two suggestions:

 

1.	In the midi event list,:

a.	The column title labeled “parameter” should be “note name”
b.	The column title labeled “value” should be “velocity.

2.	In REaEq, the automatable parameter “Q” should be changed to “band width”.  Q and band width are actually the inverse of each other so this is very mis-leading.

 

--Pete

**Comment by CastleStarter** [comment]
How do I try the +dev build?

Regards, Chris

**Comment by ScottChesworth** [comment]
> How do I try the +dev build?
> 
We're not supposed to link to them. Will email you in a sec.

**Comment by TimNoonanVoice** [comment]
Working nicely here on Mac - 

great that you can now type the sends or receives menu and then press the track number of interest and jump right to it, Due to the word track being eliminated from the track list.
Tim


On 3 Jan 2023, at 6:14 pm, ScottChesworth ***@***.***> wrote:


These tweaks are up in the +dev build for Jan 2nd. All seems solid here, but if anyone wants to put more feedback in before they go into a stable release, now's a good time.

**Comment by Lo-lo78** [comment]
Hi the tracks are numbered well.
First the number and followed by the name.
But when there is a folder it is not numbered like in the official Reaper versions.
In my opinion the end folder should also be clearly marked.
Do you think it could be useful to put the track number also for the folder?
Perhaps having the F key for "folder" and the E key for the "end folder" is even better for quick navigation.
Greetings!

**Comment by ScottChesworth** [comment]
> Do you think it could be useful to put the track number also for the folder?
> 
It sounded misleading without the forced pause. Like, imagine hearing "folder 27 drums", it sort of sounds like you've got 27 folders in the project, the twenty-seventh one being called drums. Clearer without numbering IMO.

> Perhaps having the F key for "folder" and the E key for the "end folder" is even better for quick navigation.
> 
Ooh, that's an interesting idea. I'll ask about it.

**Comment by ScottChesworth** [comment]
> Perhaps having the F key for "folder" and the E key for the "end folder" is even better for quick navigation.
> 
Looks like this is gonna happen @Lo-lo78 :)

**Comment by Lo-lo78** [comment]
@ScottChesworth 
Super cool!
👍👍👍
