### ISSUE TITLE
Tidy up extraneous speech when navigating tab order in FX window;

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#843]
I'm not sure whether this is one best handled by OSARA or Cockos (suspect the latter), but there are examples of extraneous speech when navigating the tab order in the FX window that I'd love to get cleaned up. I regularly see new users being bamboozled by this when they're not yet familiar enough with the layout to fly around on muscle memory, some tightening here would do a lot of good for the UX.

1. Create a track and instantiate ReaEQ (note that these examples are specific to the FX window, not ReaEQ).
2. From the FX chain list (the default landing position), press tab three times to reach the Presets combo box. Do this slowly and notice how the first two presses provide clean reports, but on the third press when you reach the Presets combo box, the useful part of the report (IE, that the Presets combo box is now focused and which preset is selected) is prefixed with a bunch of status stuff from elsewhere in the window. Here's an example report:
"0.0%/0.0% CPU 0/0 spls  property page  A2 Gain: ReaEQ," and only then do we hear "combo box  No preset  collapsed".
3. Now hit Tab once more, and start Shift+Tabbing back through the same controls. Moving in this direction, reporting is clean as a whistle. Ideally, this is the UX I'd like us to have travelling forward.
4. Another example, tab until you reach the unlabelled check box (already asking Cockos to fix that), and notice on the next press, we have another extraneous prefix:
"property page  G2," then we hear the actual control, "Band frequency  slider  100.0".

The fact that these examples are split into two separate reports in NVDA's speech buffer leads me to believe it happens when we move between groups in the object hierarchy or some such thing, but I don't really know enough yet to be sure I'm asking Cockos for the right stuff. Do we need improvements to the roles in the FX window? If we're going to hear prefixes, it would be good for them to be clarified, like "Presets grouping", "FX controls" and so on.

Any advice welcome. I'm happy to do the asking, watch the dev builds like a hawk and provide feedback once this gets moving, I just wanna be sure that what I'm requesting is correct and concise.

**Comment by ptorpey** [comment]
Scott,

 

I just followed the steps you gave below using JAWS.  I repeated the steps with and without the JAWS scripts running.  I didn’t hear any of the extraneous speech you describe.

 

The only odd thing I did hear was when tabbing once or twice and getting to and Edit field that said “comment”.  I have no idea what that is indicating.  Also, as you pointed out, the checkbox in the tab order has no useful description.

 

Speaking of ReaEq, did you ever get any sensible answer from cockos about why the bandwidth parameter is labeled as “Q” in some places?  As I’ve pointed out, they are the inverse of each other so it is not only confusing but wrong.  Should be easy to fix the label.

 

--Pete

 

 

From: ScottChesworth ***@***.***> 
Sent: Saturday, January 21, 2023 11:30 AM
To: jcsteh/osara ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jcsteh/osara] Tidy up extraneous speech when navigating tab order in FX window; (Issue #843)

 

I'm not sure whether this is one best handled by OSARA or Cockos (suspect the latter), but there are examples of extraneous speech when navigating the tab order in the FX window that I'd love to get cleaned up. I regularly see new users being bamboozled by this when they're not yet familiar enough with the layout to fly around on muscle memory, some tightening here would do a lot of good for the UX.

1.	Create a track and instantiate ReaEQ (note that these examples are specific to the FX window, not ReaEQ).
2.	From the FX chain list (the default landing position), press tab three times to reach the Presets combo box. Do this slowly and notice how the first two presses provide clean reports, but on the third press when you reach the Presets combo box, the useful part of the report (IE, that the Presets combo box is now focused and which preset is selected) is prefixed with a bunch of status stuff from elsewhere in the window. Here's an example report:
"0.0%/0.0% CPU 0/0 spls property page A2 Gain: ReaEQ," and only then do we hear "combo box No preset collapsed".
3.	Now hit Tab once more, and start Shift+Tabbing back through the same controls. Moving in this direction, reporting is clean as a whistle. Ideally, this is the UX I'd like us to have travelling forward.
4.	Another example, tab until you reach the unlabelled check box (already asking Cockos to fix that), and notice on the next press, we have another extraneous prefix:
"property page G2," then we hear the actual control, "Band frequency slider 100.0".

The fact that these examples are split into two separate reports in NVDA's speech buffer leads me to believe it happens when we move between groups in the object hierarchy or some such thing, but I don't really know enough yet to be sure I'm asking Cockos for the right stuff. Do we need improvements to the roles in the FX window? If we're going to hear prefixes, it would be good for them to be clarified, like "Presets grouping", "FX controls" and so on.

Any advice welcome. I'm happy to do the asking, watch the dev builds like a hawk and provide feedback once this gets moving, I just wanna be sure that what I'm requesting is correct and concise.

**Comment by ptorpey** [comment]
Oops, meant that note to go to the RWP list.  Sorry about that.

 

--Pete

 

 

From: ***@***.*** ***@***.***> 
Sent: Saturday, January 21, 2023 11:41 AM
To: 'jcsteh/osara' ***@***.***>
Subject: RE: [jcsteh/osara] Tidy up extraneous speech when navigating tab order in FX window; (Issue #843)

 

Scott,

 

I just followed the steps you gave below using JAWS.  I repeated the steps with and without the JAWS scripts running.  I didn’t hear any of the extraneous speech you describe.

 

The only odd thing I did hear was when tabbing once or twice and getting to and Edit field that said “comment”.  I have no idea what that is indicating.  Also, as you pointed out, the checkbox in the tab order has no useful description.

 

Speaking of ReaEq, did you ever get any sensible answer from cockos about why the bandwidth parameter is labeled as “Q” in some places?  As I’ve pointed out, they are the inverse of each other so it is not only confusing but wrong.  Should be easy to fix the label.

 

--Pete

 

 

From: ScottChesworth ***@***.***> 
Sent: Saturday, January 21, 2023 11:30 AM
To: jcsteh/osara ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jcsteh/osara] Tidy up extraneous speech when navigating tab order in FX window; (Issue #843)

 

I'm not sure whether this is one best handled by OSARA or Cockos (suspect the latter), but there are examples of extraneous speech when navigating the tab order in the FX window that I'd love to get cleaned up. I regularly see new users being bamboozled by this when they're not yet familiar enough with the layout to fly around on muscle memory, some tightening here would do a lot of good for the UX.

1.	Create a track and instantiate ReaEQ (note that these examples are specific to the FX window, not ReaEQ).
2.	From the FX chain list (the default landing position), press tab three times to reach the Presets combo box. Do this slowly and notice how the first two presses provide clean reports, but on the third press when you reach the Presets combo box, the useful part of the report (IE, that the Presets combo box is now focused and which preset is selected) is prefixed with a bunch of status stuff from elsewhere in the window. Here's an example report:
"0.0%/0.0% CPU 0/0 spls property page A2 Gain: ReaEQ," and only then do we hear "combo box No preset collapsed".
3.	Now hit Tab once more, and start Shift+Tabbing back through the same controls. Moving in this direction, reporting is clean as a whistle. Ideally, this is the UX I'd like us to have travelling forward.
4.	Another example, tab until you reach the unlabelled check box (already asking Cockos to fix that), and notice on the next press, we have another extraneous prefix:
"property page G2," then we hear the actual control, "Band frequency slider 100.0".

The fact that these examples are split into two separate reports in NVDA's speech buffer leads me to believe it happens when we move between groups in the object hierarchy or some such thing, but I don't really know enough yet to be sure I'm asking Cockos for the right stuff. Do we need improvements to the roles in the FX window? If we're going to hear prefixes, it would be good for them to be clarified, like "Presets grouping", "FX controls" and so on.

Any advice welcome. I'm happy to do the asking, watch the dev builds like a hawk and provide feedback once this gets moving, I just wanna be sure that what I'm requesting is correct and concise.

**Comment by ScottChesworth** [comment]
> Speaking of ReaEq, did you ever get any sensible answer from cockos about why the bandwidth parameter is labeled as “Q” in some places?
> 
It helps if I remember to ask. Having done that now, they said "oops".

> Should be easy to fix the label.
> 
Looks like a fix should be in the next+ dev.

**Comment by ptorpey** [comment]
Should be easy to fix the label.

Looks like a fix should be in the next+ dev.

[PT] Thanks a bunch.  Obviously not a big thing since the label has been there for a long time, but sometimes little things like that can drive an OCD scientifically minded person like myself nuts.  Now I can sleep at night!

 

--Pete

**Comment by jcsteh** [comment]
The reason this happens is that REAPER uses property pages (AKA tab panels) for a lot of groupings. Like dialogs, tab panels usually have a caption, so NVDA tries to guess that caption based on text in the tab panel. In this case, the guess is wrong.

There is code in OSARA (see annotateSpuriousDialogs) to deal with this. Currently, it's only triggered for the main window. We'd need to try to somehow trigger this for the FX chain window too.

**Comment by ScottChesworth** [comment]
Are those captions something that Cockos could specify?

**Comment by jcsteh** [comment]
There's not a standard way to do that. For NVDA, they could do that by annotating the description, but I'm not sure how JAWS or other screen readers would handle that. Also, there's actually no useful caption for these panels, and annotating nothing isn't possible.

**Comment by ScottChesworth** [comment]
Gotcha. Well I know Justin has got description fresh in his memory because we tried that a few days back during tightening up the virtual keyboard. However, it didn't override the extraneous speech in that case.

**Comment by ScottChesworth** [comment]
@ptorpey, Bandwidth param label is fixed in today's dev build. Another accessibility clarifier I requested accidentally got put on the wrong control though, so you might wanna wait until tomorrow. 🤞

**Comment by ptorpey** [comment]
Thanks Scott. I did notice that comment in the latest Deville. Unfortunately I just left on a week and a half vacation this morning and won’t be able to pick up those bills and test until I’m back late next week. Nice though that you were able to get them to fix the labels on those controls. Thanks again.– – Pete.Sent from my iPhoneOn Jan 24, 2023, at 7:18 PM, ScottChesworth ***@***.***> wrote:﻿
@ptorpey, Bandwidth param label is fixed in today's dev build. Another accessibility clarifier I requested accidentally got put on the wrong control though, so you might wanna wait until tomorrow. 🤞
