### ISSUE TITLE
Action that is not available for translation.

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#865]
Hi,
Is it possible to be able to translate the following actions:
OSARA: Toggle Report transport state (play, record, etc.)
OSARA: Toggle Report track numbers
OSARA: Toggle Report time movement during playback/recording
OSARA: Toggle Report position when scrubbing
OSARA: Toggle Report position when navigating chords in MIDI editor
OSARA: Toggle Report markers during playback
OSARA: Toggle Report full time for time movement commands
OSARA: Toggle Report changes made via control surfaces
OSARA: Toggle Report MIDI notes in MIDI editor
OSARA: Toggle Report FX when moving to tracks/takes
OSARA: Toggle Move relative to the play cursor for time movement commands during playback
Thanks.

**Comment by ScottChesworth** [comment]
Newbie question: I don't know where we're at with action translation. Are some of our actions already translatable and these ones need to be added? Or is it that none of our actions are translatable yet and these are the ones you need most?

**Comment by leejul** [comment]
Hmm, I think some action can't be translatable so for those, I don't think that has changed.
  But I think the actions mentioned above would be doable but impossible for me to be sure about that.
  The problem is that there are French-speaking users who do not understand an English word.
  For them, it's complicated.

**Comment by ScottChesworth** [comment]
Can you point me at an OSARA action that's already translatable? I wanna see how it's being done, maybe there'll be code I can reuse/adapt.

**Comment by leejul** [comment]
OSARA: Toggle track/take mute envelope visibility (depending on focus)
OSARA: Toggle track pre-FX pan or take pitch envelope visibility (depending on focus)

**Comment by ScottChesworth** [comment]
So the newest actions are translatable. Hmm, let's see if I can figure out how @jcsteh did that. je suis un débutant :)

**Comment by leejul** [comment]
How brave you are to get into C++. I wish I had that talent. Maybe in another life.

**Comment by jcsteh** [comment]
These settings actions are different to other OSARA actions. While not ideal, for these, we join the string "OSARA: Toggle" and the string for the name of the setting; e.g. "Report track numbers". I did it this way because those toggle actions are generated by the settings framework rather than manually entered, as it makes maintaining them a lot easier.

@Leejul, do you get the whole string in English for all of these despite having translated those smaller chunks? Do any of the OSARA: Toggle actions get translated correctly?

**Comment by leejul** [comment]
Yes, all the toggles are already translated.
I don't know if I have to do another issue but there is a problem with the actions to display of the mute envelope.
In English, NVDA says, showed track Mute envelope or hid track Mute envelope.
But in French it is always inverted compared to English.
I think the phrase stated is several words put together, but maybe I'm wrong.
But in French it makes no sense.
Sourdine enveloppe de piste affichée
It should be:
Enveloppe de Sourdine de piste affichée
Enveloppe de Sourdine de piste masqué
Is it possible to have a complete sentence spoken rather than assembled words?
Thanks.

**Comment by jcsteh** [comment]
Combining strings is never ideal for translation. It's a similar situation with envelopes. OSARA just figures out which envelope is toggled. It asks REAPER for the name of that envelope and then formats it using the string:
"showed {} envelope}
where {} is replaced with the envelope name from REAPER. Having separate strings for each one:
"showed volume track envelope"
"hid volume track envelope"
would require OSARA to separately support every possible envelope, which isn't really feasible.

Note that in the string:
"showed {} track envelope"
you can put the {} wherever the envelope name fits best for your language.

Note that even in English, this isn't grammatically correct. A full, grammatically correct sentence might be:
"The track volume envelope has been shown."
That is also ridiculously inefficient. The user has to listen to the entire sentence to hear the most important information. Similarly, we say "Comment button" rather than "There is a button labelled comment." IMO, grammatical correctness isn't the priority for screen reader messages.

**Comment by jcsteh** [comment]
I found the bug with the toggle actions. Sorry about that; silly error on my part.

**Comment by leejul** [comment]
Cool thanks Jamie.
