### ISSUE TITLE
Show config options related to feedback in MIDI editor in MIDI Editor section, so they're usable on the fly

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#883]
I got a request from someone who'd find it useful to toggle these two options in OSARA Configuration on the fly during MIDI editing.
- Report position when navigating chords in MIDI editor
- Report MIDI notes in MIDI editor
To make that possible, I'm hoping to skate on existing code making our action to mute next message visible in that section:
{MIDI_EDITOR_SECTION, {DEFACCEL, "OSARA: Mute next message from OSARA"}, "OSARA_MUTENEXTMESSAGE", cmdMuteNextMessage},

Most of that is easily reused, but what should I end with instead of cmdMuteNextMessage? Any tips appreciated.

**Comment by jcsteh** [comment]
Those toggles are added by the automatic settings framework. Unfortunately, that means it's not as simple as binding most other OSARA actions, since there's no separate cmd function you can call.

I think we'll need to teach the settings framework how to bind actions in other sections. So, we would have a section id in the BoolSetting macros in settings.h. That would mean these particular toggles would only be available in the MIDI Editor section, no longer in the main section, but that probably makes sense, since they're dealing with MIDI editing.

Doing that is going to require modifying all of the code in config.cpp which uses those macros, especially registerSettingCommands, handleSettingCommand and handleToggleState.

**Comment by ScottChesworth** [comment]
Urgh, beyond what I'm capable of at the moment. If you get to it and there's repetitive stuff left over, happy to pick that up though.
