### ISSUE TITLE
Can note previews respect length for next inserted note when using pitch cursor?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#884]
When navigating chords in the MIDI editor, note previews already respect the length of each note. However, when adjusting the pitch cursor with Alt+Up, Alt+Down, Alt+Shift+Up or Alt+Shift+Down, a generic preview length is played, I think we use a timer at the moment.
Could previews respect the current setting for lenth of next inserted note (Control+top row numbers)? Hearing contextual previews would make manual insertion of notes a more intuitive task, particularly for users who don't have a strong grasp of theory.

**Comment by jcsteh** [comment]
To do this, I guess we'd need to look at all the note length toggle actions to see which one is enabled. When we find the right one, we'd then need to calculate how long that note would be in seconds/fractions of a second. I'm not quite sure how to do that. Maybe something to do with TimeMap_QNToTime? Once we have that, we can pass that as the note end to previewNotes, which will use that as the length.

**Comment by ScottChesworth** [comment]
This seems like quite a lot of work, and also like context that would be useful in the mainstream. Shall I ask Cockos about it, see if native support can happen?

**Comment by jcsteh** [comment]
As in native support for previewing when the pitch cursor is moved? I guess that would make sense. Note that this would require removal of the OSARA code which generates note previews in that case. Otherwise, we'd double up.

That said, this is probably a couple hours of work if someone wants to put in the time, assuming we can figure out exactly how to calculate a time length from a beats length, assuming that's possible. It all depends whether we think this important enough relative to other things we want Cockos to fix.

It just occurred to me that it might be easier to calculate time from beats by looking at the current bpm and time signature. 🤷‍♂️

**Comment by ScottChesworth** [comment]
Might be worth showing Justin what we do so far re note previews. What would I link him to to get the clearest overview?

**Comment by jcsteh** [comment]
I think Justin originally helped me with the preview code, haha. [The preview code is here](https://github.com/jcsteh/osara/blob/be3bb40bc8b233fa5866aa6ee7c59446712f6dd3/src/midiEditorCommands.cpp#L433) and [we call that from here for the pitch cursor](https://github.com/jcsteh/osara/blob/be3bb40bc8b233fa5866aa6ee7c59446712f6dd3/src/midiEditorCommands.cpp#L1126), but really, this is just about us calculating the right length for the pitch cursor case. It really shouldn't be that hard as such, just tedious.

**Comment by jcsteh** [comment]
Oh. I just saw there's a MIDI setting for default_note_len, so we can avoid all the action probing crap. So, just a matter of calculating time from MIDI ticks.

**Comment by ScottChesworth** [comment]
Found this conversion on Stack Overflow if it helps at all:
The formula is 60000 / (BPM * PPQ) (milliseconds). Where BPM is the tempo of the track (Beats Per Minute). (i.e. a 120 BPM track would have a MIDI time of (60000 / (120 * 192)) or 2.604 ms for 1 tick.
