### ISSUE TITLE
item sellection

### ISSUE THREAD

**Issue by egljarm** [jcsteh/osara#906]
When i editing sound using item split method, and for example spliting one time at the beginning  and another split to end of sound whitch i Wnt to delete, i need press command left arrow two times in order to select previous item but acctually   Item after second splitting is selected, and should be enough to press one time command left errow,  in order to select previous item. . Thank you. I have an audio recording where I am demonstrating this issue, but can not add it here.

**Comment by jcsteh** [comment]
@ScottChesworth clarified this for me:

> Say you've got an item on a track, and you split it, so there are two now. When you split, the second item is selected automatically. If you want to select the first item though, you have to hit Control+Left twice, because the first press moves you to the start of the second item. I've always assumed I had some overlap and crossfade thing set somewhere that made it behave that way, but I've just disabled that and it's still the same. Here it feels like more logical behaviour would be for the first press of Control+Left to select the first item assuming my edit cursor is still positioned on the split, unless I've moved my edit cursor further along the timeline than where the split is placed, in which case sure, it would return to the start of the second item.

I agree this would be better. However, it might be tricky to fix this without breaking other things.

The reason this happens is that OSARA's next/previous item actions move to the next or previous item even if that item is right at the position of the cursor. If i remember correctly, this is one of the big reasons I replaced REAPER's own item navigation actions: precisely because they didn't do this. There are a few reasons for this behaviour:

1. If you're at the start of the project and the first item begins at the start of the project, you want control+rightArrow to move to that item. If we always moved to the item before/after the cursor, it would skip to the second item.
2. If we skipped items at the cursor, it would be impossible to navigate to multiple items that start at the same position.
3. If you jump to a marker or similar and an item starts right at that marker, it's more convenient for item navigation to move to that item rather than skipping over the item you probably want. Admittedly, you could use shift+a to get around this.

It'd be good if we could avoid this behaviour for splits. However, I'm not sure if we can determine when this happens and what item to choose when it does.

**Comment by ranetto** [comment]
Hi, but I think that as it currently is it works well, I often use this behavior to align an element of a different track by taking it and selecting that element and then moving to a different track and pasting it right in that position. We often need to know where an element is located even if we don't operate on it, I wouldn't change it, it seems to me that the current behavior is the best possible and very functional.

**Comment by jcsteh** [comment]
I did end up changing this. However, note that when you split an item, the second item is already selected, so you can still achieve what you want.
