### ISSUE TITLE
playrate in reaper

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#908]
Hello everyone, I'm asking, because I didn't understand the meaning of what the playrate mapped on the plus and minus of the keyboard is for, it created several problems for me because colliding with it by mistake, it meant that I had to re-export already mastered songs: I I decided to remove it, rather to assign a very difficult combination to carry out. I know what it's for, the playrate as an envelope on the master, where it's used for effects in dance music, but don't you think it's dangerous to have the direct and useless one mapped to the plus and minus of the keyboard? Thanks, I know it's not so directly about osara but I thought I'd ask anyway.

**Comment by jcsteh** [comment]
CC @ScottChesworth . I'm guessing there are common use cases for quickly fiddling with the play rate, but if there aren't, this does raise the question as to why it's such an easy keyboard shortcut to hit.

That said, you could argue that just about anything is potentially problematic for someone if they don't realise they've done it. And although I understand accidents do happen, OSARA does provide feedback for these commands, so one can be aware of what's happening if one is paying attention.

**Comment by TimNoonanVoice** [comment]
Interestingly, at least on the Mac, even when in key announce mode, pressing command = adjust the play rate.

As this assignment is present, I have always thought it a little odd that there isn't an inverse command on command - which instead - is set to rewind a little bit.

Of course un-do works, but not if you've done other things before realising you are set to chipmunks.

Tim


On 7 Aug 2023, at 9:56 am, James Teh ***@***.***> wrote:


CC @ScottChesworth <https://github.com/ScottChesworth> . I'm guessing there are common use cases for quickly fiddling with the play rate, but if there aren't, this does raise the question as to why it's such an easy keyboard shortcut to hit.

That said, you could argue that just about anything is potentially problematic for someone if they don't realise they've done it. And although I understand accidents do happen, OSARA does provide feedback for these commands, so one can be aware of what's happening if one is paying attention.

**Comment by jcsteh** [comment]
Actually, I think there might be some confusion here all around. I just checked and in the readme and on Windows, the playrate adjustment commands are shift+equals, shift+dash, control+shift+equals and control+shift+dash. So, none of them are a single key and thus should be harder to accidentally bump. I'm also wondering whether the mappings are incorrect on Mac based on the previous comment.

**Comment by TimNoonanVoice** [comment]
Sorry for adding confusion here.

The Mac mappings for adjusting play-rate by increments are correct, 

the command I was referring to, which I always get tripped up by, that is mapped to command equals  is listed as Custom Fast Forward when I use un-do, but when pressed says '2 play-rate", '4 play-rate" "8 play-rate" etc. It also is acted upon in the key describer.

Hope this clarifies my earlier message.
Tim



On 7 Aug 2023, at 11:56 am, James Teh ***@***.***> wrote:


Actually, I think there might be some confusion here all around. I just checked and in the readme and on Windows, the playrate adjustment commands are shift+equals, shift+dash, control+shift+equals and control+shift+dash. So, none of them are a single key and thus should be harder to accidentally bump. I'm also wondering whether the mappings are incorrect on Mac based on the previous comment.

**Comment by jcsteh** [comment]
That's what that action is intended to do apparently - it pauses, increases the play rate and then plays - but it definitely shouldn't be acting in shortcut help and it doesn't in Windows. Hmm. But that seems like something we should figure out in a separate issue.

**Comment by ScottChesworth** [comment]
@ranetto, adjusting playrate hasn't been on unmodified keys since probably about 5 years ago. Seems like you might need to update your key map.

@TimNoonanVoice, that fast forward custom action you're talking about was added by Derek and Gianluca back when they were running the key map. Think the idea of doubling the playrate each press is that it's useful for scanning through long passages of source material where you still want some amount of audible feedback. we don't have an accompanying rewind custom action that works the same way because REAPER doesn't provide a way to play the project backwards, only ways to skip, so the accompanying custom action wouldn't be possible to make.

**Comment by GarthHum** [comment]
Thought it was still there on the default keymap. A logical paired action would be one that halves the play rate. Personally I think the jump back with jump forward a little bit would be far more useful.  Sent from my iPhoneOn 7 Aug 2023, at 10:16 pm, ScottChesworth ***@***.***> wrote:﻿
@ranetto, adjusting playrate hasn't been on unmodified keys since probably about 5 years ago. Seems like you might need to update your key map.
@TimNoonanVoice, that fast forward custom action you're talking about was added by Derek and Gianluca back when they were running the key map. Think the idea of doubling the playrate each press is that it's useful for scanning through long passages of source material where you still want some amount of audible feedback. we don't have an accompanying rewind custom action that works the same way because REAPER doesn't provide a way to play the project backwards, only ways to skip, so the accompanying custom action wouldn't be possible to make.

**Comment by TimNoonanVoice** [comment]
I've now found command-shift-backspace - which returns play-rate back to 1.0. I don't feel strongly about it, but still think this is a potential gotcha for newer users. 

A side note, if play-rate has been changed, and you then record, the recording respects the new play-rate. Hence if rate was at 2 times, the recording is at half speed.

Tim

On 8 Aug 2023, at 12:57 pm, Garth Humphreys ***@***.***> wrote:


Thought it was still there on the default keymap. A logical paired action would be one that halves the play rate. Personally I think the jump back with jump forward a little bit would be far more useful.  Sent from my iPhoneOn 7 Aug 2023, at 10:16 pm, ScottChesworth ***@***.***> wrote:﻿ 
@ranetto, adjusting playrate hasn't been on unmodified keys since probably about 5 years ago. Seems like you might need to update your key map. 
@TimNoonanVoice, that fast forward custom action you're talking about was added by Derek and Gianluca back when they were running the key map. Think the idea of doubling the playrate each press is that it's useful for scanning through long passages of source material where you still want some amount of audible feedback. we don't have an accompanying rewind custom action that works the same way because REAPER doesn't provide a way to play the project backwards, only ways to skip, so the accompanying custom action wouldn't be possible to make.

**Comment by ranetto** [comment]
thanks to scot and all, i use a custom keymap that i've been making since 2017, so i proceeded to remove it myself as when i use playback speed i do it via automation. Thank you.

**Comment by jcsteh** [comment]
I'm going to close this. These commands require modifiers, so they're somewhat harder to bump accidentally, and they do provide feedback. Moreover, you could argue that many commands are potential gotchas in one way or another if you press them and don't realise. I guess we can re-evaluate this if we get a huge amount of support traffic about it.
