### ISSUE TITLE
Is it possible to use ctrl and shift to have smaller increments in the values ​​in the OSARA parameter window?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#938]
Hi, when I use an eq I often look for a precise frequency and I always go to the editing field to look for it.
In the OSARA dialog box you can use the arrows to make smaller steps and larger steps with page up or down.
Is it possible to use ctrl and shift to refine the value?
Surge XT has a very clever possibility:
with shift+arrows it takes smaller steps and with ctrl+arrows it goes to the nearest integer value.
For example:
I'm using ReaEQ and would like the first band to be at 300 hz.
I go to the OSARA parameters window and with the page on I change the default frequency from 100 to 284 and with the arrows I get to 299.9.
With ctrl+up arrow I could get to a closer integer which is 300 hz and with shift I change the fractions of the numbers:
300.01 300.02 300.03 and etc.
In this way we could have four ways to change value.
We could use Surge XT as an example.
If you cannot do all these functions you could still use ctrl and shift for small and very small steps.
It's definitely not needed for ReaEQ which is accessible but with EQs like the pro q it's important.
You could answer me that there is still an editing field. It is true!
But the numbers are often very difficult to manage. It is not possible to put 300 Hz but a number that corresponds to the value of 300 Hz.
This way it is more difficult because you lose some time to target the precise frequency.
Thank you!

**Comment by jcsteh** [comment]
It is very difficult to support precise numbers for plugins. Even if we supported smaller steps, it still might not be possible to get to the precise number you want in various plugins. The reason is that even though plugins provide a "friendly" representation of their value (e.g. 300 hz), that is actually just a piece of text provided by the plugin for a particular raw numeric value. The raw numeric values are the ones you see in the edit field. There is no way to map from a friendly value like 300 hz to a raw numeric value used by the plugin, which means that OSARA has no way to get to a precise value, even assuming it could support all the different numbering schemes used by different plugins and parameters.

All of that said, there is an issue open discussing changing OSARA's current 1000 steps per plugin parameter to 10000, which might at least improve things for you. A decision hasn't been made on that yet, though. See #593 for the discussion.
