### ISSUE TITLE
Speech feedback for the action, Item properties: Toggle lock.

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#944]
I see Osara reports an item's locked state when moving to an item. Would it be possible to get speech feedback when toggling locking on the current item? Idealy, this would also work for multiple selected items, for example saying "3 items locked."

**Comment by jcsteh** [comment]
Implementation note: We should be able to use very similar code to postToggleItemMute.

**Comment by ElCrackLoko** [comment]
Sorry for opening this but were any commands added? Or these reports only work when you add the action to a command as such, because I have tried it from the actions and it does not work for me, item lock, item unlock, take lock, take unlock, and Osara simply does not report me anything

**Comment by jcsteh** [comment]
I only added support for Item properties: toggle lock. If you want other actions reported, please file a new issue. Thanks.

**Comment by ElCrackLoko** [comment]
Hello brother. Forgive my clumsiness, truly forgive it. Maybe it's because of the language, but I don't understand well. Did you add Osara reporting support for when one blocks an item? You go to the item properties and check the lock box, click OK, and Osara should inform you that the item is locked/unlocked as the case may be? Likewise, in the actions with F4, there is an action that says block item, is that what it is for? Same for item unlocking, too? The thing is that I activate and deactivate them, but Osara does not verbalize anything to me.

**Comment by ElCrackLoko** [comment]
I mean, I don't need that, but as a translator I want to make sure that everything is right, can I?

**Comment by jcsteh** [comment]
No problem. I'll try to explain more clearly:

1. If an item is locked, when you move to the item with control+leftArrow or control+rightArrow, OSARA will report that "locked" as part of the item report. That has worked for quite some time now.
2. The change I made here is that now the action Item properties: toggle lock (which you can find in the Actions list) reports "locked" or "unlocked" as appropriate when you run it. It is not currently bound to a key in our key map, though.

**Comment by ElCrackLoko** [comment]
Of course! What you mention in step 2 is exactly what I do, I don't know why, but that is not working for me. Unless it's only restricted so that OSARA only informs me when there is a command involved. Makes sense? You can try it? I am using the latest version of Reaper 709. I also tried it in English but it doesn't work either. Logically, I am with the Osara version of January 25.

**Comment by jcsteh** [comment]
Just to be extra clear, the actions "Item properties: lock" and "Item properties: unlock" currently aren't supported. I only added feedback specifically for one single action, "Item properties: toggle lock". It's also tricky because the Actions dialog closing might clobber the feedback from the command. Perhaps try pressing the Run button rather than the Run/close button.
