### ISSUE TITLE
Is it possible to switch from FX chain to FX container chain with F6?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#947]
I find the workflow to be a bit slow.
Going from the FX chain to the FX container is a bit slow.
Is it possible to create an F6 key exception for container plug-ins that directly passes through the container's FX chain?
Thank you!

**Comment by jcsteh** [comment]
Do you mean instead of having to tab 10 times? I'll look into it.

For now, if I press f6, I get dumped on a random static text control. If I shift+tab from that, I get to the container chain. Does that work for you? That's not ideal or intuitive, but it cuts 10 keystrokes down to 2 as a workaround.

**Comment by ScottChesworth** [comment]
Should I ask Cockos to tweak the tab order @jcsteh?

**Comment by jcsteh** [comment]
I think it'll be tricky to change the tab order. The container basically just behaves like any other effect as far as the UI is concerned. It's reasonable to put the notes, preset selector, etc. between the list and the effect controls in most cases.

I think it's reasonable to have f6 switch to the container's list. Ideally, REAPER would implement this f6 thing instead of OSARA, but OSARA already has code for this and we probably have bigger fish for Cockos to fry.

**Comment by ScottChesworth** [comment]
Oh, but then that would clash with movement between bands in stock multiband plug-ins. That's also super useful.

**Comment by jcsteh** [comment]
When you're focused on a container, f6 would move into the container. When you're focused on a non-container effect, f6 would operate as it currently does.

That said, f6 is already broken for effects inside containers. Actually, I think this f6 code is going to need a significant rewrite to deal with containers and sub-containers and sub-sub-containers properly. Fun.
