### ISSUE TITLE
Accessible to visual looking in osara fx params list.

### ISSUE THREAD

**Issue by Alex-Longard** [jcsteh/osara#95]
Hi James, please make to view params and values in the list using visual revision or make screenshot.
It is necessary for developers of synthesizers and effects that i'm trying to arrange to make them available to us.

**Comment by jcsteh** [comment]
Someone with sight is going to need to do this. In theory, it can be 
done mathematically, but aside from this being tedious, error prone and 
extremely time consuming, it really needs to be done visually if you 
want it to look any good.

Note that the alternative UI in REAPER's FX chain dialog (click the UI 
button) should provide a similar experience for sighted users, so they 
may well be able to use this to judge their work instead.

**Comment by jcsteh** [comment]
Actually, visual layout isn't going to be enough. Someone would also need to design a custom widget which shows the value labels on the slider. Right now, those labels are only exposed for accessibility purposes; they aren't drawn to the screen at all. I have no idea how to design custom graphical widgets. This was simply never designed to be consumed by sighted users.

**Comment by jcsteh** [comment]
The visual presentation of dialogs was fixed in 203982de. However, as I noted [above](https://github.com/jcsteh/osara/issues/95#issuecomment-228931433), this still won't show the parameter values.

I'm not going to be able to fix this and no one else has shown any interest either, so I'm closing this. Note that you can see the same thing visually on envelope tool tips in REAPER. See the [Cockos Extensions to to VST SDK](https://www.reaper.fm/sdk/vst/vst_ext.php), which also includes implementation details for developers:

> • effVendorSpecific(effGetParamDisplay, parm, buf, val)
> Gets the formatted display of a particular value for a parameter, without setting the parameter. REAPER uses this when displaying the value of a VST's automated parameter on an envelope tooltip, for example.
