### ISSUE TITLE
View FX parameters for current track/take (depending on focus) (proposal new design)

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#952]
Since the arrival of containers in Reaper, I think it would be good to think about another design of the menu "View FX parameters for current track/take (depending on focus)".
Jamie has already accessed and fixed all the bugs when we are directly in the FX window.
But, personally, I would use a keyboard shortcut other than F6 which would be dedicated to the container.
This is how I see it:
Shortcut in the FX window:
Shift+Right Arrow - If container is selected, moves focus in its FX list, otherwise states, no container is selected
Shift+Left Arrow - Moves focus to the previous container, otherwise states, you are not in a container.
Should this be a loop, maybe yes, maybe no, personally a loop would be fine for me but some users might find it a bit confusing.
So for these users a stopper would be better for them.
If this is feasible, navigation would be extremely fast in the FX window.
Otherwise for the rest of the work already done in the FX window is very good, it is very responsive.

Now for the menu with Ctrl+F when the track is selected in the TCP.
Here is an example project:
I have 2 containers on my track.
1. Named EQ, it contains an EQ and a compressor.
2. Named Delay, it contains a delay and a compressor.
If I select my track and open the OSARA FX parameters list, I have 2 elements, the 2 containers.
I don't have access to the plugin parameters in the containers directly in the menu.
So I need to open the FX window, select the container, press F6, select the plugin and press Ctrl+Shift+P.
So, I propose to create submenus that would have the same name as the containers in this menu And the plugins would be in the submenus.
If there is a container in a container, create a submenu in the submenu etc.
To open the list which contains the 3 parameters of the container (Bypass, Wet and Delta), we select it, right arrow to open it, and the first in the list would always be the container itself. So you just press Enter.
Otherwise, you move on to the first plugin in this container.
Obviously, if the container does not contain a plugin, just press Enter only, once it is selected.
With submenu that would have the same name as the containers, it would be really quick to locate the container with a down arrow or up arrow, and a right arrow swipe to locate the plugin in that container.
Please note, it is also possible to add a container in position 1, a VST in position 2 and another container in position 3 in the FX list of the FX window.
So in this case, The menu must therefore follow the tree structure of this list of FX.
The overhaul of this menu is essential for me because it no longer reflects the needs of the future.
Additionally, as mentioned by Scott, "It avoids lag while some GUIs are drawn when arrowing through the FX chain list."
It avoids an annoying UX blip where some JUCE plug-ins/instruments grab keyboard focus as soon as they get selected in the FX chain list.
It avoids breaking like, 10000 mentions of it across resources.
And I would add that we have to think for later, I think that users will overuse the containers so opening the FX window will take a very long time.
It's not uncommon for users to have huge lists of presets for each plugin, which slows down opening the window. So imagine what it will be like with 4 containers which contains 4 plugins.

**Comment by jcsteh** [comment]
> Shortcut in the FX window:
> Shift+Right Arrow - If container is selected, moves focus in its FX list, otherwise states, no container is selected

Let's keep this in a separate issue please. I agree it's related, but it's a different decision. FWIW, sighted users can't do this either without clicking in the top FX list and I think this would effectively require OSARA to focus the FX list and select a different container anyway, so I don't think it's going to be feasible or particularly efficient.

> The overhaul of this menu is essential for me because it no longer reflects the needs of the future.

As I noted on list, it's already possible to do what you're requesting via the FX chain window with exactly the same number of keystrokes. Plus you can expose parameters from inner effects as part of the container itself if you really want maximum efficiency.

> Additionally, as mentioned by Scott, "It avoids lag while some GUIs are drawn when arrowing through the FX chain list."
> It avoids an annoying UX blip where some JUCE plug-ins/instruments grab keyboard focus as soon as they get selected in the FX chain list.
> It avoids breaking like, 10000 mentions of it across resources.

I don't think any of these apply to containers. Arrowing to containers doesn't suffer from the focus or lag issues. There are no existing resources to break, since no existing resources talk about containers.

Still, I'd love to get @ScottChesworth's thoughts on this.

**Comment by vuplounge** [comment]
I support the request, especially that container effects should be visible in the FX selection dialog initialized from the TCP (Shortcut P).
It doesn't matter too much if containers are folders or not, i.e. if those are all expanded or if you need to press right arrow or similar.
I have encountered several plug-ins that do not expose the parameter properly when accessed from the FX Chain (Shortcut Alt+P), specifically, the value shows always "0" and doesn't change through slider movements or editing the value directly. Therefore, the alternative access method would be desired.
What's more, you can faster switch to another effect's parameters when the parameter list has been opened from the track panel. There, it is possible to press p when on a slider or, the close button etc. and the new FX selection dialog pops up. That's evidently not the case with Alt+P since this places you in the parameter list by default.

**Comment by jcsteh** [comment]
> I have encountered several plug-ins that do not expose the parameter properly when accessed from the FX Chain (Shortcut Alt+P), specifically, the value shows always "0" and doesn't change through slider movements or editing the value directly.

The dialog you see for p vs alt+p is literally identical. If there's a problem there, it needs to be addressed obviously, but it's a separate issue from where the Parameters dialog is invoked.

> What's more, you can faster switch to another effect's parameters when the parameter list has been opened from the track panel. There, it is possible to press p when on a slider or, the close button etc. and the new FX selection dialog pops up.

Intriguing. That's actually a happy accident and not deliberate. I'm surprised it doesn't break, since there's already a parameters dialog open. Still, happy accidents can be useful. :)

**Comment by leejul** [comment]
I provide support with all the users in the French-speaking community and none of them use the FX window to select a plugin and press Ctrl+Shift+P to open the plugin settings window.
I didn't even know this shortcut worked in the FX window.
The FX window is used by users only to add an FX.
Even selecting,, delete or move an FX in the FX chain no longer requires opening the FX window with the ReaperAccessible KeyMap.
We can do all of this directly from TCP.
So, I don't think users will be happy to learn that you now always have to open the FX window in order to select a plugin and access its settings.
For me this is unnecessary manipulation and a loss of efficiency.

**Comment by jcsteh** [comment]
It's reasonable to argue there's a loss of efficiency when you can justify that. The problem is that I'm not seeing any solid justification here. As I noted above, the number of keystrokes is the same, and the issues with focus grabbing and UI lag aren't relevant where focusing containers is concerned.

Nevertheless, if this is something that is desired by multiple users, it's obviously a valid request. It's just a matter of where it fits in terms of priority and if/when someone is willing to put the time into it.

**Comment by jcsteh** [comment]
I will add that this is definitely possible with the REAPER API, so it's just a matter of time and effort.

**Comment by ScottChesworth** [comment]
> I provide support with all the users in the French-speaking community and none of them use the FX window to select a plugin and press Ctrl+Shift+P to open the plugin settings window. I didn't even know this shortcut worked in the FX window.
> 
It doesn't. That's Alt+P.

> Even selecting,, delete or move an FX in the FX chain no longer requires opening the FX window with the ReaperAccessible KeyMap.
> 
Is that also true when working with take-based FX, input FX and monitoring FX? If not, then it still seems like we should be focusing on the FX window seeing as that's the UI where all of these can be managed.

If you already have some way of managing all of that from the TCP on your key map, I'd love to hear about it, perhaps OSARA could adopt the same aproach you've cooked up.

**Comment by leejul** [comment]
If the API allows it, I can also control the FX of items without problem.
So far I haven't received any request about this.
Here, Alt+P in the FX window, changes the Ripple mode.
To open the parameters of a selected effect, the shortcut is Ctrl+Shift+P.
Personally, I'm not going to require users to open the FX window for every FX parameter change.
I already know what their reaction will be.
I would be curious to know what percentage of users in the list open the FX window to make a parameter value change.
And there you have it, I think I have made my point on the subject.

**Comment by ScottChesworth** [comment]
> If the API allows it, I can also control the FX of items without problem.
> 
That doesn't tell me anything about your current approach. Which type or types of FX can be selected, deleted and reordered from the TCP with your key map as things stand right now?

**Comment by leejul** [comment]
The KeyMap offered by ReaperAccessible allows you to select, bypass, delete or change FX position in the FX chain without opening the FX window.
It is also possible to move to the next or previous preset of the selected FX.
So we never open the FX window except to add an FX, 
to search for a specific preset, import or export a list of presets ou access the plugin ui with LBL.
So opening the FX window for all value parameter changes is out of the question as far as I'm concerned.
Loss of efficiency.
