### ISSUE TITLE
Here's a condition where keyboard focus can unexpectedly be stolen away from OSARA's FX Parameters dialog

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#969]
Chris Bartlett reported that when he adjusts band select parameters of TDR Nova (a free EQ plug-in), focus gets grabbed away from our dialog. Follow these steps for a comparison of unexpected vs usual UX:
1. Get TDR Nova, moving by headings on this page until you get to "Free Download": https://www.tokyodawn.net/tdr-nova/
2. Create a track, instantiate Nova, hit Alt+P from the FX chain list to open OSARA's FX Parameters dialog.
3. The "Band 1 selected" parameter will be topmost in the list, and it'll be on by Default. Tab to the slider, hit DownArrow to turn it off, then UpArrow to turn it back on again. AT this point, focus will be grabbed away and we're back in the FX chain list. DOH! This can be reproduced as many times as you like with any of the band select params.
4. Compare that behaviour to what happens if you close the FX window first, then hit P on the track, then adjust any of those band select params. In that case focus remains in our dialog where we want it to stay, ergo my guess is that selecting a band causes the FX window to refresh/redraw/re-whatever and that's when keyboard focus gets nabbed.

Is this something we can protect against at all?

**Comment by jcsteh** [comment]
Assuming you can't repro this elsewhere, I'd say the plugin is explicitly stealing focus when its parameters are tweaked, which is a rather odd thing to do. OSARA explicitly closes the dialog if something steals focus because otherwise, you can get stuck in a situation where the Parameters dialog is open, but you can't get back to it.

Trying to work around this problem is risky because we don't want to get into a situation where another window opens and gets focus, we force focus back to OSARA's dialog, then the user can't get back to the window they just opened. I don't think such a workaround is worth the risk.
