### ISSUE TITLE
Is it possible that the selected track causes OSARA to also tell the db with a switch that enables or disables this functionality?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#981]
Hi everyone!
I'm working on a project with another person.
For some strange reason at mix 18 I found myself with an .rpp file that didn't seem to work.
It was actually the master at -150 db. The sound engineer probably had specific reasons for having the master at -150 dB.
In fact, he told me that the project was working on his computer.
Mystery!
Is it possible to create an OSARA action that announces the track and master track fader volume after the track information?
Obviously with a toggle on off.
For example:
2 BASS 1 item -33.02 dB 
"perhaps the word dB can also be omitted"
Toggle.
Default:
2 BASS 1 item 

Thank you!

**Comment by jcsteh** [comment]
I understand the desire to make troubleshooting easier. However, there are so many ways in which a track could be silent, so this becomes a very slippery slope. Maybe there's an envelope which sets the volume to -150, rather than the trim level. Maybe there's a mute envelope. Maybe there is some weird routing such that a track isn't sent to its parent, but its send is muted. Ultimately, a user, even a sighted user, has to have sufficient understanding to troubleshoot a problem like this. Alternatively, there could be some automated way to troubleshoot it - that's not impossible - but that starts to fall out of scope for OSARA and more into the territory of a troubleshooting plugin targeted at all users, not just screen reader users.

**Comment by ScottChesworth** [comment]
Reopening for discussion because although this wouldn't be a foolproof solution for troubleshooting, I think this could be an option with a much wider use case.
When I'm starting mix prep or doing a mix here, I tamper down as much reporting of information that I don't need to know about as I can. However, frequently I find myself moving through tracks (let's say guitar quads), checking whether they're all set to the same volume as a starting point, and right now the only way to know that is to wiggle volume actions, IE two extra keypresses per single track movement. Strikes me that in such a mixing-based flow, sighted folk might scroll along the mixer with one eye on the volume faders, this option would be a speech-based take on that. I reckon it would be disabled by default, but I can see it being super useful during long stretches of work where I find myself manually verifying track volumes way more often than I'm needing a reminder of how many items are on a track, for example. We already report other dynamic things about each track such as whether it's muted or soloed, seems like optionally reporting volume is in line with those.

If this does get implemented we need to be careful not to make troubleshooting more confusing. Perhaps a solution could be we'd only report static track volume. Once there's a track volume envelope active, we can't account for that, so IMO we should report the presence of that envelope instead, thereby making users aware that they'll need to do their own investigating.

@jcsteh, I'm picturing using this and it's like the thing where we stopped reporting "0 items", probably insignificant to some but that change rocked my world. If I can get it going and submit a PR, are you open to trying it out?

**Comment by jcsteh** [comment]
I don't have a problem with this one thing. I do worry that it's a can of worms, though. If we do this, do we then get requests to implement separate options to report pan, sends, whatever else?

We can actually report the volume respecting envelopes, what the REAPER API calls the "UI volume". I think that's also what we show in the parameters dialog. That raises the question: which is more appropriate to report here? I think the visually visible fader is probably the UI volume, but I'm not certain.

**Comment by jcsteh** [comment]
To be clear, if we do this, I think we should have a solid argument in the bag as to why volume is more important than whatever else and thus justifies auto reporting (and a setting) where other things don't. I don't really care what that argument is, as long as it convinces most folks.

**Comment by ranetto** [comment]
Hi, I can say that sometimes it happened to me too, but I don't think it depends on Osara but on some reaper action that sometimes mutes the master by mistake, however I think it's very simple to control it, for example just look at the vmeters on the master, if the instrument scores minus 150, try turning on the metronome to see if it comes out of the right sound card, if set to the default, if all the other tracks score a level it is clear that the problem can only be on the master track, or on some effects inserted on the master. Clearly an action like this could be useful, but in my opinion it is not so necessary that it cannot be solved without a seeing eye. Reaper does a lot of things and therefore like all software that does a lot it is full of pitfalls. You could also make a script, if someone needs it, to report the volume of all the tracks below a certain level etc. However, in my opinion, it is not that essential.

**Comment by ScottChesworth** [comment]
Looks like this got done via the JAWS scripts instead. I don't like that approach (disparity between screen readers complicates support), but that's where we are.

**Comment by jcsteh** [comment]
Fair enough. I did say I was happy for this to be done as long as the reasoning was crystal clear, but I guess now we don't need to bother with that UX process.

**Comment by Lo-lo78** [comment]
Easily solved with a lua script:
[Announce db for the selected track and for the selected master track.zip](https://github.com/jcsteh/osara/files/14041214/Announce.db.for.the.selected.track.and.for.the.selected.master.track.zip)
